### ISSUE TITLE
IPython 5 terminal not available

### ISSUE THREAD

**Issue by klonuo** [glue-viz/glue#1027]
glue 0.8.1 does not seem to support IPython 5 terminal:

```pytb
Traceback (most recent call last):
  File "c:\python35\lib\site-packages\glue\app\qt\application.py", line 799, in _create_terminal
    **vars(env))
  File "c:\python35\lib\site-packages\glue\app\qt\terminal.py", line 402, in glue_terminal
    return _glue_terminal_3(**kwargs)
  File "c:\python35\lib\site-packages\glue\app\qt\terminal.py", line 381, in _glue_terminal_3
    return in_process_console(console_class=DragAndDropTerminal, **kwargs)
  File "c:\python35\lib\site-packages\glue\app\qt\terminal.py", line 101, in in_process_console
    km.start_kernel()
  File "c:\python35\lib\site-packages\ipykernel\inprocess\manager.py", line 41, in start_kernel
    self.kernel = InProcessKernel(parent=self, session=self.session)
AttributeError: 'QtInProcessKernelManager' object has no attribute 'session'
```

**Comment by astrofrog** [comment]
@klonuo - thanks for the report! I'll look into it today.

**Comment by astrofrog** [comment]
@klonuo - I'm not seeing this issue with IPython 5.0.0b4. Could you clarify:

* Which exact version of IPython you are using
* How you started glue

Thanks!

**Comment by klonuo** [comment]
@astrofrog thanks for your quick replay

I'm using IPython 5.0.0b4 too. I started glue by executing glue.exe from python scripts folder.

I run Python 3.5.1 64bit, and further:
```
> glue-deps list
        GUI FRAMEWORK
               PyQt4:   INSTALLED (PyQt: 4.11.4 - Qt: 4.8.7)
               PyQt5:   NOT INSTALLED
              PySide:   NOT INSTALLED

             REQUIRED
          setuptools:   INSTALLED (23.1.0)
               numpy:   INSTALLED (1.11.0)
          matplotlib:   INSTALLED (2.0.0b1)
              pandas:   INSTALLED (0.18.1)
             astropy:   INSTALLED (1.2.1)

              GENERAL
                dill:   MISSING (Used when saving Glue sessions)
                h5py:   INSTALLED (2.6.0)
               scipy:   INSTALLED (0.17.1)
             skimage:   INSTALLED (0.12.3)

     IPYTHON TERMINAL
             IPython:   INSTALLED (5.0.0b4)
           ipykernel:   INSTALLED (4.3.1)
           qtconsole:   INSTALLED (4.2.1)
           traitlets:   INSTALLED (4.2.1)
            pygments:   INSTALLED (2.1.3)
                 zmq:   INSTALLED (15.2.0)

            ASTRONOMY
               pyavm:   MISSING (Used to parse AVM metadata in image files)

              TESTING
                mock:   MISSING (Used in test code)
              pytest:   MISSING (Used in test code)

               EXPORT
              plotly:   MISSING (Used to explort plots to Plot.ly)
```

**Comment by astrofrog** [comment]
@klonuo - at what point do you see the error - when you start glue, or when you click on the IPython terminal icon?

**Comment by klonuo** [comment]
It's when I click terminal icon.

Maybe I can downgrade IPython to 0.4.2 any see if issue is present and not related to new IPython version, if it helps?
