### ISSUE TITLE
Glue session save not work

### ISSUE THREAD

**Issue by PennyQ** [glue-viz/glue#1079]
Error as below, I tried it with only loading one cube data but still not work, do you have this problem? @astrofrog 

Traceback (most recent call last):
  File "/Users/penny/anaconda/lib/python2.7/site-packages/glueviz-0.9.0.dev29822994-py2.7.egg/glue/utils/misc.py", line 57, in result
    return func(*args, **kwargs)
  File "/Users/penny/anaconda/lib/python2.7/site-packages/glueviz-0.9.0.dev29822994-py2.7.egg/glue/utils/qt/decorators.py", line 23, in result
    return func(*args, **kwargs)
  File "/Users/penny/anaconda/lib/python2.7/site-packages/glueviz-0.9.0.dev29822994-py2.7.egg/glue/app/qt/application.py", line 685, in _choose_save_session
    filter="Glue Session (*.glu);; Glue Session including data (*.glu)")
ValueError: too many values to unpack

**Comment by astrofrog** [comment]
@PennyQ - just to be clear, you loaded a single cube then tried to save a session and you got the following error? Or you got this error while trying to load the session?
