### ISSUE TITLE
.nib error after reinstall glue from conda

### ISSUE THREAD

**Issue by PennyQ** [glue-viz/glue#1138]
I followed all instructions from our doc as installing through conda and also install PySide, but still get the .nib error after I update glue to dev version, the stable version works well :(

> /Users/penny/anaconda/lib/python2.7/site-packages/glueviz-0.9.0.dev3107-py2.7.egg/glue/external/qt.py:6: GlueDeprecationWarning:
> The glue.external.qt subpackage is deprecated - see the v0.9 release announcement for more details
> INFO:glue:Loading plugin vispy_volume failed (Exception: No module named QtGui)
> INFO:glue:Loading plugin vispy_isosurface failed (Exception: cannot import name QtGui)
> INFO:glue:Loading plugin vispy_scatter failed (Exception: cannot import name QtGui)
> INFO:glue:Loading settings from /Users/penny/.glue/settings.cfg
> INFO:glue:Setting BACKGROUND_COLOR already initialized - skipping
> INFO:glue:Setting DATA_ALPHA already initialized - skipping
> INFO:glue:Setting DATA_COLOR already initialized - skipping
> INFO:glue:Setting FOREGROUND_COLOR already initialized - skipping
> INFO:glue:Setting SHOW_LARGE_DATA_WARNING already initialized - skipping
> INFO:glue:Setting SUBSET_COLORS already initialized - skipping
> INFO:glue.core.hub:Subscribing DataCollection (0 data sets)
>      to DataAddComponentMessage
> Qt internal error: qt_menu.nib could not be loaded. The .nib file should be placed in QtGui.framework/Versions/Current/Resources/  or in the resources directory of your application bundle.

@astrofrog Do you know how to fix it? 

I also found Glue installed from pip is more stable than conda... and we could also update the [frequent questions](https://github.com/glue-viz/glue/blob/80c9df4fb6306c1a580e63e60a4ef4c54c7d4553/doc/faq.rst) if we get a solution here :)

**Comment by astrofrog** [comment]
@PennyQ - just to check, why are you installing PySide? (conda should install PyQt by default). Could you let me know the exact commands you used to install glue with conda?

**Comment by PennyQ** [comment]
@astrofrog  All commands I use is listed on our glueviz website:

conda install -c conda-forge glueviz
conda install -c conda-forge glue-vispy-viewers

Without installing pyside I will get following error:
> Traceback (most recent call last):
  File "/Users/penny/anaconda/bin/glue", line 11, in <module>
    load_entry_point('glueviz==0.9.0.dev3107', 'gui_scripts', 'glue')()
  File "/Users/penny/anaconda/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 565, in load_entry_point
  File "/Users/penny/anaconda/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 2598, in load_entry_point
  File "/Users/penny/anaconda/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 2258, in load
  File "/Users/penny/anaconda/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 2264, in resolve
  File "/Users/penny/anaconda/lib/python2.7/site-packages/glueviz-0.9.0.dev3107-py2.7.egg/glue/__init__.py", line 129, in <module>
    from .main import load_plugins
  File "/Users/penny/anaconda/lib/python2.7/site-packages/glueviz-0.9.0.dev3107-py2.7.egg/glue/main.py", line 12, in <module>
    from glue.utils.qt.decorators import die_on_error
  File "/Users/penny/anaconda/lib/python2.7/site-packages/glueviz-0.9.0.dev3107-py2.7.egg/glue/utils/qt/__init__.py", line 3, in <module>
    from .autocomplete_widget import *
  File "/Users/penny/anaconda/lib/python2.7/site-packages/glueviz-0.9.0.dev3107-py2.7.egg/glue/utils/qt/autocomplete_widget.py", line 11, in <module>
    from qtpy import QtGui, QtWidgets
  File "/Users/penny/anaconda/lib/python2.7/site-packages/qtpy/__init__.py", line 125, in <module>
    raise PythonQtError('No Qt bindings could be found')
qtpy.PythonQtError: No Qt bindings could be found

Conda install pyqt4 doesn't work on my laptop, package not found my osx-64, so I install pyside with following commands but then got this .nib error :(
> conda install pyside
export QT_API=pyside

**Comment by astrofrog** [comment]
The issue is that you have the developer version of glueviz installed already and this is the one that gets called when you type 'glue' (you can see in the error log it mentions version 0.9.0.dev which is the developer version). In addition to this there is an issue with conda-forge which means that it doesn't work well with qtpy right now. The average user won't see these issues because they aren't using the developer version of glue (which uses qtpy). In your case, to fix this, try doing:

```
conda remove pyside
conda install pyqt=4.11.3
```

I will investigate the issue with the nib file.

**Comment by astrofrog** [comment]
PySide is broken in conda: https://github.com/ContinuumIO/anaconda-issues/issues/1132
