### ISSUE TITLE
Failed to restore session stored before Glue0.9

### ISSUE THREAD

**Issue by PennyQ** [glue-viz/glue#1152]
So I had a session that was saved before glue9.0 , data is not included, but I got several errors when trying to open it under latest-dev version of Glue.

The first one is because we use `Subset` instead of `PatchedElementSubsetState`, so I also replaced them in my `.glu file`.

> Traceback (most recent call last):
>   File "/Users/penny/Works/Gluedev/glue/glue/glue/utils/qt/decorators.py", line 53, in wrapper
>     return func(_args, *_kwargs)
>   File "/Users/penny/Works/Gluedev/glue/glue/glue/app/qt/application.py", line 730, in _restore_session
>     ga = self.restore_session(file_name)
> ...
>   File "/Users/penny/Works/Gluedev/glue/glue/glue/core/state.py", line 409, in _dispatch
>     typ = lookup_class_with_patches(rec['_type'])
>   File "/Users/penny/Works/Gluedev/glue/glue/glue/core/state.py", line 120, in lookup_class_with_patches
>     return lookup_class(name)
>   File "/Users/penny/Works/Gluedev/glue/glue/glue/utils/misc.py", line 81, in lookup_class
>     raise ValueError("Object '{0}' not found".format(ref))
> ValueError: Object 'glue_vispy_viewers.common.toolbar.PatchedElementSubsetState' not found

The second is as below, which I don't know how to solve it. @astrofrog Do you know the reason for it? thanks! All data is here https://1drv.ms/f/s!Avn4HRIa1XyWil0-SO9TKF2xGnM9

> Traceback (most recent call last):
>   File "/Users/penny/Works/Gluedev/glue/glue/glue/utils/qt/decorators.py", line 53, in wrapper
>     return func(_args, *_kwargs)
>   File "/Users/penny/Works/Gluedev/glue/glue/glue/app/qt/application.py", line 730, in _restore_session
>     ga = self.restore_session(file_name)
>   File "/Users/penny/Works/Gluedev/glue/glue/glue/app/qt/application.py", line 772, in restore_session
>     ga = Application.restore_session(path)
>   File "/Users/penny/Works/Gluedev/glue/glue/glue/core/application_base.py", line 128, in restore_session
>     return state.object('__main__')
>   File "/Users/penny/Works/Gluedev/glue/glue/glue/core/registry.py", line 91, in wrapper
>     return func(_args, *_kwargs)
>   File "/Users/penny/Works/Gluedev/glue/glue/glue/core/state.py", line 456, in object
>     obj = func(rec, self)
>   File "/Users/penny/Works/Gluedev/glue/glue/glue/core/application_base.py", line 310, in **setgluestate**
>     viewer = context.object(v)
>   File "/Users/penny/Works/Gluedev/glue/glue/glue/core/registry.py", line 91, in wrapper
>     return func(_args, *_kwargs)
>   File "/Users/penny/Works/Gluedev/glue/glue/glue/core/state.py", line 456, in object
>     obj = func(rec, self)
>   File "/Users/penny/Works/Gluedev/glue/glue/glue/core/application_base.py", line 480, in **setgluestate**
>     result.restore_layers(rec['layers'], context)
>   File "/Users/penny/Works/Gluedev/glue/glue/glue/viewers/common/qt/mpl_widget.py", line 39, in wrapper
>     result = func(_args, *_kwargs)
>   File "/Users/penny/Works/Gluedev/glue/glue/glue/viewers/image/qt/viewer_widget.py", line 352, in restore_layers
>     self.set_attribute_combo(self.client.display_data)
>   File "/Users/penny/Works/Gluedev/glue/glue/glue/external/echo.py", line 313, in **exit**
>     p.notify(self.instance, old, new)
>   File "/Users/penny/Works/Gluedev/glue/glue/glue/external/echo.py", line 104, in notify
>     cback(new)
>   File "/Users/penny/Works/Gluedev/glue/glue/glue/utils/misc.py", line 57, in result
>     return func(_args, *_kwargs)
>   File "/Users/penny/Works/Gluedev/glue/glue/glue/viewers/image/qt/viewer_widget.py", line 220, in _display_data_changed
>     self.client._update_and_redraw()
>   File "/Users/penny/Works/Gluedev/glue/glue/glue/viewers/image/client.py", line 791, in _update_and_redraw
>     self._update_data_plot()
>   File "/Users/penny/Works/Gluedev/glue/glue/glue/viewers/image/client.py", line 38, in result
>     return func(_args, *_kwargs)
>   File "/Users/penny/Works/Gluedev/glue/glue/glue/viewers/image/client.py", line 349, in _update_data_plot
>     a.update(view, transpose)
>   File "/Users/penny/Works/Gluedev/glue/glue/glue/viewers/image/layer_artist.py", line 335, in update
>     mask = subset.to_mask(view[1:])
>   File "/Users/penny/Works/Gluedev/glue/glue/glue/core/subset.py", line 262, in to_mask
>     return self.subset_state.to_mask(self.data, view)
>   File "/Users/penny/Works/Gluedev/glue/glue/glue/core/subset.py", line 517, in to_mask
>     if i == self.xatt.axis or i == self.yatt.axis:
> AttributeError: 'ComponentID' object has no attribute 'axis'

**Comment by astrofrog** [comment]
@PennyQ - can you send me the session file by email?

**Comment by astrofrog** [comment]
Should be fixed now!

**Comment by mpound** [comment]
I get this same error message when trying to load old sessions from July 25 2016, which I think was v0.9.  The error occurs against branch v0.9.x and against master (version 0.10.0.dev03175).   

### Here's the traceback:

Traceback (most recent call last):
  File "/home/mpound/.local/lib/python2.7/site-packages/glueviz-0.10.0.dev3175-py2.7.egg/glue/utils/qt/decorators.py", line 53, in wrapper
    return func(*args, **kwargs)
  File "/home/mpound/.local/lib/python2.7/site-packages/glueviz-0.10.0.dev3175-py2.7.egg/glue/app/qt/application.py", line 730, in _restore_session
    ga = self.restore_session(file_name)
  File "/home/mpound/.local/lib/python2.7/site-packages/glueviz-0.10.0.dev3175-py2.7.egg/glue/app/qt/application.py", line 772, in restore_session
    ga = Application.restore_session(path)
  File "/home/mpound/.local/lib/python2.7/site-packages/glueviz-0.10.0.dev3175-py2.7.egg/glue/core/application_base.py", line 128, in restore_session
    return state.object('__main__')
  File "/home/mpound/.local/lib/python2.7/site-packages/glueviz-0.10.0.dev3175-py2.7.egg/glue/core/registry.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/mpound/.local/lib/python2.7/site-packages/glueviz-0.10.0.dev3175-py2.7.egg/glue/core/state.py", line 457, in object
    obj = func(rec, self)
  File "/home/mpound/.local/lib/python2.7/site-packages/glueviz-0.10.0.dev3175-py2.7.egg/glue/core/application_base.py", line 310, in __setgluestate__
    viewer = context.object(v)
  File "/home/mpound/.local/lib/python2.7/site-packages/glueviz-0.10.0.dev3175-py2.7.egg/glue/core/registry.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/mpound/.local/lib/python2.7/site-packages/glueviz-0.10.0.dev3175-py2.7.egg/glue/core/state.py", line 457, in object
    obj = func(rec, self)
  File "/home/mpound/.local/lib/python2.7/site-packages/glueviz-0.10.0.dev3175-py2.7.egg/glue/core/application_base.py", line 480, in __setgluestate__
    result.restore_layers(rec['layers'], context)
  File "/home/mpound/.local/lib/python2.7/site-packages/glueviz-0.10.0.dev3175-py2.7.egg/glue/viewers/common/qt/mpl_widget.py", line 39, in wrapper
    result = func(*args, **kwargs)
  File "/home/mpound/.local/lib/python2.7/site-packages/glueviz-0.10.0.dev3175-py2.7.egg/glue/viewers/scatter/qt/viewer_widget.py", line 278, in restore_layers
    self._update_combos()
  File "/home/mpound/.local/lib/python2.7/site-packages/glueviz-0.10.0.dev3175-py2.7.egg/glue/viewers/common/qt/mpl_widget.py", line 39, in wrapper
    result = func(*args, **kwargs)
  File "/home/mpound/.local/lib/python2.7/site-packages/glueviz-0.10.0.dev3175-py2.7.egg/glue/viewers/scatter/qt/viewer_widget.py", line 152, in _update_combos
    self.client.xatt = self.xatt
  File "/home/mpound/.local/lib/python2.7/site-packages/glueviz-0.10.0.dev3175-py2.7.egg/glue/external/echo.py", line 72, in __set__
    self.notify(instance, old, new)
  File "/home/mpound/.local/lib/python2.7/site-packages/glueviz-0.10.0.dev3175-py2.7.egg/glue/external/echo.py", line 104, in notify
    cback(new)
  File "/home/mpound/.local/lib/python2.7/site-packages/glueviz-0.10.0.dev3175-py2.7.egg/glue/viewers/scatter/client.py", line 245, in _set_xydata
    self._snap_xlim()
  File "/home/mpound/.local/lib/python2.7/site-packages/glueviz-0.10.0.dev3175-py2.7.egg/glue/viewers/scatter/client.py", line 161, in _snap_xlim
    rng = self._visible_limits(0)
  File "/home/mpound/.local/lib/python2.7/site-packages/glueviz-0.10.0.dev3175-py2.7.egg/glue/viewers/scatter/client.py", line 154, in _visible_limits
    return visible_limits(self.artists, axis)
  File "/home/mpound/.local/lib/python2.7/site-packages/glueviz-0.10.0.dev3175-py2.7.egg/glue/core/util.py", line 299, in visible_limits
    xy = art.get_data()
  File "/home/mpound/.local/lib/python2.7/site-packages/glueviz-0.10.0.dev3175-py2.7.egg/glue/viewers/scatter/layer_artist.py", line 89, in get_data
    return self.layer[self.xatt].ravel(), self.layer[self.yatt].ravel()
  File "/home/mpound/.local/lib/python2.7/site-packages/glueviz-0.10.0.dev3175-py2.7.egg/glue/core/subset.py", line 368, in __getitem__
    ma = self.to_mask(v)
  File "/home/mpound/.local/lib/python2.7/site-packages/glueviz-0.10.0.dev3175-py2.7.egg/glue/core/subset.py", line 262, in to_mask
    return self.subset_state.to_mask(self.data, view)
  File "/home/mpound/.local/lib/python2.7/site-packages/glueviz-0.10.0.dev3175-py2.7.egg/glue/core/decorators.py", line 32, in wrapper
    result = func(*args, **kwargs)
  File "/home/mpound/.local/lib/python2.7/site-packages/glueviz-0.10.0.dev3175-py2.7.egg/glue/core/subset.py", line 778, in to_mask
    self.state2.to_mask(data, view))
  File "/home/mpound/.local/lib/python2.7/site-packages/glueviz-0.10.0.dev3175-py2.7.egg/glue/core/decorators.py", line 32, in wrapper
    result = func(*args, **kwargs)
  File "/home/mpound/.local/lib/python2.7/site-packages/glueviz-0.10.0.dev3175-py2.7.egg/glue/core/subset.py", line 777, in to_mask
    return self.op(self.state1.to_mask(data, view),
  File "/home/mpound/.local/lib/python2.7/site-packages/glueviz-0.10.0.dev3175-py2.7.egg/glue/core/subset.py", line 514, in to_mask
    if i == self.xatt.axis or i == self.yatt.axis:
AttributeError: 'ComponentID' object has no attribute 'axis'

### And Version Information
Glue: 0.10.0.dev03175
PyQt4: PyQt: 4.10.4 - Qt: 4.8.5
PyQt5: Not installed
PySide: Not installed
qtpy: 1.1.2
setuptools: 28.7.1
numpy: 1.9.2
matplotlib: 2.0.0b4
pandas: 0.14.0
astropy: 1.2.1
dill: Not installed
h5py: 2.3.0
xlrd: unknown version
scipy: 0.14.0
skimage: 0.10.0
IPython: 2.1.0
ipykernel: Not installed
qtconsole: Not installed
traitlets: Not installed
pygments: 1.6
zmq: 14.3.0
pyavm: Not installed
spectral_cube: Not installed
ginga: Not installed
astrodendro: Not installed
mock: 1.0.1
pytest: 2.5.2
plotly: Not installed

### Example failing glue file and associated FITS

[loadfail.zip](https://github.com/glue-viz/glue/files/566998/loadfail.zip)

**Comment by mpound** [comment]
@astrofrog Wondering if you can reproduce the failure using the data I provided.

**Comment by astrofrog** [comment]
@mpound - I'll take a look at this - thanks for the detailed report!

**Comment by astrofrog** [comment]
@mpound - I'm sorry for not getting back to you sooner. I've fixed this in #1243 and the fix will be in glue 0.10.1 (which will be released shortly)
