### ISSUE TITLE
Issue Showing 2D Image of Merged Spectral Cubes

### ISSUE THREAD

**Issue by catherinezucker** [glue-viz/glue#1291]
I have three spectral cubes of the same region which I have merged, and now I am trying to display a 2D image of them so I can make a selection and view the spectrum in that region for each of the three cubes. The 2D image rendering worked in 0.9.1 but it no longer works in 0.10.3 (which I recently updated to). It just refuses to display. Here's the error I get. I'm happy to provide the cubes if that helps. Thanks!

WARNING: VerifyWarning: Invalid 'BLANK' keyword in header.  The 'BLANK' keyword is only applicable to integer data, and will be ignored in this HDU. [astropy.io.fits.hdu.image]
WARNING: VerifyWarning: Invalid 'BLANK' keyword in header.  The 'BLANK' keyword is only applicable to integer data, and will be ignored in this HDU. [astropy.io.fits.hdu.image]
WARNING: VerifyWarning: Invalid 'BLANK' keyword in header.  The 'BLANK' keyword is only applicable to integer data, and will be ignored in this HDU. [astropy.io.fits.hdu.image]
WARNING: VerifyWarning: Invalid 'BLANK' keyword in header.  The 'BLANK' keyword is only applicable to integer data, and will be ignored in this HDU. [astropy.io.fits.hdu.image]
WARNING: VerifyWarning: Invalid 'BLANK' keyword in header.  The 'BLANK' keyword is only applicable to integer data, and will be ignored in this HDU. [astropy.io.fits.hdu.image]
WARNING: VerifyWarning: Invalid 'BLANK' keyword in header.  The 'BLANK' keyword is only applicable to integer data, and will be ignored in this HDU. [astropy.io.fits.hdu.image]
Traceback (most recent call last):
  File "//anaconda/lib/python3.5/site-packages/glue/core/data.py", line 796, in __getitem__
    comp = self._components[key]
KeyError: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "//anaconda/lib/python3.5/site-packages/glue/app/qt/mdi_area.py", line 61, in dropEvent
    new_layer(layer)
  File "//anaconda/lib/python3.5/site-packages/glue/app/qt/mdi_area.py", line 51, in new_layer
    self._application.choose_new_data_viewer(layer)
  File "//anaconda/lib/python3.5/site-packages/glue/app/qt/application.py", line 690, in choose_new_data_viewer
    return self.do(cmd)
  File "//anaconda/lib/python3.5/site-packages/glue/core/application_base.py", line 218, in do
    self._cmds.do(command)
  File "//anaconda/lib/python3.5/site-packages/glue/core/command.py", line 126, in do
    result = cmd.do(self._session)
  File "//anaconda/lib/python3.5/site-packages/glue/core/command.py", line 216, in do
    v = session.application.new_data_viewer(self.viewer, self.data)
  File "//anaconda/lib/python3.5/site-packages/glue/viewers/common/qt/mpl_widget.py", line 45, in wrapper
    result = func(*args, **kwargs)
  File "//anaconda/lib/python3.5/site-packages/glue/core/application_base.py", line 85, in new_data_viewer
    if data and not c.add_data(data):
  File "//anaconda/lib/python3.5/site-packages/glue/viewers/common/qt/mpl_widget.py", line 45, in wrapper
    result = func(*args, **kwargs)
  File "//anaconda/lib/python3.5/site-packages/glue/viewers/image/qt/viewer_widget.py", line 123, in add_data
    self.set_attribute_combo(self.client.display_data)
  File "//anaconda/lib/python3.5/site-packages/glue/external/echo/core.py", line 405, in __exit__
    p.notify(self.instance, old, new)
  File "//anaconda/lib/python3.5/site-packages/glue/external/echo/core.py", line 106, in notify
    cback(new)
  File "//anaconda/lib/python3.5/site-packages/glue/utils/misc.py", line 58, in result
    return func(*args, **kwargs)
  File "//anaconda/lib/python3.5/site-packages/glue/viewers/image/qt/viewer_widget.py", line 220, in _display_data_changed
    self.client._update_and_redraw()
  File "//anaconda/lib/python3.5/site-packages/glue/viewers/image/client.py", line 791, in _update_and_redraw
    self._update_data_plot()
  File "//anaconda/lib/python3.5/site-packages/glue/viewers/image/client.py", line 38, in result
    return func(*args, **kwargs)
  File "//anaconda/lib/python3.5/site-packages/glue/viewers/image/client.py", line 337, in _update_data_plot
    self._image = self.display_data[view]
  File "//anaconda/lib/python3.5/site-packages/glue/core/data.py", line 798, in __getitem__
    raise IncompatibleAttribute(key)
glue.core.exceptions.IncompatibleAttribute: None

**Comment by astrofrog** [comment]
@catherinezucker - this is fixed in 0.10.4 which will be available in conda in a few hours :)
