### ISSUE TITLE
error creating 3D scatter plot

### ISSUE THREAD

**Issue by shichuzhu** [glue-viz/glue#1306]
I encountered the following error when creating 3D scatter plot with a dataset. Note that 2D scatter plot works fine.
I'm using Samsung chromebook plus (ARM architecture) with Ubuntu Xeniel installed by crouton.

Here's the glueviz version info:
Glue: 0.10.4
PyQt4: PyQt: 4.11.4 - Qt: 4.8.7
PyQt5: Not installed
PySide: Not installed
qtpy: 1.2.1
setuptools: 20.7.0
numpy: 1.11.0
matplotlib: 1.5.1
pandas: 0.17.1
astropy: 1.3.3
dill: 0.2.6
h5py: 2.7.0
xlrd: 1.0.0
glue_vispy_viewers: 0.7.2
IPython: 6.1.0
qtconsole: 4.3.0
ipykernel: 4.6.1
traitlets: 4.3.2
pygments: 2.2.0
zmq: 16.0.2
scipy: 0.17.0
skimage: Not installed
pyavm: Not installed
spectral_cube: Not installed
astrodendro: Not installed
mock: Not installed
pytest: Not installed
plotly: Not installed

Below is the error info when creating the 3D scatter plot ---------------------------------------------
WARNING: Although PyQt4 is already imported, the PyQt4 backend could not
be used ("cannot import name 'QtOpenGL'"). 
Note that running multiple GUI toolkits simultaneously can cause side effects.
WARNING:vispy:Although PyQt4 is already imported, the PyQt4 backend could not
be used ("cannot import name 'QtOpenGL'"). 
Note that running multiple GUI toolkits simultaneously can cause side effects.
INFO: Could not import backend "PyQt5":
Refusing to import PyQt5 because PyQt4.QtCore is already imported.
INFO:vispy:Could not import backend "PyQt5":
Refusing to import PyQt5 because PyQt4.QtCore is already imported.
INFO: Could not import backend "PySide":
Refusing to import PySide because PyQt4.QtCore is already imported.
INFO:vispy:Could not import backend "PySide":
Refusing to import PySide because PyQt4.QtCore is already imported.
INFO: Could not import backend "Pyglet":
No module named 'pyglet'
INFO:vispy:Could not import backend "Pyglet":
No module named 'pyglet'
INFO: Could not import backend "Glfw":
GLFW library not found
INFO:vispy:Could not import backend "Glfw":
GLFW library not found
INFO: Could not import backend "SDL2":
No module named 'sdl2'
INFO:vispy:Could not import backend "SDL2":
No module named 'sdl2'
INFO: Could not import backend "wx":
No module named 'wx'
INFO:vispy:Could not import backend "wx":
No module named 'wx'
libEGL warning: DRI2: failed to authenticate
INFO: Could not import backend "EGL":
Not ready for testing
INFO:vispy:Could not import backend "EGL":
Not ready for testing
INFO: Could not import backend "osmesa":
OSMesa library not found
INFO:vispy:Could not import backend "osmesa":
OSMesa library not found
Traceback (most recent call last):
  File "/home/shichu/.local/lib/python3.5/site-packages/glue/app/qt/mdi_area.py", line 61, in dropEvent
    new_layer(layer)
  File "/home/shichu/.local/lib/python3.5/site-packages/glue/app/qt/mdi_area.py", line 51, in new_layer
    self._application.choose_new_data_viewer(layer)
  File "/home/shichu/.local/lib/python3.5/site-packages/glue/app/qt/application.py", line 690, in choose_new_data_viewer
    return self.do(cmd)
  File "/home/shichu/.local/lib/python3.5/site-packages/glue/core/application_base.py", line 218, in do
    self._cmds.do(command)
  File "/home/shichu/.local/lib/python3.5/site-packages/glue/core/command.py", line 126, in do
    result = cmd.do(self._session)
  File "/home/shichu/.local/lib/python3.5/site-packages/glue/core/command.py", line 216, in do
    v = session.application.new_data_viewer(self.viewer, self.data)
  File "/home/shichu/.local/lib/python3.5/site-packages/glue/viewers/common/qt/mpl_widget.py", line 45, in wrapper
    result = func(*args, **kwargs)
  File "/home/shichu/.local/lib/python3.5/site-packages/glue/core/application_base.py", line 82, in new_data_viewer
    c = viewer_class(self._session)
  File "/home/shichu/.local/lib/python3.5/site-packages/glue/viewers/common/qt/data_viewer.py", line 29, in __call__
    obj = type.__call__(cls, *args, **kwargs)
  File "/home/shichu/.local/lib/python3.5/site-packages/glue_vispy_viewers/common/vispy_data_viewer.py", line 56, in __init__
    self._vispy_widget = VispyWidgetHelper(viewer_state=self.state)
  File "/home/shichu/.local/lib/python3.5/site-packages/glue_vispy_viewers/common/vispy_widget.py", line 25, in __init__
    bgcolor=rgb(settings.BACKGROUND_COLOR))
  File "/home/shichu/.local/lib/python3.5/site-packages/glue_vispy_viewers/extern/vispy/scene/canvas.py", line 136, in __init__
    always_on_top, px_scale)
  File "/home/shichu/.local/lib/python3.5/site-packages/glue_vispy_viewers/extern/vispy/app/canvas.py", line 169, in __init__
    self._app = use_app(call_reuse=False)
  File "/home/shichu/.local/lib/python3.5/site-packages/glue_vispy_viewers/extern/vispy/app/_default_app.py", line 47, in use_app
    default_app = Application(backend_name)
  File "/home/shichu/.local/lib/python3.5/site-packages/glue_vispy_viewers/extern/vispy/app/application.py", line 49, in __init__
    self._use(backend_name)
  File "/home/shichu/.local/lib/python3.5/site-packages/glue_vispy_viewers/extern/vispy/app/application.py", line 238, in _use
    'PyQt' % [b[0] for b in CORE_BACKENDS])
RuntimeError: Could not import any of the backends. You need to install any of ['PyQt4', 'PyQt5', 'PySide', 'Pyglet', 'Glfw', 'SDL2', 'wx', 'EGL', 'osmesa']. We recommend PyQt

**Comment by astrofrog** [comment]
@shichuzhu - It looks like your installation of PyQt is missing the OpenGL bindings. How did you install PyQt? In any case, we should have a better error message when this is the case!

**Comment by shichuzhu** [comment]
@astrofrog I installed PyQt by the ubuntu repository
sudo apt-get install python-qt4

I then installed glueviz using
pip3 install glueviz
