### ISSUE TITLE
Error relating to deleted label

### ISSUE THREAD

**Issue by astrofrog** [glue-viz/glue#1349]
Under certain conditions, users might see something like:

```
Traceback (most recent call last):
File "/Users/agoodman/anaconda/lib/python2.7/site-packages/glue/core/application_base.py", line 25, in wrapper
return func(*args, **kwargs)
File "/Users/agoodman/anaconda/lib/python2.7/site-packages/glue/core/application_base.py", line 169, in load_data
d = load_data(path)
File "/Users/agoodman/anaconda/lib/python2.7/site-packages/glue/core/data_factories/helpers.py", line 237, in load_data
d = as_list(factory(path, **kwargs))
File "/Users/agoodman/anaconda/lib/python2.7/site-packages/glue/core/data_factories/helpers.py", line 330, in auto_data
return fac(filename, *args, **kwargs)
File "/Users/agoodman/anaconda/lib/python2.7/site-packages/glue/core/data_factories/astropy_table.py", line 93, in astropy_tabular_data_votable
return astropy_tabular_data(*args, **kwargs)
File "/Users/agoodman/anaconda/lib/python2.7/site-packages/glue/core/data_factories/astropy_table.py", line 66, in astropy_tabular_data
table = astropy_table_read(*args, **kwargs)
File "/Users/agoodman/anaconda/lib/python2.7/site-packages/glue/core/data_factories/astropy_table.py", line 49, in astropy_table_read
return Table.read(*args, **kwargs)
File "/Users/agoodman/anaconda/lib/python2.7/site-packages/astropy/table/table.py", line 2450, in read
return io_registry.read(cls, *args, **kwargs)
File "/Users/agoodman/anaconda/lib/python2.7/site-packages/astropy/io/registry.py", line 468, in read
data = reader(*args, **kwargs)
File "/Users/agoodman/anaconda/lib/python2.7/site-packages/astropy/io/votable/connect.py", line 73, in read_table_votable
input = parse(input, table_id=table_id)
File "/Users/agoodman/anaconda/lib/python2.7/site-packages/astropy/io/votable/table.py", line 117, in parse
pedantic = conf.pedantic
File "/Users/agoodman/anaconda/lib/python2.7/site-packages/astropy/config/configuration.py", line 278, in __get__
return self()
File "/Users/agoodman/anaconda/lib/python2.7/site-packages/astropy/config/configuration.py", line 423, in __call__
AstropyDeprecationWarning)
File "/Users/agoodman/anaconda/lib/python2.7/site-packages/astropy/logger.py", line 220, in _showwarning
self.warning(message)
File "/Users/agoodman/anaconda/lib/python2.7/logging/__init__.py", line 1179, in warning
self._log(WARNING, msg, args, **kwargs)
File "/Users/agoodman/anaconda/lib/python2.7/logging/__init__.py", line 1286, in _log
self.handle(record)
File "/Users/agoodman/anaconda/lib/python2.7/logging/__init__.py", line 1296, in handle
self.callHandlers(record)
File "/Users/agoodman/anaconda/lib/python2.7/logging/__init__.py", line 1336, in callHandlers
hdlr.handle(record)
File "/Users/agoodman/anaconda/lib/python2.7/logging/__init__.py", line 759, in handle
self.emit(record)
File "/Users/agoodman/anaconda/lib/python2.7/site-packages/astropy/logger.py", line 561, in emit
color_print(record.levelname, 'brown', end='', file=stream)
File "/Users/agoodman/anaconda/lib/python2.7/site-packages/astropy/utils/console.py", line 392, in color_print
write(msg)
File "/Users/agoodman/anaconda/lib/python2.7/site-packages/glue/app/qt/application.py", line 156, in write
self.stderr.write(message)
File "/Users/agoodman/anaconda/lib/python2.7/site-packages/glue/app/qt/application.py", line 159, in write
self._status.setPixmap(status_pixmap(attention=True))
RuntimeError: wrapped C/C++ object of type ClickableLabel has been deleted
```

I wonder if this can happen if the user resets or loads a session since the label from the previous window may still be attached to stderr.

**Comment by astrofrog** [comment]
This should no longer be relevant now that the status is no longer shown in the pixmap
