### ISSUE TITLE
Can no longer drag catalogs onto 2D images in latest dev version

### ISSUE THREAD

**Issue by catherinezucker** [glue-viz/glue#1379]
Try to drag the W5 catalog onto the W5 fits image in the glue tutorial. You get the following error...

Traceback (most recent call last):
  File "/anaconda/lib/python3.6/site-packages/glue/viewers/common/qt/data_viewer.py", line 106, in dropEvent
    self.request_add_layer(layer)
  File "/anaconda/lib/python3.6/site-packages/glue/core/application_base.py", line 354, in request_add_layer
    self._session.command_stack.do(cmd)
  File "/anaconda/lib/python3.6/site-packages/glue/core/command.py", line 126, in do
    result = cmd.do(self._session)
  File "/anaconda/lib/python3.6/site-packages/glue/core/command.py", line 235, in do
    self.viewer.add_layer(self.layer)
  File "/anaconda/lib/python3.6/site-packages/glue/core/application_base.py", line 358, in add_layer
    self.add_data(layer)
  File "/anaconda/lib/python3.6/site-packages/glue/utils/matplotlib.py", line 158, in wrapper
    result = func(*args, **kwargs)
  File "/anaconda/lib/python3.6/site-packages/glue/viewers/image/qt/data_viewer.py", line 80, in add_data
    result = super(ImageViewer, self).add_data(data)
  File "/anaconda/lib/python3.6/site-packages/glue/utils/matplotlib.py", line 154, in wrapper
    return func(*args, **kwargs)
  File "/anaconda/lib/python3.6/site-packages/glue/viewers/common/qt/data_viewer_with_state.py", line 77, in add_data
    layer = self.get_data_layer_artist(data)
  File "/anaconda/lib/python3.6/site-packages/glue/utils/matplotlib.py", line 154, in wrapper
    return func(*args, **kwargs)
  File "/anaconda/lib/python3.6/site-packages/glue/viewers/image/qt/data_viewer.py", line 148, in get_data_layer_artist
    return self.get_layer_artist(cls, layer=layer, layer_state=layer_state)
  File "/anaconda/lib/python3.6/site-packages/glue/utils/matplotlib.py", line 154, in wrapper
    return func(*args, **kwargs)
  File "/anaconda/lib/python3.6/site-packages/glue/viewers/matplotlib/qt/data_viewer.py", line 113, in get_layer_artist
    return cls(self.axes, self.state, layer=layer, layer_state=layer_state)
  File "/anaconda/lib/python3.6/site-packages/glue/utils/matplotlib.py", line 154, in wrapper
    return func(*args, **kwargs)
TypeError: _scatter_artist() got an unexpected keyword argument 'layer_state'
Traceback (most recent call last):
  File "/anaconda/lib/python3.6/site-packages/glue/viewers/common/qt/data_viewer.py", line 106, in dropEvent
    self.request_add_layer(layer)
  File "/anaconda/lib/python3.6/site-packages/glue/core/application_base.py", line 354, in request_add_layer
    self._session.command_stack.do(cmd)
  File "/anaconda/lib/python3.6/site-packages/glue/core/command.py", line 126, in do
    result = cmd.do(self._session)
  File "/anaconda/lib/python3.6/site-packages/glue/core/command.py", line 235, in do
    self.viewer.add_layer(self.layer)
  File "/anaconda/lib/python3.6/site-packages/glue/core/application_base.py", line 358, in add_layer
    self.add_data(layer)
  File "/anaconda/lib/python3.6/site-packages/glue/utils/matplotlib.py", line 158, in wrapper
    result = func(*args, **kwargs)
  File "/anaconda/lib/python3.6/site-packages/glue/viewers/image/qt/data_viewer.py", line 80, in add_data
    result = super(ImageViewer, self).add_data(data)
  File "/anaconda/lib/python3.6/site-packages/glue/utils/matplotlib.py", line 154, in wrapper
    return func(*args, **kwargs)
  File "/anaconda/lib/python3.6/site-packages/glue/viewers/common/qt/data_viewer_with_state.py", line 77, in add_data
    layer = self.get_data_layer_artist(data)
  File "/anaconda/lib/python3.6/site-packages/glue/utils/matplotlib.py", line 154, in wrapper
    return func(*args, **kwargs)
  File "/anaconda/lib/python3.6/site-packages/glue/viewers/image/qt/data_viewer.py", line 148, in get_data_layer_artist
    return self.get_layer_artist(cls, layer=layer, layer_state=layer_state)
  File "/anaconda/lib/python3.6/site-packages/glue/utils/matplotlib.py", line 154, in wrapper
    return func(*args, **kwargs)
  File "/anaconda/lib/python3.6/site-packages/glue/viewers/matplotlib/qt/data_viewer.py", line 113, in get_layer_artist
    return cls(self.axes, self.state, layer=layer, layer_state=layer_state)
  File "/anaconda/lib/python3.6/site-packages/glue/utils/matplotlib.py", line 154, in wrapper
    return func(*args, **kwargs)
TypeError: _scatter_artist() got an unexpected keyword argument 'layer_state'

Here's my version info:
Glue: 0.11.0.dev03853
PyQt4: Not installed
PyQt5: PyQt: 5.6 - Qt: 5.6.2
PySide: Not installed
qtpy: 1.2.1
setuptools: 27.2.0
numpy: 1.12.1
matplotlib: 2.0.2
pandas: 0.20.1
astropy: 1.3.2
dill: 0.2.6
h5py: 2.7.0
xlrd: 1.0.0
glue_vispy_viewers: 0.8.dev0
IPython: 5.3.0
qtconsole: 4.3.0
ipykernel: 4.6.1
traitlets: 4.3.2
pygments: 2.2.0
zmq: 16.0.2
scipy: 0.19.0
skimage: 0.13.0
pyavm: 0.9.2
spectral_cube: 0.4.0
astrodendro: 0.2.0
mock: 2.0.0
pytest: 3.0.7
plotly: 2.0.9

Thanks!!!

**Comment by catherinezucker** [comment]
Thanks, Tom! Will there be a conda version for this as well?

**Comment by astrofrog** [comment]
@catherinezucker - the conda package should be updated now :)
