### ISSUE TITLE
Error when using Table viewer with PyQt4

### ISSUE THREAD

**Issue by astrofrog** [glue-viz/glue#1398]
A user reported the following exception:

```
Traceback (most recent call last):

File "/Users/chrusher/anaconda/lib/python2.7/site-packages/glue/utils/misc.py", line 58, in result
  return func(*args, **kwargs)
File "/Users/chrusher/anaconda/lib/python2.7/site-packages/glue/app/qt/layer_tree_widget.py", line 120, in _do_action
  self.app.choose_new_data_viewer(data)
File "/Users/chrusher/anaconda/lib/python2.7/site-packages/glue/app/qt/application.py", line 754, in choose_new_data_viewer
  return self.do(cmd)
File "/Users/chrusher/anaconda/lib/python2.7/site-packages/glue/core/application_base.py", line 218, in do
  self._cmds.do(command)
File "/Users/chrusher/anaconda/lib/python2.7/site-packages/glue/core/command.py", line 126, in do
  result = cmd.do(self._session)
File "/Users/chrusher/anaconda/lib/python2.7/site-packages/glue/core/command.py", line 216, in do
  v = session.application.new_data_viewer(self.viewer, self.data)
File "/Users/chrusher/anaconda/lib/python2.7/site-packages/glue/utils/matplotlib.py", line 158, in wrapper
  result = func(*args, **kwargs)
File "/Users/chrusher/anaconda/lib/python2.7/site-packages/glue/core/application_base.py", line 82, in new_data_viewer
  c = viewer_class(self._session)
File "/Users/chrusher/anaconda/lib/python2.7/site-packages/glue/viewers/common/qt/data_viewer.py", line 29, in __call__
  obj = type.__call__(cls, *args, **kwargs)
File "/Users/chrusher/anaconda/lib/python2.7/site-packages/glue/viewers/table/qt/data_viewer.py", line 196, in __init__
  hdr.setSectionResizeMode(hdr.Interactive)
AttributeError: ‘QHeaderView’ object has no attribute ‘setSectionResizeMode’ Traceback (most recent call last):

File "/Users/chrusher/anaconda/lib/python2.7/site-packages/glue/utils/misc.py", line 58, in result
  return func(*args, **kwargs)
File "/Users/chrusher/anaconda/lib/python2.7/site-packages/glue/app/qt/layer_tree_widget.py", line 120, in _do_action
  self.app.choose_new_data_viewer(data)
File "/Users/chrusher/anaconda/lib/python2.7/site-packages/glue/app/qt/application.py", line 754, in choose_new_data_viewer
  return self.do(cmd)
File "/Users/chrusher/anaconda/lib/python2.7/site-packages/glue/core/application_base.py", line 218, in do
  self._cmds.do(command)
File "/Users/chrusher/anaconda/lib/python2.7/site-packages/glue/core/command.py", line 126, in do
  result = cmd.do(self._session)
File "/Users/chrusher/anaconda/lib/python2.7/site-packages/glue/core/command.py", line 216, in do
  v = session.application.new_data_viewer(self.viewer, self.data)
File "/Users/chrusher/anaconda/lib/python2.7/site-packages/glue/utils/matplotlib.py", line 158, in wrapper
  result = func(*args, **kwargs)
File "/Users/chrusher/anaconda/lib/python2.7/site-packages/glue/core/application_base.py", line 82, in new_data_viewer
  c = viewer_class(self._session)
File "/Users/chrusher/anaconda/lib/python2.7/site-packages/glue/viewers/common/qt/data_viewer.py", line 29, in __call__
  obj = type.__call__(cls, *args, **kwargs)
File "/Users/chrusher/anaconda/lib/python2.7/site-packages/glue/viewers/table/qt/data_viewer.py", line 196, in __init__
  hdr.setSectionResizeMode(hdr.Interactive)
AttributeError: ‘QHeaderView’ object has no attribute ‘setSectionResizeMode’
```

**Comment by astrofrog** [comment]
The fix is to update QtPy to 1.2 or later
