### ISSUE TITLE
Bug with unset bins in histogram viewer

### ISSUE THREAD

**Issue by astrofrog** [glue-viz/glue#1422]
Reported via glue:

```python
Traceback (most recent call last):

File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\backends\backend_qt5.py", line 313, in mouseReleaseEvent
  guiEvent=event)
File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\backend_bases.py", line 1940, in button_release_event
  self.callbacks.process(s, event)
File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\cbook.py", line 554, in process
  proxy(*args, **kwargs)
File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\cbook.py", line 416, in __call__
  return mtd(*args, **kwargs)
File "C:\ProgramData\Anaconda3\lib\site-packages\glue\viewers\common\qt\mouse_mode.py", line 234, in release
  self._finish_roi(event)
File "C:\ProgramData\Anaconda3\lib\site-packages\glue\viewers\common\qt\mouse_mode.py", line 186, in _finish_roi
  self._roi_callback(self)
File "C:\ProgramData\Anaconda3\lib\site-packages\glue\viewers\common\qt\mouse_mode.py", line 161, in apply_mode
  self.viewer.apply_roi(self.roi())
File "C:\ProgramData\Anaconda3\lib\site-packages\glue\utils\qt\decorators.py", line 24, in result
  return func(*args, **kwargs)
File "C:\ProgramData\Anaconda3\lib\site-packages\glue\core\application_base.py", line 385, in apply_roi
  self._session.command_stack.do(cmd)
File "C:\ProgramData\Anaconda3\lib\site-packages\glue\core\command.py", line 126, in do
  result = cmd.do(self._session)
File "C:\ProgramData\Anaconda3\lib\site-packages\glue\core\command.py", line 261, in do
  self.client.apply_roi(self.roi)
File "C:\ProgramData\Anaconda3\lib\site-packages\glue\viewers\histogram\client.py", line 427, in apply_roi
  if lo >= bins.min():
AttributeError: ‘NoneType’ object has no attribute ‘min’ Traceback (most recent call last):
```

**Comment by astrofrog** [comment]
This was an old version of glue (as evidenced by the ``client.py`` in the histogram viewer)
