### ISSUE TITLE
Issue when creating subsets after closing table viewer

### ISSUE THREAD

**Issue by astrofrog** [glue-viz/glue#1465]
```
Traceback (most recent call last):
  File "/Users/tom/miniconda3/envs/stable-glue/lib/python3.6/site-packages/matplotlib/cbook/__init__.py", line 389, in process
    proxy(*args, **kwargs)
  File "/Users/tom/miniconda3/envs/stable-glue/lib/python3.6/site-packages/matplotlib/cbook/__init__.py", line 227, in __call__
    return mtd(*args, **kwargs)
  File "/Users/tom/miniconda3/envs/stable-glue/lib/python3.6/site-packages/glue/viewers/common/qt/mouse_mode.py", line 239, in release
    self._finish_roi(event)
  File "/Users/tom/miniconda3/envs/stable-glue/lib/python3.6/site-packages/glue/viewers/common/qt/mouse_mode.py", line 189, in _finish_roi
    self._roi_callback(self)
  File "/Users/tom/miniconda3/envs/stable-glue/lib/python3.6/site-packages/glue/viewers/common/qt/mouse_mode.py", line 160, in apply_mode
    self.viewer.apply_roi(self.roi())
  File "/Users/tom/miniconda3/envs/stable-glue/lib/python3.6/site-packages/glue/utils/matplotlib.py", line 158, in wrapper
    result = func(*args, **kwargs)
  File "/Users/tom/miniconda3/envs/stable-glue/lib/python3.6/site-packages/glue/viewers/matplotlib/qt/data_viewer.py", line 125, in apply_roi
    self._session.command_stack.do(cmd)
  File "/Users/tom/miniconda3/envs/stable-glue/lib/python3.6/site-packages/glue/core/command.py", line 127, in do
    result = cmd.do(self._session)
  File "/Users/tom/miniconda3/envs/stable-glue/lib/python3.6/site-packages/glue/core/command.py", line 300, in do
    mode.update(self.data_collection, self.subset_state)
  File "/Users/tom/miniconda3/envs/stable-glue/lib/python3.6/site-packages/glue/core/edit_subset_mode.py", line 71, in update
    self._combine_data(new_state)
  File "/Users/tom/miniconda3/envs/stable-glue/lib/python3.6/site-packages/glue/core/edit_subset_mode.py", line 45, in _combine_data
    self.edit_subset = self.data_collection.new_subset_group()
  File "/Users/tom/miniconda3/envs/stable-glue/lib/python3.6/site-packages/glue/core/data_collection.py", line 216, in new_subset_group
    result.register(self)
  File "/Users/tom/miniconda3/envs/stable-glue/lib/python3.6/site-packages/glue/core/subset_group.py", line 133, in register
    d.add_subset(s)
  File "/Users/tom/miniconda3/envs/stable-glue/lib/python3.6/site-packages/glue/core/data.py", line 677, in add_subset
    self.hub.broadcast(msg)
  File "/Users/tom/miniconda3/envs/stable-glue/lib/python3.6/site-packages/glue/core/hub.py", line 207, in broadcast
    handler(message)
  File "/Users/tom/miniconda3/envs/stable-glue/lib/python3.6/site-packages/glue/viewers/table/qt/data_viewer.py", line 265, in _refresh
    self._sync_layers()
  File "/Users/tom/miniconda3/envs/stable-glue/lib/python3.6/site-packages/glue/viewers/table/qt/data_viewer.py", line 279, in _sync_layers
    self._layer_artist_container.append(TableLayerArtist(subset, self))
  File "/Users/tom/miniconda3/envs/stable-glue/lib/python3.6/site-packages/glue/core/qt/layer_artist_model.py", line 388, in append
    self._notify()
  File "/Users/tom/miniconda3/envs/stable-glue/lib/python3.6/site-packages/glue/core/layer_artist.py", line 388, in _notify
    cb()
  File "/Users/tom/miniconda3/envs/stable-glue/lib/python3.6/site-packages/glue/viewers/common/qt/data_viewer.py", line 315, in update_window_title
    self.setWindowTitle(self.window_title)
RuntimeError: wrapped C/C++ object of type TableViewer has been deleted
```

**Comment by astrofrog** [comment]
I think this has been fixed in the mean time when cleaning up all the circular references to viewers.
