### ISSUE TITLE
Bugs + Feature Requests 

### ISSUE THREAD

**Issue by catherinezucker** [glue-viz/glue#1477]
- For the WWT viewer, don't make gray the default color
- Add the GLIMPSE-Spitzer layer to the WWT viewer 
- Implement the option to do discrete color maps, so we can color by class
- Can't get to bottom of window in display mode (*bonus feature*, ignore for now)
- Changing the shape of markers (i.e. going from circle to star)  in 2D/3D scatter plot does not work
- When you save a .glu session more than once, have the second save remember the name you called the file last
- Do scaling of vectors *to scale.* If you are showing length of vectors in the units of a plot (i.e. length of filament in degrees on the l,b plane of the sky) include an option to scale to plot axes

Also, the WWT Viewer is broken in the latest developer version. I get the following error whenever I drag over a catalog. 

Traceback (most recent call last):
  File "/anaconda/lib/python3.6/site-packages/glue/app/qt/mdi_area.py", line 61, in dropEvent
    new_layer(layer)
  File "/anaconda/lib/python3.6/site-packages/glue/app/qt/mdi_area.py", line 51, in new_layer
    self._application.choose_new_data_viewer(layer)
  File "/anaconda/lib/python3.6/site-packages/glue/app/qt/application.py", line 841, in choose_new_data_viewer
    return self.do(cmd)
  File "/anaconda/lib/python3.6/site-packages/glue/core/application_base.py", line 218, in do
    return self._cmds.do(command)
  File "/anaconda/lib/python3.6/site-packages/glue/core/command.py", line 127, in do
    result = cmd.do(self._session)
  File "/anaconda/lib/python3.6/site-packages/glue/core/command.py", line 217, in do
    v = session.application.new_data_viewer(self.viewer, self.data)
  File "/anaconda/lib/python3.6/site-packages/glue/utils/matplotlib.py", line 158, in wrapper
    result = func(*args, **kwargs)
  File "/anaconda/lib/python3.6/site-packages/glue/core/application_base.py", line 85, in new_data_viewer
    if data and not c.add_data(data):
  File "/anaconda/lib/python3.6/site-packages/glue_wwt/viewer/data_viewer.py", line 68, in add_data
    self._add_layer(data, center)
  File "/anaconda/lib/python3.6/site-packages/glue_wwt/viewer/data_viewer.py", line 82, in _add_layer
    artist = WWTLayer(self._wwt_widget, self.state, layer=layer)
  File "/anaconda/lib/python3.6/site-packages/glue_wwt/viewer/layer_artist.py", line 37, in __init__
    layer=self.layer)
  File "/anaconda/lib/python3.6/site-packages/glue_wwt/viewer/state.py", line 81, in __init__
    visible=False)
TypeError: __init__() got an unexpected keyword argument 'visible'

Here is my version info:
Glue: 0.13.0.dev04101
Python: 3.6.3
PyQt4: Not installed
PyQt5: PyQt: 5.6 - Qt: 5.6.2
PySide: Not installed
qtpy: 1.3.1
setuptools: 36.5.0.post20170921
numpy: 1.13.3
matplotlib: 2.0.2
pandas: 0.21.0
astropy: 2.0.2
dill: 0.2.7.1
h5py: 2.7.0
xlrd: 1.1.0
mpl-scatter-density: 0.3
glue-core: 0.13.0.dev04101
glue-vispy-viewers: 0.9
glue-wwt: unknown version
IPython: 6.1.0
qtconsole: 4.3.1
ipykernel: 4.6.1
traitlets: 4.3.2
pygments: 2.2.0
pyzmq: 16.0.2
scipy: 1.0.0
scikit-image: 0.13.0
PyAVM: 0.9.2
spectral-cube: 0.4.0
astrodendro: 0.2.0
mock: 2.0.0
pytest: 3.2.1
plotly: 2.1.0

**Comment by catherinezucker** [comment]
More features/bugs?
- Be able to color code or size the scatter points in the WWT viewer by a third attribute

**Comment by catherinezucker** [comment]
When you zoom in on 2D scatter plot, points become *tiny* and you can barely see them, even though they are huge in the "full galaxy" view

**Comment by astrofrog** [comment]
@catherinezucker - could you open issues in the https://github.com/glue-viz/glue-wwt repository for each of the WWT requests/issues above? (it will make it easier to track). Thanks!
