### ISSUE TITLE
Error when creating a derived component when links are defined

### ISSUE THREAD

**Issue by astrofrog** [glue-viz/glue#1532]
There is a bug in the new component manager which occurs if a data object has derived components set up for links and components are reordered or a new component is added:

```
Traceback (most recent call last):
  File "/Users/tom/Dropbox/Code/Glue/glue/glue/dialogs/component_manager/qt/component_manager.py", line 349, in accept
    data.reorder_components(cids_all)
  File "/Users/tom/Dropbox/Code/Glue/glue/glue/core/data.py", line 891, in reorder_components
    raise ValueError("Number of component in component_ids does not "
ValueError: Number of component in component_ids does not match existing number of components
```

This is because the component manager ignores derived components related to links while ``reorder_components`` doesn't.

**Comment by astrofrog** [comment]
This has been fixed and the component manager tests have been modified here to make sure they always work with links present:

https://github.com/glue-viz/glue/blob/master/glue/dialogs/component_manager/qt/tests/test_component_manager.py#L111
