### ISSUE TITLE
matplotlib-2.2.0 breaks compatibility

### ISSUE THREAD

**Issue by drdavella** [glue-viz/glue#1565]
I have tried this on both Linux and OSX: when upgrading to `matplotlib-2.2.0`, `glue` seems to be unable to draw in mpl-based viewers. Here's the traceback I get:

```
Traceback (most recent call last):
  File "/Users/ddavella/glue/glue/viewers/matplotlib/qt/widget.py", line 76, in paintEvent
    drawRect = self._drawRect
AttributeError: 'MplCanvas' object has no attribute '_drawRect'
Traceback (most recent call last):
  File "/Users/ddavella/glue/glue/viewers/matplotlib/qt/widget.py", line 72, in paintEvent
    drawRect = self.drawRect
AttributeError: 'MplCanvas' object has no attribute 'drawRect'
```

**Comment by astrofrog** [comment]
Thanks for the report! I'll try and fix this today.
