### ISSUE TITLE
matplotlib 3.0.0 ModestImage imshow issue

### ISSUE THREAD

**Issue by ngoldbaum** [glue-viz/glue#1848]
When running the maptlotlib 3.0.0 release candidate, I get the following error when trying to make a 2D image:

```python traceback
Traceback (most recent call last):
  File "/Users/goldbaum/Documents/glue/glue/app/qt/mdi_area.py", line 65, in dropEvent
    new_layer(layer)
  File "/Users/goldbaum/Documents/glue/glue/app/qt/mdi_area.py", line 56, in new_layer
    application.choose_new_data_viewer(layer)
  File "/Users/goldbaum/Documents/glue/glue/app/qt/application.py", line 995, in choose_new_data_viewer
    return self.do(cmd)
  File "/Users/goldbaum/Documents/glue/glue/core/application_base.py", line 265, in do
    return self._cmds.do(command)
  File "/Users/goldbaum/Documents/glue/glue/core/command.py", line 126, in do
    result = cmd.do(self._session)
  File "/Users/goldbaum/Documents/glue/glue/core/command.py", line 216, in do
    viewer = session.application.new_data_viewer(self.viewer, self.data)
  File "/Users/goldbaum/Documents/glue/glue/utils/matplotlib.py", line 161, in wrapper
    result = func(*args, **kwargs)
  File "/Users/goldbaum/Documents/glue/glue/core/application_base.py", line 81, in new_data_viewer
    c = viewer_class(self._session)
  File "/Users/goldbaum/Documents/glue/glue/viewers/common/qt/data_viewer.py", line 29, in __call__
    obj = type.__call__(cls, *args, **kwargs)
  File "/Users/goldbaum/Documents/glue/glue/utils/matplotlib.py", line 157, in wrapper
    return func(*args, **kwargs)
  File "/Users/goldbaum/Documents/glue/glue/viewers/image/qt/data_viewer.py", line 48, in __init__
    MatplotlibImageMixin.setup_callbacks(self)
  File "/Users/goldbaum/Documents/glue/glue/viewers/image/viewer.py", line 51, in setup_callbacks
    origin='lower', interpolation='nearest')
  File "/Users/goldbaum/Documents/glue/glue/external/modest_image.py", line 226, in imshow
    if not axes._hold:
AttributeError: 'WCSAxesSubplot' object has no attribute '_hold'
```

This is due to the removal of the `hold` machinery in matplotlib, which has been deprecated since matplotlib 2.1. See https://matplotlib.org/devdocs/api/api_changes.html#hold-machinery-removed

**Comment by astrofrog** [comment]
Fixed in #1875
