### ISSUE TITLE
glue crashes before opening with failed to parse sys.version

### ISSUE THREAD

**Issue by johnarban** [glue-viz/glue#1908]
I have tried putting glue in it's own conda environment and installing via astroconda. From what I can tell online, this seems to be an issue with the `platform` module. The odd thing is that I don't get these errors when importing `pandas` by itself. 
```
> glue
Traceback (most recent call last):
  File "/Users/johnlewis/anaconda3/bin/glue", line 7, in <module>
    from glue.main import main
  File "/Users/johnlewis/anaconda3/lib/python3.6/site-packages/glue/__init__.py", line 127, in <module>
    from .qglue import qglue
  File "/Users/johnlewis/anaconda3/lib/python3.6/site-packages/glue/qglue.py", line 20, in <module>
    from glue.core import Data
  File "/Users/johnlewis/anaconda3/lib/python3.6/site-packages/glue/core/__init__.py", line 3, in <module>
    from .client import Client  # noqa
  File "/Users/johnlewis/anaconda3/lib/python3.6/site-packages/glue/core/client.py", line 9, in <module>
    from glue.core.data_collection import DataCollection
  File "/Users/johnlewis/anaconda3/lib/python3.6/site-packages/glue/core/data_collection.py", line 5, in <module>
    from glue.core.util import disambiguate
  File "/Users/johnlewis/anaconda3/lib/python3.6/site-packages/glue/core/util.py", line 9, in <module>
    import pandas as pd
  File "/Users/johnlewis/anaconda3/lib/python3.6/site-packages/pandas/__init__.py", line 23, in <module>
    from pandas.compat.numpy import *
  File "/Users/johnlewis/anaconda3/lib/python3.6/site-packages/pandas/compat/__init__.py", line 47, in <module>
    PYPY = platform.python_implementation() == 'PyPy'
  File "/Users/johnlewis/anaconda3/lib/python3.6/platform.py", line 1265, in python_implementation
    return _sys_version()[0]
  File "/Users/johnlewis/anaconda3/lib/python3.6/platform.py", line 1223, in _sys_version
    repr(sys_version))
ValueError: failed to parse CPython sys.version: '3.6.6 |Anaconda, Inc.| (default, Jun 28 2018, 11:07:29) \n[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]'
```

**Comment by johnarban** [comment]
After a reinstall of anaconda glue works again! I noticed an output when running `conda info -a` (and didn't think to copy it) but it said that `sys.version` had been configured by `conda-forge`. Now in the working version it has `sys.version: 3.7.1 (default, Dec 14 2018, 13:28:58)` (where it now says "default...", when it was broken is returned "conda-forge..."). This makes me believe the issue is with conda-forge not glue.

**Comment by astrofrog** [comment]
@johnarban - ok thanks!
