### ISSUE TITLE
Can't open demo data file  w5_psc.vot

### ISSUE THREAD

**Issue by aaronoppenheimer** [glue-viz/glue#1910]
The "getting started" guide advises opening w5_psc.vot from the demo data zip file. When I try to open I see a failure, with this message:

```
Error message: Cannot convert fill_value nan to dtype int32

Traceback (most recent call last):
  File "C:\Users\Aaron.Oppenheimer\AppData\Local\Continuum\anaconda2\envs\glueviz\lib\site-packages\numpy\ma\core.py", line 479, in _check_fill_value
    fill_value = np.array(fill_value, copy=False, dtype=ndtype)
ValueError: cannot convert float NaN to integer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Aaron.Oppenheimer\AppData\Local\Continuum\anaconda2\envs\glueviz\lib\site-packages\glue\dialogs\data_wizard\qt\data_wizard_dialog.py", line 36, in data_wizard
    result = gdd.load_data()
  File "C:\Users\Aaron.Oppenheimer\AppData\Local\Continuum\anaconda2\envs\glueviz\lib\site-packages\glue\dialogs\data_wizard\qt\data_wizard_dialog.py", line 119, in load_data
    d = load_data(path, factory=fac.function)
  File "C:\Users\Aaron.Oppenheimer\AppData\Local\Continuum\anaconda2\envs\glueviz\lib\site-packages\glue\core\data_factories\helpers.py", line 251, in load_data
    d = as_list(factory(path, **kwargs))
  File "C:\Users\Aaron.Oppenheimer\AppData\Local\Continuum\anaconda2\envs\glueviz\lib\site-packages\glue\core\data_factories\astropy_table.py", line 93, in astropy_tabular_data_votable
    return astropy_tabular_data(*args, **kwargs)
  File "C:\Users\Aaron.Oppenheimer\AppData\Local\Continuum\anaconda2\envs\glueviz\lib\site-packages\glue\core\data_factories\astropy_table.py", line 78, in astropy_tabular_data
    c = c.filled(fill_value=np.nan)
  File "C:\Users\Aaron.Oppenheimer\AppData\Local\Continuum\anaconda2\envs\glueviz\lib\site-packages\astropy\table\column.py", line 1265, in filled
    data = super().filled(fill_value)
  File "C:\Users\Aaron.Oppenheimer\AppData\Local\Continuum\anaconda2\envs\glueviz\lib\site-packages\numpy\ma\core.py", line 3712, in filled
    fill_value = _check_fill_value(fill_value, self.dtype)
  File "C:\Users\Aaron.Oppenheimer\AppData\Local\Continuum\anaconda2\envs\glueviz\lib\site-packages\numpy\ma\core.py", line 485, in _check_fill_value
    raise TypeError(err_msg % (fill_value, ndtype))
TypeError: Cannot convert fill_value nan to dtype int32
```

I installed GlueViz through Anaconda, here's my environment:
```
# Name                    Version                   Build  Channel
asn1crypto                0.24.0                   py37_0
astropy                   3.1              py37he774522_0
atomicwrites              1.2.1                    py37_0
attrs                     18.2.0           py37h28b3542_0
backcall                  0.1.0                    py37_0
blas                      1.0                         mkl
bokeh                     1.0.2                    py37_0
bottleneck                1.2.1            py37h452e1ab_1
ca-certificates           2018.03.07                    0
certifi                   2018.11.29               py37_0
cffi                      1.11.5           py37h74b6da3_1
chardet                   3.0.4                    py37_1
click                     7.0                      py37_0
cloudpickle               0.6.1                    py37_0
colorama                  0.4.1                    py37_0
cryptography              2.4.2            py37h7a1dbc1_0
cycler                    0.10.0                   py37_0
cytoolz                   0.9.0.1          py37hfa6e2cd_1
dask                      1.0.0                    py37_0
dask-core                 1.0.0                    py37_0
decorator                 4.3.0                    py37_0
dill                      0.2.8.2                  py37_0
distributed               1.25.1                   py37_0
fast-histogram            0.5              py37h452e1ab_1
freetype                  2.9.1                ha9979f8_1
glue-core                 0.14.1                   py37_0
glue-vispy-viewers        0.10                     py37_0
glueviz                   0.13.3                        0
h5py                      2.8.0            py37h3bdd7fb_2
hdf5                      1.10.2               hac2f561_1
heapdict                  1.0.0                    py37_2
icc_rt                    2019.0.0             h0cc432a_1
icu                       58.2                 ha66f8fd_1
idna                      2.8                      py37_0
imageio                   2.4.1                    py37_0
intel-openmp              2019.1                      144
ipykernel                 5.1.0            py37h39e3cac_0
ipython                   7.2.0            py37h39e3cac_0
ipython_genutils          0.2.0                    py37_0
jedi                      0.13.2                   py37_0
jinja2                    2.10                     py37_0
jpeg                      9b                   hb83a4c4_2
jsonschema                2.6.0                    py37_0
jupyter_client            5.2.4                    py37_0
jupyter_core              4.4.0                    py37_0
kiwisolver                1.0.1            py37h6538335_0
libpng                    1.6.35               h2a8f88b_0
libsodium                 1.0.16               h9d3ae62_0
libtiff                   4.0.9                h36446d0_2
locket                    0.2.0                    py37_1
markupsafe                1.1.0            py37he774522_0
matplotlib                3.0.2            py37hc8f65d3_0
mkl                       2019.1                      144
mkl_fft                   1.0.6            py37h6288b17_0
mkl_random                1.0.2            py37h343c172_0
more-itertools            4.3.0                    py37_0
mpl-scatter-density       0.4                      py37_0
msgpack-python            0.5.6            py37he980bc4_1
nbformat                  4.4.0                    py37_0
networkx                  2.2                      py37_1
numpy                     1.15.4           py37h19fb1c0_0
numpy-base                1.15.4           py37hc3f5095_0
olefile                   0.46                     py37_0
openssl                   1.1.1a               he774522_0
packaging                 18.0                     py37_0
pandas                    0.23.4           py37h830ac7b_0
parso                     0.3.1                    py37_0
partd                     0.3.9                    py37_0
pickleshare               0.7.5                    py37_0
pillow                    5.3.0            py37hdc69c19_0
pip                       18.1                     py37_0
plotly                    3.4.2            py37h28b3542_0
pluggy                    0.8.0                    py37_0
prompt_toolkit            2.0.7                    py37_0
psutil                    5.4.8            py37he774522_0
py                        1.7.0                    py37_0
pycparser                 2.19                     py37_0
pygments                  2.3.1                    py37_0
pyopengl                  3.1.1a1                  py37_0
pyopenssl                 18.0.0                   py37_0
pyparsing                 2.3.0                    py37_0
pyqt                      5.9.2            py37h6538335_2
pyreadline                2.1                      py37_1
pysocks                   1.6.8                    py37_0
pytest                    4.0.2                    py37_0
pytest-arraydiff          0.3              py37h39e3cac_0
pytest-astropy            0.5.0                    py37_0
pytest-doctestplus        0.2.0                    py37_0
pytest-openfiles          0.3.1                    py37_0
pytest-remotedata         0.3.1                    py37_0
python                    3.7.1                h8c8aaf0_6
python-dateutil           2.7.5                    py37_0
pytz                      2018.7                   py37_0
pywavelets                1.0.1            py37h8c2d366_0
pyyaml                    3.13             py37hfa6e2cd_0
pyzmq                     17.1.2           py37hfa6e2cd_0
qt                        5.9.7            vc14h73c81de_0
qtconsole                 4.4.3                    py37_0
qtpy                      1.5.2                    py37_0
requests                  2.21.0                   py37_0
retrying                  1.3.3                    py37_2
scikit-image              0.14.1           py37ha925a31_0
scipy                     1.1.0            py37h29ff71c_2
setuptools                40.6.3                   py37_0
sip                       4.19.8           py37h6538335_0
six                       1.12.0                   py37_0
sortedcontainers          2.1.0                    py37_0
sqlite                    3.26.0               he774522_0
tblib                     1.3.2                    py37_0
tk                        8.6.8                hfa6e2cd_0
toolz                     0.9.0                    py37_0
tornado                   5.1.1            py37hfa6e2cd_0
traitlets                 4.3.2                    py37_0
urllib3                   1.24.1                   py37_0
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.15.26706          h3a45250_0
wcwidth                   0.1.7                    py37_0
wheel                     0.32.3                   py37_0
win_inet_pton             1.0.1                    py37_1
wincertstore              0.2                      py37_0
xlrd                      1.2.0                    py37_0
yaml                      0.1.7                hc54c509_2
zeromq                    4.2.5                he025d50_1
zict                      0.1.3                    py37_0
zlib                      1.2.11               h62dcd97_3
```

**Comment by astrofrog** [comment]
Thanks for the bug report! I'll investigate.

**Comment by astrofrog** [comment]
I've got a fix in https://github.com/glue-viz/glue/pull/1911 and will try and release 0.14.2 shortly with the fix. In the mean time, try using the CSV file from here instead:

https://github.com/glue-viz/glue-example-data/tree/master/Astronomy/W5
