### ISSUE TITLE
date data cannot be displayed by scatter

### ISSUE THREAD

**Issue by aaronoppenheimer** [glue-viz/glue#1912]
New to Glue here. If I create an excel sheet with two numeric columns and one date column, I can import everything, and the dtype of the date column is properly datetime64. When I drag the data into the viewer, I can see it in a table view. When I request a scatter view, though, to see the numbers over time, I get a popup with this message:
```
Failed to add data
Unknown data kind
```
The "Show Details..." is below. If I change the format of the date cells in the excel file to "number" it imports and displays properly as numbers.

From previous issues, it seems like this used to work. Even if the scatter viewer can't manage dates, there's no way to look at the other two columns - maybe that's a different issue.

```
Traceback (most recent call last):
  File "C:\Users\ao\AppData\Local\Continuum\anaconda2\envs\glueviz\lib\site-packages\glue\utils\qt\decorators.py", line 63, in decorated
    return f(*args, **kwargs)
  File "C:\Users\ao\AppData\Local\Continuum\anaconda2\envs\glueviz\lib\site-packages\glue\viewers\common\qt\data_viewer.py", line 235, in add_data
    return super(DataViewer, self).add_data(data)
  File "C:\Users\ao\AppData\Local\Continuum\anaconda2\envs\glueviz\lib\site-packages\glue\viewers\common\viewer.py", line 200, in add_data
    layer = get_layer_artist_from_registry(data, self) or self.get_data_layer_artist(data)
  File "C:\Users\ao\AppData\Local\Continuum\anaconda2\envs\glueviz\lib\site-packages\glue\utils\matplotlib.py", line 157, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\ao\AppData\Local\Continuum\anaconda2\envs\glueviz\lib\site-packages\glue\utils\matplotlib.py", line 157, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\ao\AppData\Local\Continuum\anaconda2\envs\glueviz\lib\site-packages\glue\viewers\common\viewer.py", line 225, in get_data_layer_artist
    return self.get_layer_artist(self._data_artist_cls, layer=layer, layer_state=layer_state)
  File "C:\Users\ao\AppData\Local\Continuum\anaconda2\envs\glueviz\lib\site-packages\glue\utils\matplotlib.py", line 157, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\ao\AppData\Local\Continuum\anaconda2\envs\glueviz\lib\site-packages\glue\utils\matplotlib.py", line 157, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\ao\AppData\Local\Continuum\anaconda2\envs\glueviz\lib\site-packages\glue\viewers\matplotlib\viewer.py", line 213, in get_layer_artist
    return cls(self.axes, self.state, layer=layer, layer_state=layer_state)
  File "C:\Users\ao\AppData\Local\Continuum\anaconda2\envs\glueviz\lib\site-packages\glue\viewers\scatter\layer_artist.py", line 143, in __init__
    layer_state=layer_state, layer=layer)
  File "C:\Users\ao\AppData\Local\Continuum\anaconda2\envs\glueviz\lib\site-packages\glue\viewers\matplotlib\layer_artist.py", line 19, in __init__
    layer=layer)
  File "C:\Users\ao\AppData\Local\Continuum\anaconda2\envs\glueviz\lib\site-packages\glue\viewers\common\layer_artist.py", line 26, in __init__
    layer=self.layer)
  File "C:\Users\ao\AppData\Local\Continuum\anaconda2\envs\glueviz\lib\site-packages\glue\viewers\scatter\state.py", line 297, in __init__
    self._on_layer_change()
  File "C:\Users\ao\AppData\Local\Continuum\anaconda2\envs\glueviz\lib\site-packages\glue\viewers\scatter\state.py", line 317, in _on_layer_change
    self.cmap_att_helper.set_multiple_data([self.layer])
  File "C:\Users\ao\AppData\Local\Continuum\anaconda2\envs\glueviz\lib\site-packages\glue\core\data_combo_helper.py", line 318, in set_multiple_data
    self.refresh()
  File "C:\Users\ao\AppData\Local\Continuum\anaconda2\envs\glueviz\lib\site-packages\glue\core\data_combo_helper.py", line 349, in refresh
    if ((data.get_kind(cid) in ('numerical', 'datetime') and self.numeric) or
  File "C:\Users\ao\AppData\Local\Continuum\anaconda2\envs\glueviz\lib\site-packages\glue\core\data.py", line 1204, in get_kind
    raise TypeError("Unknown data kind")
TypeError: Unknown data kind
```
version info:
```
Glue: 0.14.1
Python: 3.7.1
PyQt5: PyQt: 5.9.2 - Qt: 5.9.6
PySide2: Not installed
qtpy: 1.5.2
setuptools: 40.6.3
numpy: 1.15.4
bottleneck: 1.2.1
matplotlib: 3.0.2
pandas: 0.23.4
astropy: 3.1
dill: 0.2.8.2
h5py: 2.8.0
xlrd: 1.2.0
mpl-scatter-density: 0.4
glue-core: 0.14.1
glue-vispy-viewers: 0.10
IPython: 7.2.0
qtconsole: 4.4.3
ipykernel: 5.1.0
traitlets: 4.3.2
pygments: 2.3.1
pyzmq: 17.1.2
scipy: 1.1.0
scikit-image: 0.14.1
PyAVM: Not installed
spectral-cube: Not installed
astrodendro: Not installed
mock: Not installed
pytest: 4.0.2
plotly: 3.4.2
```

**Comment by astrofrog** [comment]
@aaronoppenheimer - can you share an example of an excel spreadsheet that fails? (either as a link here, or by email to thomas.robitaille@gmail.com)

**Comment by aaronoppenheimer** [comment]
sent via email.
