### ISSUE TITLE
can't display subset as table view

### ISSUE THREAD

**Issue by aaronoppenheimer** [glue-viz/glue#1914]
I have a set of data that can be viewed in a table, scatter, etc. I create a subset which works properly with scatter and is highlighted properly in the table view.

If I drag the subset from the data collection window into the viewer area, I can select to view it as scatter plot and it works fine. If I select 'table view' though, I get a popup:
```
Failed to add subset
'NoneType' object has no attribute 'data_changed'
```
show details says...
```
Traceback (most recent call last):
  File "C:\Users\Aaron.Oppenheimer\AppData\Local\Continuum\anaconda2\envs\glueviz\lib\site-packages\glue\utils\qt\decorators.py", line 63, in decorated
    return f(*args, **kwargs)
  File "C:\Users\Aaron.Oppenheimer\AppData\Local\Continuum\anaconda2\envs\glueviz\lib\site-packages\glue\viewers\common\qt\data_viewer.py", line 239, in add_subset
    return super(DataViewer, self).add_subset(subset)
  File "C:\Users\Aaron.Oppenheimer\AppData\Local\Continuum\anaconda2\envs\glueviz\lib\site-packages\glue\viewers\common\viewer.py", line 247, in add_subset
    layer.update()
  File "C:\Users\Aaron.Oppenheimer\AppData\Local\Continuum\anaconda2\envs\glueviz\lib\site-packages\glue\viewers\table\qt\data_viewer.py", line 137, in update
    self._refresh()
  File "C:\Users\Aaron.Oppenheimer\AppData\Local\Continuum\anaconda2\envs\glueviz\lib\site-packages\glue\viewers\table\qt\data_viewer.py", line 131, in _refresh
    self._table_viewer.model.data_changed()
AttributeError: 'NoneType' object has no attribute 'data_changed'
```

version info:
```
Glue: 0.14.1
Python: 3.7.1
PyQt5: PyQt: 5.9.2 - Qt: 5.9.6
PySide2: Not installed
qtpy: 1.5.2
setuptools: 40.6.3
numpy: 1.15.4
bottleneck: 1.2.1
matplotlib: 3.0.2
pandas: 0.23.4
astropy: 3.1
dill: 0.2.8.2
h5py: 2.8.0
xlrd: 1.2.0
mpl-scatter-density: 0.4
glue-core: 0.14.1
glue-vispy-viewers: 0.10
IPython: 7.2.0
qtconsole: 4.4.3
ipykernel: 5.1.0
traitlets: 4.3.2
pygments: 2.3.1
pyzmq: 17.1.2
scipy: 1.1.0
scikit-image: 0.14.1
PyAVM: Not installed
spectral-cube: Not installed
astrodendro: Not installed
mock: Not installed
pytest: 4.0.2
plotly: 3.4.2
```

**Comment by aaronoppenheimer** [comment]
Actually, I've now found that if I right-click the subset in the 'data collection' list and pick 'create new viewer' I can (sometimes) get a table view - but even when it opens a table, it displays the entire dataset instead of just the subset.

**Comment by astrofrog** [comment]
@aaronoppenheimer - thanks for the report - indeed at the moment the full dataset is always shown in the table viewer, but I agree it would be good to make it possible to view just a subset.
