### ISSUE TITLE
Error when trying to make table viewer out of table subset data

### ISSUE THREAD

**Issue by catherinezucker** [glue-viz/glue#1930]
When I drag over a subset of a catalog and try to make a new table viewer I get this error:

Traceback (most recent call last):
  File "/anaconda3/envs/glueviz-dev/lib/python3.6/site-packages/glue/utils/qt/decorators.py", line 63, in decorated
    return f(*args, **kwargs)
  File "/anaconda3/envs/glueviz-dev/lib/python3.6/site-packages/glue/viewers/common/qt/data_viewer.py", line 239, in add_subset
    return super(DataViewer, self).add_subset(subset)
  File "/anaconda3/envs/glueviz-dev/lib/python3.6/site-packages/glue/viewers/common/viewer.py", line 247, in add_subset
    layer.update()
  File "/anaconda3/envs/glueviz-dev/lib/python3.6/site-packages/glue/viewers/table/qt/data_viewer.py", line 137, in update
    self._refresh()
  File "/anaconda3/envs/glueviz-dev/lib/python3.6/site-packages/glue/viewers/table/qt/data_viewer.py", line 131, in _refresh
    self._table_viewer.model.data_changed()
AttributeError: 'NoneType' object has no attribute 'data_changed'

**Comment by catherinezucker** [comment]
Ah, I see this has already been opened before, sorry!
