### ISSUE TITLE
AttributeError: type object 'Qt' has no attribute 'AA_UseHighDpiPixmaps'

### ISSUE THREAD

**Issue by cphyc** [glue-viz/glue#1960]
Hey,
I have tried installing glue on a cluster I have access to using the conda package. However, when I try to launch it, I get the following error
```
/home/cadiou/miniconda3/envs/py3/lib/python3.6/site-packages/qtpy/__init__.py:211: RuntimeWarning: Selected binding "pyqt5" could not be found, using "pyqt"
  'using "{}"'.format(initial_api, API), RuntimeWarning)
Traceback (most recent call last):
  File "/home/cadiou/miniconda3/envs/py3/bin/glue", line 11, in <module>
    sys.exit(main())
  File "/home/cadiou/miniconda3/envs/py3/lib/python3.6/site-packages/glue/main.py", line 252, in main
    start_glue(**kwargs)
  File "/home/cadiou/miniconda3/envs/py3/lib/python3.6/site-packages/glue/main.py", line 148, in start_glue
    app = get_qapp()
  File "/home/cadiou/miniconda3/envs/py3/lib/python3.6/site-packages/glue/utils/qt/app.py", line 40, in get_qapp
    qapp.setAttribute(QtCore.Qt.AA_UseHighDpiPixmaps)
AttributeError: type object 'Qt' has no attribute 'AA_UseHighDpiPixmaps'
```

I have fixed the issue by commenting out https://github.com/glue-viz/glue/blob/e71ade3cb0d509f370750ff1a36710937a558be2/glue/utils/qt/app.py#L60

System information
----
* anaconda version: 4.6.8
* python version: 3.6.7
* glue version: 0.13.0

**Comment by astrofrog** [comment]
Thanks for the report! Can you let me know the output of ‘conda list’?

**Comment by cphyc** [comment]
There you go
```# packages in environment at /home/cadiou/miniconda3/envs/py3:
#
# Name                    Version                   Build  Channel
absl-py                   0.5.0                    pypi_0    pypi
alabaster                 0.7.12                   pypi_0    pypi
aplus                     0.11.0                     py_1    conda-forge
appdirs                   1.4.3                      py_1    conda-forge
apptools                  4.4.0                 py36_1002    conda-forge
asn1crypto                0.24.0                py36_1003    conda-forge
asteval                   0.9.12                   pypi_0    pypi
astor                     0.7.1                    pypi_0    pypi
astroid                   2.1.0                    pypi_0    pypi
astropy                   3.0.4                    pypi_0    pypi
atk                       2.25.90           hb9dd440_1002    conda-forge
atomicwrites              1.2.1                    pypi_0    pypi
attrs                     18.2.0                   pypi_0    pypi
automat                   0.7.0                    pypi_0    pypi
autopep8                  1.4.3                    pypi_0    pypi
babel                     2.6.0                    pypi_0    pypi
backcall                  0.1.0                      py_0    conda-forge
blas                      1.0                         mkl  
bleach                    2.1.4                    pypi_0    pypi
blosc                     1.16.3               hf484d3e_0    conda-forge
bokeh                     0.13.0                   pypi_0    pypi
bottleneck                1.2.1           py36h3010b51_1001    conda-forge
bqplot                    0.11.1                   pypi_0    pypi
branca                    0.3.1                      py_0    conda-forge
bzip2                     1.0.6             h14c3975_1002    conda-forge
ca-certificates           2019.3.9             hecc5488_0    conda-forge
cachetools                3.1.0                      py_0    conda-forge
caesar                    0.1                       dev_0    <develop>
cairo                     1.16.0            ha4e643d_1000    conda-forge
certifi                   2018.8.13                pypi_0    pypi
cffi                      1.12.2           py36hf0e25f4_1    conda-forge
cftime                    1.0.3.4         py36h3010b51_1000    conda-forge
chardet                   3.0.4                 py36_1003    conda-forge
click                     6.7                      pypi_0    pypi
cloudpickle               0.5.6                    pypi_0    pypi
colorcet                  0.9.1                    pypi_0    pypi
colossus                  1.2.4                    pypi_0    pypi
configobj                 5.0.6                      py_0    conda-forge
constantly                15.1.0                     py_0    conda-forge
correlations              0.0.1                     dev_0    <develop>
coverage                  4.5.2                    pypi_0    pypi
cryptography              2.3.1                    pypi_0    pypi
cryptography-vectors      2.6.1                      py_0    conda-forge
curl                      7.64.0               h646f8bb_2    conda-forge
cycler                    0.10.0                   pypi_0    pypi
cython                    0.29.6           py36hf484d3e_0    conda-forge
cython-fortran-file       0.0.8                    pypi_0    pypi
cytoolz                   0.9.0.1         py36h14c3975_1001    conda-forge
dask                      0.19.2                   pypi_0    pypi
dask-core                 1.1.4                      py_0    conda-forge
datashader                0.6.6                    pypi_0    pypi
datashape                 0.5.2                    pypi_0    pypi
dbus                      1.13.0            h4e0c4b3_1000    conda-forge
decorator                 4.3.2                      py_0    conda-forge
defusedxml                0.5.0                      py_1    conda-forge
dill                      0.2.9                    py36_0    conda-forge
distributed               1.22.1                   pypi_0    pypi
docformatter              1.0                      pypi_0    pypi
docutils                  0.14                     pypi_0    pypi
elpy                      1.23.0                   pypi_0    pypi
entrypoints               0.3                   py36_1000    conda-forge
envisage                  4.7.0                    pypi_0    pypi
expat                     2.2.5             hf484d3e_1002    conda-forge
fast-histogram            0.7             py36h3010b51_1000    conda-forge
fontconfig                2.13.1            h2176d3f_1000    conda-forge
freetype                  2.9.1             h94bbf69_1005    conda-forge
future                    0.17.1                py36_1000    conda-forge
fyeldgenerator            0.1.1                     dev_0    <develop>
gdk-pixbuf                2.36.12           h49783d7_1002    conda-forge
gettext                   0.19.8.1          h9745a5d_1001    conda-forge
gitpython                 2.1.11                   pypi_0    pypi
glib                      2.58.3            hf63aee3_1001    conda-forge
glue-core                 0.13.0                   py36_0    glueviz
glue-vispy-viewers        0.10                     py36_0    glueviz
glueviz                   0.13.0                        1    glueviz
gmp                       6.1.2             hf484d3e_1000    conda-forge
gobject-introspection     1.58.2          py36h2da5eee_1000    conda-forge
graphite2                 1.3.13            hf484d3e_1000    conda-forge
grpcio                    1.14.1                   pypi_0    pypi
gst-plugins-base          1.14.4            hdf3bae2_1001    conda-forge
gstreamer                 1.14.4            h66beb1c_1001    conda-forge
gtk2                      2.24.31           hb68c50a_1001    conda-forge
h5netcdf                  0.7.0                      py_0    conda-forge
h5py                      2.9.0           nompi_py36hf008753_1102    conda-forge
harfbuzz                  2.3.1                h6824563_0    conda-forge
hdf4                      4.2.13            h9a582f1_1002    conda-forge
hdf5                      1.10.4          nompi_h11e915b_1105    conda-forge
heapdict                  1.0.0                    pypi_0    pypi
html5lib                  1.0.1                      py_0    conda-forge
httpretty                 0.9.5                    pypi_0    pypi
hyperlink                 18.0.0                   pypi_0    pypi
icu                       58.2              hf484d3e_1000    conda-forge
idna                      2.8                   py36_1000    conda-forge
imageio                   2.5.0                    py36_0    conda-forge
imagesize                 1.1.0                    pypi_0    pypi
incremental               17.5.0                     py_0    conda-forge
intel-openmp              2019.1                      144  
ipydatawidgets            4.0.0                      py_0    conda-forge
ipykernel                 5.1.0           py36h24bf2e0_1002    conda-forge
ipyleaflet                0.10.0                   py36_0    conda-forge
ipympl                    0.2.1                 py36_1001    conda-forge
ipyparallel               6.2.2                    pypi_0    pypi
ipyscales                 0.3.0                      py_0    conda-forge
ipython                   7.3.0            py36h24bf2e0_0    conda-forge
ipython-genutils          0.2.0                    pypi_0    pypi
ipython_genutils          0.2.0                      py_1    conda-forge
ipyvolume                 0.5.1                    pypi_0    pypi
ipywebrtc                 0.4.0                    pypi_0    pypi
ipywidgets                7.4.0                    pypi_0    pypi
isort                     4.3.4                    pypi_0    pypi
itk-core                  4.13.1.post1             pypi_0    pypi
itk-filtering             4.13.1.post1             pypi_0    pypi
itk-io                    4.13.1.post1             pypi_0    pypi
itk-numerics              4.13.1.post1             pypi_0    pypi
itk-registration          4.13.1.post1             pypi_0    pypi
itk-segmentation          4.13.1.post1             pypi_0    pypi
jedi                      0.12.1                   pypi_0    pypi
jinja2                    2.10                       py_1    conda-forge
joblib                    0.13.0                   pypi_0    pypi
jpeg                      9c                h14c3975_1001    conda-forge
jsoncpp                   1.8.4             h6bb024c_1001    conda-forge
jsonschema                3.0.1                    py36_0    conda-forge
jupyter                   1.0.0                      py_1    conda-forge
jupyter-sphinx            0.1.4                    pypi_0    pypi
jupyter_client            5.2.4                      py_3    conda-forge
jupyter_console           6.0.0                      py_0    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
jupyterlab                0.34.0                   pypi_0    pypi
jupyterlab-launcher       0.13.1                   pypi_0    pypi
jupyterlab_launcher       0.13.1                     py_2    conda-forge
jupyterlab_server         0.2.0                      py_0    conda-forge
jyquickhelper             0.3.128                  pypi_0    pypi
kapteyn                   2.3             py36h6091dcd_1002    conda-forge
kiwisolver                1.0.1           py36h6bb024c_1002    conda-forge
krb5                      1.16.3            h05b26f9_1001    conda-forge
lazy-object-proxy         1.3.1                    pypi_0    pypi
libcurl                   7.64.0               h541490c_2    conda-forge
libedit                   3.1.20170329      hf8c457e_1001    conda-forge
libffi                    3.2.1             hf484d3e_1005    conda-forge
libgcc                    7.2.0                h69d50b8_2    conda-forge
libgcc-ng                 7.3.0                hdf63c60_0    conda-forge
libgfortran               3.0.0                         1    conda-forge
libgfortran-ng            7.2.0                hdf63c60_3    conda-forge
libiconv                  1.15              h14c3975_1004    conda-forge
libnetcdf                 4.6.2             hbdf4f91_1001    conda-forge
libogg                    1.3.2             h14c3975_1001    conda-forge
libopenblas               0.2.20               h9ac9557_7  
libpng                    1.6.36            h84994c4_1000    conda-forge
libsodium                 1.0.16            h14c3975_1001    conda-forge
libssh2                   1.8.0             h90d6eec_1004    conda-forge
libstdcxx-ng              7.3.0                hdf63c60_0    conda-forge
libtheora                 1.1.1             h14c3975_1001    conda-forge
libtiff                   4.0.10            h648cc4a_1001    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libvorbis                 1.3.5             h14c3975_1001    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxml2                   2.9.8             h143f9aa_1005    conda-forge
llvmlite                  0.24.0                   pypi_0    pypi
lmfit                     0.9.11                   pypi_0    pypi
locket                    0.2.0                    pypi_0    pypi
lxml                      4.2.4                    pypi_0    pypi
lz4                       2.1.6            py36h7b6447c_0  
lz4-c                     1.8.3             hf484d3e_1001    conda-forge
lzo                       2.10              h14c3975_1000    conda-forge
markupsafe                1.1.1            py36h14c3975_0    conda-forge
matplotlib                3.0.2                    pypi_0    pypi
matplotlib-base           3.0.3            py36h167e16e_0    conda-forge
matplotlib-colorbar       0.3.5                    pypi_0    pypi
metakernel                0.20.14                  pypi_0    pypi
mezmorize                 0.25.0                   pypi_0    pypi
mistune                   0.8.4           py36h14c3975_1000    conda-forge
mkl                       2019.1                      144  
mkl_fft                   1.0.10                   py36_0    conda-forge
mkl_random                1.0.2                    py36_0    conda-forge
more-itertools            4.3.0                 py36_1000    conda-forge
mpfr                      4.0.1             ha14ba45_1000    conda-forge
mpl-scatter-density       0.5                        py_0    conda-forge
msgpack                   0.5.6                    pypi_0    pypi
msgpack-python            0.6.1            py36h6bb024c_0    conda-forge
multi-key-dict            2.0.3                    pypi_0    pypi
multipledispatch          0.6.0                    pypi_0    pypi
nbconvert                 5.4.1                      py_2    conda-forge
nbformat                  4.4.0                      py_1    conda-forge
nbpresent                 3.0.0                    pypi_0    pypi
ncurses                   6.1               hf484d3e_1002    conda-forge
netcdf4                   1.4.3.2          py36h597e859_0    conda-forge
networkx                  2.2                        py_1    conda-forge
nodejs                    11.11.0              hf484d3e_0    conda-forge
nose                      1.3.7                 py36_1002    conda-forge
notebook                  5.6.0                    pypi_0    pypi
numba                     0.39.0                   pypi_0    pypi
numexpr                   2.6.10.dev0              pypi_0    pypi
numpy                     1.16.2           py36h7e9f1db_0  
numpy-base                1.16.2           py36hde5b4d6_0  
olefile                   0.46                       py_0    conda-forge
openblas                  0.3.3             h9ac9557_1001    conda-forge
openjpeg                  2.3.0             hf38bd82_1003    conda-forge
openssl                   1.1.1b               h14c3975_1    conda-forge
opt-einsum                2.3.2                    pypi_0    pypi
packaging                 17.1                     pypi_0    pypi
pandas                    0.24.2           py36hf484d3e_0    conda-forge
pandoc                    2.6                           1    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
pango                     1.40.14           h4ea9474_1004    conda-forge
param                     1.7.0                    pypi_0    pypi
parse                     1.11.1                   pypi_0    pypi
parso                     0.3.4                      py_0    conda-forge
partd                     0.3.8                    pypi_0    pypi
pbr                       4.2.0                    pypi_0    pypi
pcre                      8.41              hf484d3e_1003    conda-forge
pexpect                   4.6.0                 py36_1000    conda-forge
pickleshare               0.7.5                 py36_1000    conda-forge
pillow                    5.2.0                    pypi_0    pypi
pip                       18.0                     pypi_0    pypi
pixman                    0.34.0            h14c3975_1003    conda-forge
plotly                    3.7.0                      py_0    conda-forge
pluggy                    0.7.1                    pypi_0    pypi
ply                       3.11                     pypi_0    pypi
poppler                   0.74.0               h2ad7f00_0    conda-forge
poppler-data              0.4.9                         1    conda-forge
pprofile                  2.0.2                    pypi_0    pypi
progressbar2              3.38.0                     py_1    conda-forge
prometheus-client         0.3.1                    pypi_0    pypi
prometheus_client         0.6.0                      py_0    conda-forge
prompt-toolkit            1.0.15                   pypi_0    pypi
prompt_toolkit            2.0.9                      py_0    conda-forge
protobuf                  3.6.1                    pypi_0    pypi
psutil                    5.4.7                    pypi_0    pypi
pthread-stubs             0.4               h14c3975_1001    conda-forge
ptyprocess                0.6.0                 py36_1000    conda-forge
py                        1.5.4                    pypi_0    pypi
py-constr-field           0.0.1                     dev_0    <develop>
py-extrema                0.0.1                     dev_0    <develop>
py-heat                   0.0.6                    pypi_0    pypi
py-heat-magic             0.0.2                    pypi_0    pypi
pyasn1                    0.4.4                    pypi_0    pypi
pyasn1-modules            0.2.2                    pypi_0    pypi
pycparser                 2.19                     py36_1    conda-forge
pyct                      0.4.5                    pypi_0    pypi
pydocstyle                3.0.0                    pypi_0    pypi
pyevtk                    1.1.0                    pypi_0    pypi
pyface                    6.0.0                      py_1    conda-forge
pyfftw                    0.11.1          py36h3010b51_1001    conda-forge
pyflakes                  2.0.0                    pypi_0    pypi
pygments                  2.2.0                    pypi_0    pypi
pyhamcrest                1.9.0                      py_2    conda-forge
pyinstrument              3.0.1                    pypi_0    pypi
pyinstrument-cext         0.2.0                    pypi_0    pypi
pylint                    2.2.2                    pypi_0    pypi
pymsespymses              4.0.0                    pypi_0    pypi
pyopengl                  3.1.3b2                    py_1    conda-forge
pyopenssl                 19.0.0                   py36_0    conda-forge
pyparsing                 2.2.0                    pypi_0    pypi
pyperclip                 1.6.4                    pypi_0    pypi
pyqt                      4.11.4                   py36_3    conda-forge
pyquickhelper             1.8.2924                 pypi_0    pypi
pyrats                    0.1b0                     dev_0    <develop>
pyrsistent                0.14.11          py36h14c3975_0    conda-forge
pysocks                   1.6.8                 py36_1002    conda-forge
pytables                  3.4.4           py36h5d69a80_1004    conda-forge
pytest                    3.7.2                    pypi_0    pypi
pytest-arraydiff          0.3                        py_0    conda-forge
pytest-astropy            0.5.0                      py_0    conda-forge
pytest-doctestplus        0.3.0                      py_0    conda-forge
pytest-openfiles          0.3.1                      py_0    conda-forge
pytest-remotedata         0.3.1                      py_0    conda-forge
pytest-runner             4.4                        py_0    conda-forge
python                    3.6.7             h381d211_1004    conda-forge
python-dateutil           2.8.0                      py_0    conda-forge
python-utils              2.3.0                      py_1    conda-forge
pythreejs                 2.0.2                 py36_1000    conda-forge
pytz                      2018.5                   pypi_0    pypi
pywavelets                1.0.2            py36h3010b51_0    conda-forge
pyyaml                    3.13                     pypi_0    pypi
pyzmq                     17.1.2                   pypi_0    pypi
qt                        4.8.7                         2  
qtconsole                 4.4.1                    pypi_0    pypi
qtpy                      1.6.0              pyh8a2030e_0    conda-forge
readline                  7.0               hf8c457e_1001    conda-forge
remote-ikernel            0.4.6                     dev_0    <develop>
requests                  2.21.0                py36_1000    conda-forge
retrying                  1.3.3                      py_2    conda-forge
scikit-image              0.14.2           py36hf484d3e_1    conda-forge
scikit-learn              0.19.2                   pypi_0    pypi
scipy                     1.1.0                    pypi_0    pypi
semantic-version          2.6.0                    pypi_0    pypi
send2trash                1.5.0                      py_0    conda-forge
service_identity          17.0.0                     py_0    conda-forge
setuptools                39.1.0                   pypi_0    pypi
shapely                   1.6.4.post2              pypi_0    pypi
shove                     0.6.6                    pypi_0    pypi
simplegeneric             0.8.1                      py_1    conda-forge
sip                       4.18                     py36_1    conda-forge
six                       1.12.0                   pypi_0    pypi
smmap2                    2.0.4                    pypi_0    pypi
snakeviz                  1.0.0                    pypi_0    pypi
snowballstemmer           1.2.1                    pypi_0    pypi
sortedcontainers          2.0.4                    pypi_0    pypi
sphinx                    1.8.4                    pypi_0    pypi
sphinx-gallery            0.2.0                    pypi_0    pypi
sphinxcontrib-imagesvg    0.1                      pypi_0    pypi
sphinxcontrib-websupport  1.1.0                    pypi_0    pypi
sqlite                    3.26.0            h67949de_1001    conda-forge
stevedore                 1.29.0                   pypi_0    pypi
stuf                      0.9.16                   pypi_0    pypi
sympy                     1.2                      pypi_0    pypi
tables                    3.4.4                    pypi_0    pypi
tabulate                  0.8.3                      py_0    conda-forge
tbb                       2019.4               h6bb024c_0    conda-forge
tblib                     1.3.2                    pypi_0    pypi
tectonic                  0.1.11            hdf6f142_1001    conda-forge
tensorboard               1.10.0                   pypi_0    pypi
terminado                 0.8.1                 py36_1001    conda-forge
testpath                  0.4.2                 py36_1000    conda-forge
tinydb                    3.10.0                   pypi_0    pypi
tk                        8.6.9             h84994c4_1000    conda-forge
toolz                     0.9.0                      py_1    conda-forge
tornado                   5.1                      pypi_0    pypi
tqdm                      4.25.0                   pypi_0    pypi
traitlets                 4.3.2                 py36_1000    conda-forge
traits                    5.0.0            py36h14c3975_0    conda-forge
traitsui                  6.0.0                      py_1    conda-forge
traittypes                0.2.1                      py_1    conda-forge
twisted                   18.7.0                   pypi_0    pypi
typed-ast                 1.3.1                    pypi_0    pypi
uncertainties             3.0.2                    pypi_0    pypi
unify                     0.4                      pypi_0    pypi
untokenize                0.1.1                    pypi_0    pypi
unyt                      1.0.7                    pypi_0    pypi
urllib3                   1.24.1                py36_1000    conda-forge
vaex                      1.0.0b7                    py_0    conda-forge
vaex-astro                0.2.0                    py36_0    conda-forge
vaex-core                 0.6.1            py36hf8a1672_0    conda-forge
vaex-distributed          0.2.0                      py_0    conda-forge
vaex-hdf5                 0.3.0                    pypi_0    pypi
vaex-jupyter              0.2.1                      py_0    conda-forge
vaex-server               0.2.1                      py_0    conda-forge
vaex-ui                   0.2.0                      py_0    conda-forge
vaex-viz                  0.3.2                      py_0    conda-forge
virtualenv                16.0.0                   pypi_0    pypi
vtk                       8.1.1                    pypi_0    pypi
wcwidth                   0.1.7                    pypi_0    pypi
webencodings              0.5.1                      py_1    conda-forge
weightedstats             0.3                      pypi_0    pypi
werkzeug                  0.13                     pypi_0    pypi
wheel                     0.33.1                   py36_0    conda-forge
widgetsnbextension        3.4.0                    pypi_0    pypi
widgyts                   0.3.0                    pypi_0    pypi
wrapt                     1.11.1                   pypi_0    pypi
xarray                    0.10.8                   pypi_0    pypi
xlrd                      1.2.0                      py_0    conda-forge
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
xorg-libice               1.0.9             h14c3975_1004    conda-forge
xorg-libsm                1.2.3             h4937e3b_1000    conda-forge
xorg-libx11               1.6.7             h14c3975_1000    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.2             h14c3975_1007    conda-forge
xorg-libxext              1.3.3             h14c3975_1004    conda-forge
xorg-libxrender           0.9.10            h14c3975_1002    conda-forge
xorg-libxt                1.1.5             h14c3975_1002    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
xorg-xproto               7.0.31            h14c3975_1007    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
yaml                      0.1.7             h14c3975_1001    conda-forge
yarn                      1.13.0                        0    conda-forge
yt                        3.6.dev0                  dev_0    <develop>
yt-utils                  0.0.1                     dev_0    <develop>
zeromq                    4.2.5             hf484d3e_1006    conda-forge
zict                      0.1.3                    pypi_0    pypi
zlib                      1.2.11            h14c3975_1004    conda-forge
zope.interface            4.6.0           py36h14c3975_1000    conda-forge
zstd                      1.3.8             h0a35d5f_1001    conda-forge
```

**Comment by astrofrog** [comment]
@cphyc - it looks like you have an old version of glue, could you try and install the latest version with:

```
conda install glueviz=0.14
```

to see if that helps?

**Comment by cphyc** [comment]
Updating to version 0.14 solved the issue.

**Comment by astrofrog** [comment]
Great, thanks for confirming!
