### ISSUE TITLE
Faceted subsets don't work with categorical attributes

### ISSUE THREAD

**Issue by astrofrog** [glue-viz/glue#2004]
```
Traceback (most recent call last):
  File "/Users/tom/Dropbox/Code/Glue/glue/glue/external/echo/qt/connect.py", line 329, in update_prop
    setattr(self._instance, self._prop, value)
  File "/Users/tom/Dropbox/Code/Glue/glue/glue/external/echo/core.py", line 266, in __setattr__
    self._notify_global(**{attribute: value})
  File "/Users/tom/Dropbox/Code/Glue/glue/glue/utils/matplotlib.py", line 165, in wrapper
    return func(*args, **kwargs)
  File "/Users/tom/Dropbox/Code/Glue/glue/glue/viewers/matplotlib/state.py", line 225, in _notify_global
    super(MatplotlibLayerState, self)._notify_global(*args, **kwargs)
  File "/Users/tom/Dropbox/Code/Glue/glue/glue/external/echo/core.py", line 261, in _notify_global
    callback(**kwargs)
  File "/Users/tom/Dropbox/Code/Glue/glue/glue/external/echo/list.py", line 125, in callback
    self.notify(instance, wrapped_list, wrapped_list)
  File "/Users/tom/Dropbox/Code/Glue/glue/glue/external/echo/core.py", line 128, in notify
    cback(new)
  File "/Users/tom/Dropbox/Code/Glue/glue/glue/external/echo/core.py", line 253, in _notify_global_lists
    self._notify_global(**properties)
  File "/Users/tom/Dropbox/Code/Glue/glue/glue/utils/matplotlib.py", line 165, in wrapper
    return func(*args, **kwargs)
  File "/Users/tom/Dropbox/Code/Glue/glue/glue/viewers/matplotlib/state.py", line 182, in _notify_global
    super(MatplotlibDataViewerState, self)._notify_global(*args, **kwargs)
  File "/Users/tom/Dropbox/Code/Glue/glue/glue/external/echo/core.py", line 261, in _notify_global
    callback(**kwargs)
  File "/Users/tom/Dropbox/Code/Glue/glue/glue/utils/matplotlib.py", line 165, in wrapper
    return func(*args, **kwargs)
  File "/Users/tom/Dropbox/Code/Glue/glue/glue/viewers/scatter/layer_artist.py", line 467, in _update_scatter
    self._update_data()
  File "/Users/tom/Dropbox/Code/Glue/glue/glue/utils/matplotlib.py", line 165, in wrapper
    return func(*args, **kwargs)
  File "/Users/tom/Dropbox/Code/Glue/glue/glue/viewers/scatter/layer_artist.py", line 182, in _update_data
    x = ensure_numerical(self.layer[self._viewer_state.x_att].ravel())
  File "/Users/tom/Dropbox/Code/Glue/glue/glue/core/subset.py", line 292, in __getitem__
    ma = self.to_mask(v)
  File "/Users/tom/Dropbox/Code/Glue/glue/glue/core/subset.py", line 186, in to_mask
    return self.data.get_mask(self.subset_state, view=view)
  File "/Users/tom/Dropbox/Code/Glue/glue/glue/core/data.py", line 1246, in get_mask
    return subset_state.to_mask(self, view=view)
  File "/Users/tom/Dropbox/Code/Glue/glue/glue/core/decorators.py", line 32, in wrapper
    result = func(*args, **kwargs)
  File "/Users/tom/Dropbox/Code/Glue/glue/glue/core/subset.py", line 1032, in to_mask
    return self.op(self.state1.to_mask(data, view),
  File "/Users/tom/Dropbox/Code/Glue/glue/glue/core/decorators.py", line 32, in wrapper
    result = func(*args, **kwargs)
  File "/Users/tom/Dropbox/Code/Glue/glue/glue/core/subset.py", line 1577, in to_mask
    return self._operator(left, right)
TypeError: '<=' not supported between instances of 'numpy.ndarray' and 'categorical_ndarray'
```

**Comment by crayxt** [comment]
This would be very useful.
