### ISSUE TITLE
uncompatiable with PyQt5 5.13.0?

### ISSUE THREAD

**Issue by andyzysjtu** [glue-viz/glue#2037]
--- Logging error ---
Traceback (most recent call last):
  File "c:\program files\python37\lib\logging\__init__.py", line 1037, in emit
    stream.write(msg + self.terminator)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "c:\program files\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python37\Scripts\glue.exe\__main__.py", line 9, in <module>
    sys.exit(main())
  File "c:\program files\python37\lib\site-packages\glue\main.py", line 261, in main
    start_glue(**kwargs)
  File "c:\program files\python37\lib\site-packages\glue\main.py", line 188, in start_glue
    ga = GlueApplication(session=session)
  File "c:\program files\python37\lib\site-packages\glue\app\qt\application.py", line 302, in __init__
    self._setup_ui()
  File "c:\program files\python37\lib\site-packages\glue\app\qt\application.py", line 482, in _setup_ui
    self._hub.subscribe(self, DataCollectionMessage, handler=self._on_data_collection_change)
  File "c:\program files\python37\lib\site-packages\glue\core\hub.py", line 110, in subscribe
    subscriber, message_class.__name__)
Message: 'Subscribing %s to %s'
Arguments: (<glue.app.qt.application.GlueApplication object at 0x000000001598A318>, 'DataCollectionMessage')
--- Logging error ---
Traceback (most recent call last):
  File "c:\program files\python37\lib\logging\__init__.py", line 1037, in emit
    stream.write(msg + self.terminator)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "c:\program files\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python37\Scripts\glue.exe\__main__.py", line 9, in <module>
    sys.exit(main())
  File "c:\program files\python37\lib\site-packages\glue\main.py", line 261, in main
    start_glue(**kwargs)
  File "c:\program files\python37\lib\site-packages\glue\main.py", line 188, in start_glue
    ga = GlueApplication(session=session)
  File "c:\program files\python37\lib\site-packages\glue\app\qt\application.py", line 302, in __init__
    self._setup_ui()
  File "c:\program files\python37\lib\site-packages\glue\app\qt\application.py", line 483, in _setup_ui
    self._hub.subscribe(self, SettingsChangeMessage, handler=self._on_ui_settings_change)
  File "c:\program files\python37\lib\site-packages\glue\core\hub.py", line 110, in subscribe
    subscriber, message_class.__name__)
Message: 'Subscribing %s to %s'
Arguments: (<glue.app.qt.application.GlueApplication object at 0x000000001598A318>, 'SettingsChangeMessage')
--- Logging error ---
Traceback (most recent call last):
  File "c:\program files\python37\lib\logging\__init__.py", line 1037, in emit
    stream.write(msg + self.terminator)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "c:\program files\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python37\Scripts\glue.exe\__main__.py", line 9, in <module>
    sys.exit(main())
  File "c:\program files\python37\lib\site-packages\glue\main.py", line 261, in main
    start_glue(**kwargs)
  File "c:\program files\python37\lib\site-packages\glue\main.py", line 188, in start_glue
    ga = GlueApplication(session=session)
  File "c:\program files\python37\lib\site-packages\glue\app\qt\application.py", line 318, in __init__
    self._connect()
  File "c:\program files\python37\lib\site-packages\glue\app\qt\application.py", line 728, in _connect
    self._layer_widget.setup(self._data)
  File "c:\program files\python37\lib\site-packages\glue\app\qt\layer_tree_widget.py", line 536, in setup
    self.ui.layerTree.set_data_collection(collection)
  File "c:\program files\python37\lib\site-packages\glue\core\qt\data_collection_model.py", line 477, in set_data_collection
    self._model = DataCollectionModel(data_collection)
  File "c:\program files\python37\lib\site-packages\glue\core\qt\data_collection_model.py", line 254, in __init__
    self.register_to_hub(self.data_collection.hub)
  File "c:\program files\python37\lib\site-packages\glue\core\qt\data_collection_model.py", line 410, in register_to_hub
    hub.subscribe(self, msg, self.invalidate)
  File "c:\program files\python37\lib\site-packages\glue\core\hub.py", line 110, in subscribe
    subscriber, message_class.__name__)
Message: 'Subscribing %s to %s'
Arguments: (<glue.core.qt.data_collection_model.DataCollectionModel object at 0x000000000DAAAAF8>, 'DataCollectionDeleteMessage')
--- Logging error ---
Traceback (most recent call last):
  File "c:\program files\python37\lib\logging\__init__.py", line 1037, in emit
    stream.write(msg + self.terminator)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "c:\program files\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python37\Scripts\glue.exe\__main__.py", line 9, in <module>
    sys.exit(main())
  File "c:\program files\python37\lib\site-packages\glue\main.py", line 261, in main
    start_glue(**kwargs)
  File "c:\program files\python37\lib\site-packages\glue\main.py", line 188, in start_glue
    ga = GlueApplication(session=session)
  File "c:\program files\python37\lib\site-packages\glue\app\qt\application.py", line 318, in __init__
    self._connect()
  File "c:\program files\python37\lib\site-packages\glue\app\qt\application.py", line 728, in _connect
    self._layer_widget.setup(self._data)
  File "c:\program files\python37\lib\site-packages\glue\app\qt\layer_tree_widget.py", line 536, in setup
    self.ui.layerTree.set_data_collection(collection)
  File "c:\program files\python37\lib\site-packages\glue\core\qt\data_collection_model.py", line 477, in set_data_collection
    self._model = DataCollectionModel(data_collection)
  File "c:\program files\python37\lib\site-packages\glue\core\qt\data_collection_model.py", line 254, in __init__
    self.register_to_hub(self.data_collection.hub)
  File "c:\program files\python37\lib\site-packages\glue\core\qt\data_collection_model.py", line 410, in register_to_hub
    hub.subscribe(self, msg, self.invalidate)
  File "c:\program files\python37\lib\site-packages\glue\core\hub.py", line 110, in subscribe
    subscriber, message_class.__name__)
Message: 'Subscribing %s to %s'
Arguments: (<glue.core.qt.data_collection_model.DataCollectionModel object at 0x000000000DAAAAF8>, 'SubsetDeleteMessage')
--- Logging error ---
Traceback (most recent call last):
  File "c:\program files\python37\lib\logging\__init__.py", line 1037, in emit
    stream.write(msg + self.terminator)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "c:\program files\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python37\Scripts\glue.exe\__main__.py", line 9, in <module>
    sys.exit(main())
  File "c:\program files\python37\lib\site-packages\glue\main.py", line 261, in main
    start_glue(**kwargs)
  File "c:\program files\python37\lib\site-packages\glue\main.py", line 188, in start_glue
    ga = GlueApplication(session=session)
  File "c:\program files\python37\lib\site-packages\glue\app\qt\application.py", line 318, in __init__
    self._connect()
  File "c:\program files\python37\lib\site-packages\glue\app\qt\application.py", line 728, in _connect
    self._layer_widget.setup(self._data)
  File "c:\program files\python37\lib\site-packages\glue\app\qt\layer_tree_widget.py", line 536, in setup
    self.ui.layerTree.set_data_collection(collection)
  File "c:\program files\python37\lib\site-packages\glue\core\qt\data_collection_model.py", line 477, in set_data_collection
    self._model = DataCollectionModel(data_collection)
  File "c:\program files\python37\lib\site-packages\glue\core\qt\data_collection_model.py", line 254, in __init__
    self.register_to_hub(self.data_collection.hub)
  File "c:\program files\python37\lib\site-packages\glue\core\qt\data_collection_model.py", line 412, in register_to_hub
    hub.subscribe(self, m.DataCollectionAddMessage, self._on_add_data)
  File "c:\program files\python37\lib\site-packages\glue\core\hub.py", line 110, in subscribe
    subscriber, message_class.__name__)
Message: 'Subscribing %s to %s'
Arguments: (<glue.core.qt.data_collection_model.DataCollectionModel object at 0x000000000DAAAAF8>, 'DataCollectionAddMessage')
--- Logging error ---
Traceback (most recent call last):
  File "c:\program files\python37\lib\logging\__init__.py", line 1037, in emit
    stream.write(msg + self.terminator)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "c:\program files\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python37\Scripts\glue.exe\__main__.py", line 9, in <module>
    sys.exit(main())
  File "c:\program files\python37\lib\site-packages\glue\main.py", line 261, in main
    start_glue(**kwargs)
  File "c:\program files\python37\lib\site-packages\glue\main.py", line 188, in start_glue
    ga = GlueApplication(session=session)
  File "c:\program files\python37\lib\site-packages\glue\app\qt\application.py", line 318, in __init__
    self._connect()
  File "c:\program files\python37\lib\site-packages\glue\app\qt\application.py", line 728, in _connect
    self._layer_widget.setup(self._data)
  File "c:\program files\python37\lib\site-packages\glue\app\qt\layer_tree_widget.py", line 536, in setup
    self.ui.layerTree.set_data_collection(collection)
  File "c:\program files\python37\lib\site-packages\glue\core\qt\data_collection_model.py", line 477, in set_data_collection
    self._model = DataCollectionModel(data_collection)
  File "c:\program files\python37\lib\site-packages\glue\core\qt\data_collection_model.py", line 254, in __init__
    self.register_to_hub(self.data_collection.hub)
  File "c:\program files\python37\lib\site-packages\glue\core\qt\data_collection_model.py", line 413, in register_to_hub
    hub.subscribe(self, m.SubsetCreateMessage, self._on_add_subset)
  File "c:\program files\python37\lib\site-packages\glue\core\hub.py", line 110, in subscribe
    subscriber, message_class.__name__)
Message: 'Subscribing %s to %s'
Arguments: (<glue.core.qt.data_collection_model.DataCollectionModel object at 0x000000000DAAAAF8>, 'SubsetCreateMessage')
--- Logging error ---
Traceback (most recent call last):
  File "c:\program files\python37\lib\logging\__init__.py", line 1037, in emit
    stream.write(msg + self.terminator)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "c:\program files\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python37\Scripts\glue.exe\__main__.py", line 9, in <module>
    sys.exit(main())
  File "c:\program files\python37\lib\site-packages\glue\main.py", line 261, in main
    start_glue(**kwargs)
  File "c:\program files\python37\lib\site-packages\glue\main.py", line 188, in start_glue
    ga = GlueApplication(session=session)
  File "c:\program files\python37\lib\site-packages\glue\app\qt\application.py", line 318, in __init__
    self._connect()
  File "c:\program files\python37\lib\site-packages\glue\app\qt\application.py", line 728, in _connect
    self._layer_widget.setup(self._data)
  File "c:\program files\python37\lib\site-packages\glue\app\qt\layer_tree_widget.py", line 536, in setup
    self.ui.layerTree.set_data_collection(collection)
  File "c:\program files\python37\lib\site-packages\glue\core\qt\data_collection_model.py", line 501, in set_data_collection
    data_collection.hub.subscribe(self, Message, handler=self._update_viewport)
  File "c:\program files\python37\lib\site-packages\glue\core\hub.py", line 110, in subscribe
    subscriber, message_class.__name__)
Message: 'Subscribing %s to %s'
Arguments: (<glue.core.qt.data_collection_model.DataCollectionView object at 0x000000000D9ECC18>, 'Message')
--- Logging error ---
Traceback (most recent call last):
  File "c:\program files\python37\lib\logging\__init__.py", line 1037, in emit
    stream.write(msg + self.terminator)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "c:\program files\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python37\Scripts\glue.exe\__main__.py", line 9, in <module>
    sys.exit(main())
  File "c:\program files\python37\lib\site-packages\glue\main.py", line 261, in main
    start_glue(**kwargs)
  File "c:\program files\python37\lib\site-packages\glue\main.py", line 188, in start_glue
    ga = GlueApplication(session=session)
  File "c:\program files\python37\lib\site-packages\glue\app\qt\application.py", line 318, in __init__
    self._connect()
  File "c:\program files\python37\lib\site-packages\glue\app\qt\application.py", line 728, in _connect
    self._layer_widget.setup(self._data)
  File "c:\program files\python37\lib\site-packages\glue\app\qt\layer_tree_widget.py", line 537, in setup
    self.bind_selection_to_edit_subset()
  File "c:\program files\python37\lib\site-packages\glue\app\qt\layer_tree_widget.py", line 568, in bind_selection_to_edit_subset
    handler=self._update_subset_selection)
  File "c:\program files\python37\lib\site-packages\glue\core\hub.py", line 110, in subscribe
    subscriber, message_class.__name__)
Message: 'Subscribing %s to %s'
Arguments: (<glue.app.qt.layer_tree_widget.LayerTreeWidget object at 0x000000000D9EC798>, 'EditSubsetMessage')

**Comment by astrofrog** [comment]
Thanks for the report! It looks like PyQt5 5.13 was released today, so I'll work on trying to fix compatibility.

**Comment by astrofrog** [comment]
@andyzysjtu - what version of glue are you using, and how did you install it?

**Comment by andyzysjtu** [comment]
> @andyzysjtu - what version of glue are you using, and how did you install it?

glueviz-0.15.1 by pip

**Comment by astrofrog** [comment]
@andyzysjtu - could you try and start up IPython with the 'ipython' command, then typing:

```python
from glue import qglue
qglue()
```

Let me know if that works.

**Comment by andyzysjtu** [comment]
> @andyzysjtu - could you try and start up IPython with the 'ipython' command, then typing:
> 
> ```python
> from glue import qglue
> qglue()
> ```
> 
> Let me know if that works.

![image](https://user-images.githubusercontent.com/20332952/60755824-0a182000-a028-11e9-939b-5cdae4a425cb.png)

**Comment by andyzysjtu** [comment]
> > @andyzysjtu - could you try and start up IPython with the 'ipython' command, then typing:
> > ```python
> > from glue import qglue
> > qglue()
> > ```
> > 
> > 
> > Let me know if that works.
> 
> ![image](https://user-images.githubusercontent.com/20332952/60755824-0a182000-a028-11e9-939b-5cdae4a425cb.png)

It seems to err when access menu "Help -> Version information"

**Comment by andyzysjtu** [comment]
sorry, how is this issue?

**Comment by andyzysjtu** [comment]
it seems to be fixed with PyQT5 5.13.1.
