### ISSUE TITLE
Error when creating profile viewer

### ISSUE THREAD

**Issue by Cadair** [glue-viz/glue#2055]
```
/home/stuart/Git/glue/glue/viewers/common/qt/tool.py:6: UserWarning: glue.viewers.common.qt.tool is deprecated, use glue.viewers.common.tool instead
  'glue.viewers.common.tool instead', UserWarning)
WARNING: VerifyWarning: Verification reported errors: [astropy.io.fits.verify]
WARNING:sunpy:VerifyWarning: Verification reported errors:
WARNING: VerifyWarning: HDU 0: [astropy.io.fits.verify]
WARNING:sunpy:VerifyWarning: HDU 0:
WARNING: VerifyWarning:     Card 87: [astropy.io.fits.verify]
WARNING:sunpy:VerifyWarning:     Card 87:
WARNING: VerifyWarning:         Card 'CADPL_DV' is not FITS standard (invalid value string: 'NAN /').  Fixed 'CADPL_DV' card to meet the FITS standard. [astropy.io.fits.verify]
WARNING:sunpy:VerifyWarning:         Card 'CADPL_DV' is not FITS standard (invalid value string: 'NAN /').  Fixed 'CADPL_DV' card to meet the FITS standard.
WARNING: VerifyWarning:     Card 89: [astropy.io.fits.verify]
WARNING:sunpy:VerifyWarning:     Card 89:
WARNING: VerifyWarning:         Card 'CADEX_DV' is not FITS standard (invalid value string: 'NAN /').  Fixed 'CADEX_DV' card to meet the FITS standard. [astropy.io.fits.verify]
WARNING:sunpy:VerifyWarning:         Card 'CADEX_DV' is not FITS standard (invalid value string: 'NAN /').  Fixed 'CADEX_DV' card to meet the FITS standard.
WARNING: VerifyWarning: Note: astropy.io.fits uses zero-based indexing.
 [astropy.io.fits.verify]
WARNING:sunpy:VerifyWarning: Note: astropy.io.fits uses zero-based indexing.

AttributeError: __getattribute__

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/stuart/Git/glue/glue/app/qt/mdi_area.py", line 65, in dropEvent
    new_layer(layer)
  File "/home/stuart/Git/glue/glue/app/qt/mdi_area.py", line 56, in new_layer
    application.choose_new_data_viewer(layer)
  File "/home/stuart/Git/glue/glue/app/qt/application.py", line 1008, in choose_new_data_viewer
    return self.do(cmd)
  File "/home/stuart/Git/glue/glue/core/application_base.py", line 262, in do
    return self._cmds.do(command)
  File "/home/stuart/Git/glue/glue/core/command.py", line 126, in do
    result = cmd.do(self._session)
  File "/home/stuart/Git/glue/glue/core/command.py", line 216, in do
    viewer = session.application.new_data_viewer(self.viewer, self.data)
  File "/home/stuart/Git/glue/glue/utils/matplotlib.py", line 170, in wrapper
    result = func(*args, **kwargs)
  File "/home/stuart/Git/glue/glue/app/qt/application.py", line 1012, in new_data_viewer
    viewer = super(GlueApplication, self).new_data_viewer(viewer_class, data=data, state=state)
  File "/home/stuart/Git/glue/glue/core/application_base.py", line 85, in new_data_viewer
    c = viewer_class(self._session)
  File "/home/stuart/Git/glue/glue/viewers/common/qt/data_viewer.py", line 31, in __call__
    obj.initialize_toolbar()
  File "/home/stuart/Git/glue/glue/utils/matplotlib.py", line 165, in wrapper
    return func(*args, **kwargs)
  File "/home/stuart/Git/glue/glue/utils/matplotlib.py", line 165, in wrapper
    return func(*args, **kwargs)
  File "/home/stuart/Git/glue/glue/viewers/common/qt/data_viewer.py", line 160, in initialize_toolbar
    mode = mode_cls(self)
  File "/home/stuart/Git/glue/glue/viewers/profile/qt/profile_tools.py", line 50, in __init__
    self._profile_tools = ProfileTools(viewer)
  File "/home/stuart/Git/glue/glue/viewers/profile/qt/profile_tools.py", line 76, in __init__
    directory=os.path.dirname(__file__))
  File "/home/stuart/Git/glue/glue/utils/qt/helpers.py", line 145, in load_ui
    return loadUi(full_path, parent)
  File "/home/stuart/.virtualenvs/glue/lib/python3.7/site-packages/PyQt5/uic/__init__.py", line 226, in loadUi
    return DynamicUILoader(package).loadUi(uifile, baseinstance, resource_suffix)
  File "/home/stuart/.virtualenvs/glue/lib/python3.7/site-packages/PyQt5/uic/Loader/loader.py", line 72, in loadUi
    return self.parse(filename, resource_suffix, basedir)
  File "/home/stuart/.virtualenvs/glue/lib/python3.7/site-packages/PyQt5/uic/uiparser.py", line 1011, in parse
    actor(elem)
  File "/home/stuart/.virtualenvs/glue/lib/python3.7/site-packages/PyQt5/uic/uiparser.py", line 932, in createConnections
    QtCore.QMetaObject.connectSlotsByName(self.toplevelWidget)
SystemError: <built-in function connectSlotsByName> returned a result with an error set
```

**Comment by astrofrog** [comment]
Fixed in https://github.com/glue-viz/glue/commit/09e8d2834d4b8fc2fdeeefca6b0acbd50c9c8af4
