### ISSUE TITLE
No OpenGL support PyQt5 again

### ISSUE THREAD

**Issue by pscicluna** [glue-viz/glue#2291]
I'm getting an occurrence of https://github.com/glue-viz/glue/issues/1395 on fedora 34 with a new install of glue in a clean conda environment with python 3.9. Following the docs, I attempted to update conda, then update all packages, but the versions of pyqt, qt and qtpy do not appear to have changed from the previous (up to date!) versions. No required dependencies seem to be missing. Here are the current versions:

```
Name                    Version                   Build     Channel
pyqt                      5.9.2            py39h2531618_6  
qt                        5.9.7                h5867ecd_1  
qtconsole                 5.3.0              pyhd3eb1b0_0  
qtpy                      2.0.1              pyhd3eb1b0_0  
```
Do you have any idea why this might have come back?

**Comment by pscicluna** [comment]
It looks like the error is originating in vispy, but I can't figure out what is causing it. After updating to the latest version of vispy, I get the following warnings:

```
WARNING: OpenGL version could not be determined, which might be a sign that OpenGL is not loaded correctly.
WARNING:vispy:OpenGL version could not be determined, which might be a sign that OpenGL is not loaded correctly.
```

Before the update, I had vispy 0.7.3. With that version, I got a long traceback which terminated in distutils on a call from vispy to _gl_initialise to determine the version of *something*, I assume OpenGL. As far as I can tell, OpenGL is correctly installed, with version 4.6.

**Comment by dhomeier** [comment]
Are the icu and sip versions unchanged as well?
Can you try to reinstall OpenGL/Mesa?

**Comment by pscicluna** [comment]
conda list --revisions only shows one transaction for each of icu and sip, so I assume their versions didn't change.

I'm not sure if I'll be able to reinstall OpenGL, but will give it a try. I don't have full management rights on this machine. That might be useful, however, as I now notice that I get a set of errors from libgl and MESA-LOADER on starting glue - iris and swrast fail to load.

**Comment by ManonMarchand** [comment]
Same issue here, on a clean conda environnement in ubuntu 20.04.5. 
I tried using PyQt6 just in case and I now get a different error. 

```
Traceback (most recent call last):
  File "/home/usr/miniconda3/envs/test-glue/bin/glue", line 11, in <module>
    sys.exit(main())
  File "/home/usr/miniconda3/envs/test-glue/lib/python3.10/site-packages/glue/main.py", line 259, in main
    start_glue(**kwargs)
  File "/home/usr/miniconda3/envs/test-glue/lib/python3.10/site-packages/glue/main.py", line 148, in start_glue
    app = get_qapp()
  File "/home/usr/miniconda3/envs/test-glue/lib/python3.10/site-packages/glue/utils/qt/app.py", line 69, in get_qapp
    qapp.setAttribute(QtCore.Qt.AA_UseHighDpiPixmaps)
AttributeError: type object 'Qt' has no attribute 'AA_UseHighDpiPixmaps'

```

**Comment by dhomeier** [comment]
> File "/home/usr/miniconda3/envs/test-glue/lib/python3.10/site-packages/glue/utils/qt/app.py", line 69, in get_qapp
>     qapp.setAttribute(QtCore.Qt.AA_UseHighDpiPixmaps)
> AttributeError: type object 'Qt' has no attribute 'AA_UseHighDpiPixmaps'

Can you check your installed glueviz/glue-core version? This was fixed in 1.6, but the latest miniconda3 (on macOS...) only offers 1.2.4 for the (default!) python-3.10. Until they get their distribution updated you have probably two options:
1. Set your glue environment up with `python=3.9`, which does have glue-core==1.6.0 for me.
2. `pip install --upgrade glue-core` on top of your miniconda installation (as you probably have already done for PyQt6); that should give you 1.6.0 and fix the PyQt6 conflicts at least.

**Comment by ManonMarchand** [comment]
I tried your first solution and it works perfectly, thanks!

For potential future readers if you have issues in a miniconda environment with python 3.10 :

```
$ conda create -n "test-glue" python=3.9.*
$ conda activate test-glue
$ conda install -c glueviz glueviz
$ glue
```
