### ISSUE TITLE
glue reads .csv file but only Table Viewer is available

### ISSUE THREAD

**Issue by alexbinks** [glue-viz/glue#2303]
**Describe the bug**
The glueviz interface will only display .csv data in Table Viewer. 
When any plotting options are selected, the software remains idle.
However, there are error messages printed to the terminal, which
are appended at the bottom of this report. The final python error
message reads

TypeError: attrs() got an unexpected keyword argument 'eq'

**To Reproduce**
Steps to reproduce the behavior such as:
1. copy and paste these lines and save as glue_test_mini.csv

a,b,c,d,e
1,2,3,4,5
6,7,8,9,10
11,12,13,14,15
16,17,18,19,20
21,22,23,24,25

Note that my original file is 20,000 lines with different headers
and 18 columns. With this basic dummy table the same errors
are returned.

2. Run glue from the terminal: > glue glue_test_mini.csv
3. Drag and drop the "glue_test_mini" data into the plot window.
4. Click on "2D scatter" -> error message reported in the terminal.
5. Click on "Table Viewer" -> table is correctly displayed (attached)

**Expected behavior**
A 2D scatter plot GUI to be displayed when the "2D scatter" option
is selected.

**Screenshots**
![glue_issue1](https://user-images.githubusercontent.com/60255737/170550467-3898a6c0-43ff-45a9-9cdc-e727d04ce312.png)
![glue_issue2](https://user-images.githubusercontent.com/60255737/170550494-0f55427f-6097-49cf-b0c0-31d8575a3898.png)
![glue_issue3](https://user-images.githubusercontent.com/60255737/170550505-e72a2481-b443-4fd0-88bd-eeae05dcbebe.png)

**Details:**

- Operating System: Ubuntu 20.04.1 x86_64
- Python version: Python 3.9.7
- Glue version: 1.2.4
- How you installed glue: conda install -c glueviz glueviz

**Additional context**
Traceback (most recent call last):
  File "/home/abinks/anaconda3/lib/python3.9/site-packages/glue/app/qt/mdi_area.py", line 63, in dropEvent
    new_layer(layer)
  File "/home/abinks/anaconda3/lib/python3.9/site-packages/glue/app/qt/mdi_area.py", line 54, in new_layer
    application.choose_new_data_viewer(layer)
  File "/home/abinks/anaconda3/lib/python3.9/site-packages/glue/app/qt/application.py", line 1009, in choose_new_data_viewer
    return self.do(cmd)
  File "/home/abinks/anaconda3/lib/python3.9/site-packages/glue/core/application_base.py", line 258, in do
    return self._cmds.do(command)
  File "/home/abinks/anaconda3/lib/python3.9/site-packages/glue/core/command.py", line 125, in do
    result = cmd.do(self._session)
  File "/home/abinks/anaconda3/lib/python3.9/site-packages/glue/core/command.py", line 215, in do
    viewer = session.application.new_data_viewer(self.viewer, self.data)
  File "/home/abinks/anaconda3/lib/python3.9/site-packages/glue/utils/matplotlib.py", line 170, in wrapper
    result = func(*args, **kwargs)
  File "/home/abinks/anaconda3/lib/python3.9/site-packages/glue/app/qt/application.py", line 1013, in new_data_viewer
    viewer = super(GlueApplication, self).new_data_viewer(viewer_class, data=data, state=state)
  File "/home/abinks/anaconda3/lib/python3.9/site-packages/glue/core/application_base.py", line 82, in new_data_viewer
    c = viewer_class(self._session)
  File "/home/abinks/anaconda3/lib/python3.9/site-packages/glue/viewers/common/qt/data_viewer.py", line 27, in __call__
    obj = type.__call__(cls, *args, **kwargs)
  File "/home/abinks/anaconda3/lib/python3.9/site-packages/glue/utils/matplotlib.py", line 165, in wrapper
    return func(*args, **kwargs)
  File "/home/abinks/anaconda3/lib/python3.9/site-packages/glue/viewers/scatter/qt/data_viewer.py", line 30, in __init__
    MatplotlibDataViewer.__init__(self, session, parent=parent, state=state, projection=proj)
  File "/home/abinks/anaconda3/lib/python3.9/site-packages/glue/utils/matplotlib.py", line 165, in wrapper
    return func(*args, **kwargs)
  File "/home/abinks/anaconda3/lib/python3.9/site-packages/glue/viewers/matplotlib/qt/data_viewer.py", line 36, in __init__
    self.figure, self.axes = init_mpl(self.mpl_widget.canvas.fig, wcs=wcs, projection=projection)
  File "/home/abinks/anaconda3/lib/python3.9/site-packages/glue/viewers/matplotlib/mpl_axes.py", line 44, in init_mpl
    from astropy.visualization.wcsaxes import WCSAxesSubplot
  File "/home/abinks/anaconda3/lib/python3.9/site-packages/astropy/visualization/wcsaxes/__init__.py", line 7, in <module>
    import pytest
  File "/home/abinks/anaconda3/lib/python3.9/site-packages/pytest/__init__.py", line 5, in <module>
    from _pytest._code import ExceptionInfo
  File "/home/abinks/anaconda3/lib/python3.9/site-packages/_pytest/_code/__init__.py", line 2, in <module>
    from .code import Code
  File "/home/abinks/anaconda3/lib/python3.9/site-packages/_pytest/_code/code.py", line 963, in <module>
    @attr.s(eq=False, auto_attribs=True)
TypeError: attrs() got an unexpected keyword argument 'eq'

**Comment by dhomeier** [comment]
Hi Alex, thanks for the detailed bug report. The traceback however looks like the actual error arises entirely within your `astropy.visualization.wcsaxes` module, or even just on importing `pytest`. Could you check the result of the following in your installation:
```python
import pytest
from astropy.visualization.wcsaxes import WCSAxesSubplot
```
and also provide the astropy and pytest versions?
TIA.

**Comment by astrofrog** [comment]
Yes I think @dhomeier is right - I think this is something that was fixed with more recent astropy versions:

https://github.com/astropy/astropy/blob/2288ecd4e9c4d3722d72b7f4a6555a34f4f04fc7/astropy/visualization/wcsaxes/__init__.py#L6-L11

I think you either need to upgrade the attrs package or the astropy package.

**Comment by alexbinks** [comment]
Hi Derek and Thomas,
Thanks for looking into my request.

I upgraded astropy* and pytest*, and now glue seems to be running fine, so the issue is resolved.
*>>pip upgrade astropy
*>>pip upgrade pytest

**Comment by astrofrog** [comment]
Thanks for letting us know!
