### ISSUE TITLE
Error Launching GlueViz from Navigator and Anaconda Prompt

### ISSUE THREAD

**Issue by jgregory2u** [glue-viz/glue#2421]
Traceback (most recent call last):
File "C:\Users\jgregory\AppData\Local\anaconda3\envs\Live_Session_Timing\Scripts\glue-script.py", line 10, in 
sys.exit(main())
File "C:\Users\jgregory\AppData\Local\anaconda3\envs\Live_Session_Timing\lib\site-packages\glue\main.py", line 259, in main
start_glue(**kwargs)
File "C:\Users\jgregory\AppData\Local\anaconda3\envs\Live_Session_Timing\lib\site-packages\glue\main.py", line 156, in start_glue
load_plugins(splash=splash, require_qt_plugins=True)
File "C:\Users\jgregory\AppData\Local\anaconda3\envs\Live_Session_Timing\lib\site-packages\glue\main.py", line 347, in load_plugins
splash.set_progress(100. * iplugin / float(n_plugins))
File "C:\Users\jgregory\AppData\Local\anaconda3\envs\Live_Session_Timing\lib\site-packages\glue\app\qt\splash_screen.py", line 31, in set_progress
self.progress.setValue(value)
TypeError: setValue(self, int): argument 1 has unexpected type 'float'

**Comment by astrofrog** [comment]
This should already be fixed in the latest version of glue, but it might take some time to propagate back to Anaconda. Can you try and do:

```
conda install -c conda-forge glue-core
```

to see if that helps?
