### ISSUE TITLE
can't open ipython terminal

### ISSUE THREAD

**Issue by smallstudent2021** [glue-viz/glue#2448]
after start glue， click **terminal** ，there is following message：

Traceback (most recent call last):
  File "E:\Python310\lib\site-packages\glue\app\qt\application.py", line 1170, in _toggle_terminal
    self._create_terminal()
  File "E:\Python310\lib\site-packages\glue\app\qt\application.py", line 1155, in _create_terminal
    widget = glue_terminal(data_collection=self._data,
  File "E:\Python310\lib\site-packages\glue\app\qt\terminal.py", line 242, in glue_terminal
    return in_process_console(console_class=DragAndDropTerminal, **kwargs)
  File "E:\Python310\lib\site-packages\glue\app\qt\terminal.py", line 83, in in_process_console
    start_in_process_kernel()
  File "E:\Python310\lib\site-packages\glue\app\qt\terminal.py", line 62, in start_in_process_kernel
    kernel_manager.start_kernel()
  File "E:\Python310\lib\site-packages\ipykernel\inprocess\manager.py", line 47, in start_kernel
    self.kernel = InProcessKernel(parent=self, session=self.session)
  File "E:\Python310\lib\site-packages\ipykernel\inprocess\ipkernel.py", line 70, in __init__
    super().__init__(**traits)
  File "E:\Python310\lib\site-packages\ipykernel\ipkernel.py", line 90, in __init__
    self.shell = self.shell_class.instance(
  File "E:\Python310\lib\site-packages\traitlets\config\configurable.py", line 551, in instance
    inst = cls(*args, **kwargs)
  File "E:\Python310\lib\site-packages\IPython\core\interactiveshell.py", line 698, in __init__
    self.init_io()
  File "E:\Python310\lib\site-packages\IPython\core\interactiveshell.py", line 874, in init_io
    io.stdout = io.IOStream(sys.stdout)
  File "E:\Python310\lib\site-packages\IPython\utils\io.py", line 31, in __init__
    raise ValueError("fallback required, but not specified")
ValueError: fallback required, but not specified

how to solve this problem

**Comment by dhomeier** [comment]
Could you add some relevant information as specified in the `Bug` template?

**Details:**

- Operating System: [e.g. macOS 10.13.2]
- Python version (``python --version``): [e.g. Python 3.10.9]
- Glue version (``glue --version``): [e.g. 1.13.1]
- How you installed glue: [e.g. conda or pip]


Thanks!

**Comment by smallstudent2021** [comment]
hi
@dhomeier 
Operating System: [win10 professional19045.3570]
Python version (python --version): [Python 3.10.10]
Glue version (glue --version): [1.5.0]
How you installed glue: [pip]
IPython version (ipython --7.34.0)
ipykernel version (ipykernel --  6.17.0)


best regards

more glue information as following：
Glue: 1.5.0
Python: 3.10.10
PyQt5: PyQt: 5.15.9 - Qt: 5.15.2
PySide2: Not installed
qtpy: 2.2.1
setuptools: 57.4.0
echo: 0.8.0
numpy: 1.23.4
matplotlib: 3.6.1
pandas: 1.5.1
astropy: 5.1.1
dill: 0.3.6
h5py: 3.7.0
xlrd: 2.0.1
openpyxl: 3.0.10
mpl-scatter-density: 0.7
casa-formats-io: 0.2.1
edxia: unknown version
glue-core: 1.5.0
glue-vispy-viewers: 1.0.5
IPython: 7.34.0
qtconsole: 5.3.2
ipykernel: 6.17.0
traitlets: 5.5.0
pygments: 2.13.0
pyzmq: 24.0.1
scipy: 1.9.3
scikit-image: 0.19.3
PyAVM: Not installed
spectral-cube: 0.6.0
astrodendro: Not installed
mock: Not installed
pytest: Not installed
plotly: Not installed

**Comment by dhomeier** [comment]
Your installed versions are quite old; I'd suggest to run (at least)
`pip install --upgrade glue ipython ipykernel`
The failure may be related or not, but it will definitely be easier to track down with current versions installed – IPython 8.x in any case does not even have the "fallback required" error above.

**Comment by smallstudent2021** [comment]
thank you very much
I fixed it and update ipython==8.13.1 and ipykernel==5.3.4 @dhomeier
