### ISSUE TITLE
GluViz application can't start from Anaconda Navigator

### ISSUE THREAD

**Issue by amx-sandor** [glue-viz/glue#2506]
Hi Team,

I installed Anaconda Navigator on my PC (Windows 10, 64 bit) , I wanted to try the GlueViz application. I installed GlueViz from under Anaconda Navigator. When I clicked on the Launch button, the application did not start, but after a short while it gave the following error message:

0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
Traceback (most recent call last):
File "C:\Users\sandor.hegedus\AppData\Local\anaconda3\Scripts\glue-script.py", line 10, in
sys.exit(main())
^^^^^^
File "C:\Users\sandor.hegedus\AppData\Local\anaconda3\Lib\site-packages\glue\main.py", line 259, in main
start_glue(**kwargs)
File "C:\Users\sandor.hegedus\AppData\Local\anaconda3\Lib\site-packages\glue\main.py", line 156, in start_glue
load_plugins(splash=splash, require_qt_plugins=True)
File "C:\Users\sandor.hegedus\AppData\Local\anaconda3\Lib\site-packages\glue\main.py", line 347, in load_plugins
splash.set_progress(100. * iplugin / float(n_plugins))
File "C:\Users\sandor.hegedus\AppData\Local\anaconda3\Lib\site-packages\glue\app\qt\splash_screen.py", line 31, in set_progress
self.progress.setValue(value)
TypeError: setValue(self, value: int): argument 1 has unexpected type 'float'

Can you help me with this? Thx.

Sandor

**Comment by kasouthon** [comment]
Hi,

I ran into the same error recently when trying to launch GlueViz via Anaconda for the first time. I managed to get it working (and successfully launched) by opening the file:
{your-path-to}\anaconda3\Lib\site-packages\glue\app\qt\splash_screen.py

and simply changing this (line 31):
self.progress.setValue(value)
to this:
self.progress.setValue(int(value))

This is not a particularly elegant solution, but it worked for me - hope it helps!

Kate
