### ISSUE TITLE
Failed to save glue session

### ISSUE THREAD

**Issue by hcferguson** [glue-viz/glue#534]
My glue session failed to save. Here is the traceback.

Traceback (most recent call last):
  File "glue/core/application_base.pyc", line 24, in wrapper
  File "glue/core/application_base.pyc", line 94, in save_session
  File "glue/core/state.pyc", line 341, in dump
  File "glue/core/state.pyc", line 319, in dumpo
  File "glue/core/state.pyc", line 253, in do_all
  File "glue/core/state.pyc", line 275, in do
  File "glue/core/application_base.pyc", line 379, in __gluestate__
  File "glue/core/util.pyc", line 342, in properties
  File "glue/core/util.pyc", line 342, in <dictcomp>
  File "glue/qt/widget_properties.pyc", line 54, in __get__
  File "glue/qt/widget_properties.pyc", line 102, in getter
AttributeError: 'PySide.QtGui.QLabel' object has no attribute 'isChecked'

**Comment by astrofrog** [comment]
@hcferguson - just to check, are you still seeing this issue? Would it be possible to send me the datafiles required, specifically:

```python
/Users/ferguson/data/candels/goodss/mosaics/current/goods_s_all_combined_v0.5/gs_all_candels_ers_udf_f160w_v0.5_drz.fits 
/Users/ferguson/data/herschel_deconfusion/result_files_SAM_5e4_alpha_1_start_0_minus1.txt 
/Users/ferguson/data/candels/goodss/mosaics/current/irac/s12_ch4_v0.30_sci.fits 
/Users/ferguson/data/herschel_deconfusion/5e4_pm3_start_0_alpha_1_minus1.fits 
/Users/ferguson/data/candels/goodss/mosaics/current/mips/s1_mips_v0.30_sci.fits 
/Users/ferguson/data/herschel_deconfusion/gh_goodss_dr1_160_sci.fits 
```

?

**Comment by hcferguson** [comment]
I'll give it a try, and also see if I can find the data files...

**Comment by astrofrog** [comment]
@hcferguson - I'm going to close this issue, but please let me know if you have problems in future with loading session files.
