### ISSUE TITLE
Error installing glueviz in Linux with Anaconda

### ISSUE THREAD

**Issue by nudomarinero** [glue-viz/glue#562]
I tried the installation command suggested in the documentation:
`pythonw -m pip install glueviz`
but the command `pythonw` is not available (at least directly) in my version of Anaconda in Linux (Debian Jessie).
When I try directly with `pip install glueviz` I got the following error:
```
(...)
copying glue/qt/ui/subset_facet.ui -> build/lib/glue/qt/ui

running install_lib

Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "/tmp/pip-build-mp42hW/glueviz/setup.py", line 67, in <module>

    package_data={'': ['*.png', '*.ui']}

  File "/home/jsm/programs/soft/anaconda/lib/python2.7/distutils/core.py", line 151, in setup

    dist.run_commands()

  File "/home/jsm/programs/soft/anaconda/lib/python2.7/distutils/dist.py", line 953, in run_commands

    self.run_command(cmd)

  File "/home/jsm/programs/soft/anaconda/lib/python2.7/distutils/dist.py", line 972, in run_command

    cmd_obj.run()

  File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 61, in run

    return orig.install.run(self)

  File "/home/jsm/programs/soft/anaconda/lib/python2.7/distutils/command/install.py", line 575, in run

    self.run_command(cmd_name)

  File "/home/jsm/programs/soft/anaconda/lib/python2.7/distutils/cmd.py", line 326, in run_command

    self.distribution.run_command(command)

  File "/home/jsm/programs/soft/anaconda/lib/python2.7/distutils/dist.py", line 971, in run_command

    cmd_obj.ensure_finalized()

  File "/home/jsm/programs/soft/anaconda/lib/python2.7/distutils/cmd.py", line 109, in ensure_finalized

    self.finalize_options()

  File "/usr/lib/python2.7/dist-packages/setuptools/command/install_lib.py", line 16, in finalize_options

    self.set_undefined_options('install',('install_layout','install_layout'))

  File "/home/jsm/programs/soft/anaconda/lib/python2.7/distutils/cmd.py", line 302, in set_undefined_options

    getattr(src_cmd_obj, src_option))

  File "/home/jsm/programs/soft/anaconda/lib/python2.7/distutils/cmd.py", line 105, in __getattr__

    raise AttributeError, attr

AttributeError: install_layout

----------------------------------------
Cleaning up...
```
Any idea of the origin of the error?

**Comment by astrofrog** [comment]
@nudomarinero - I am working on providing conda packages for glue, I will get back to you later today.

**Comment by astrofrog** [comment]
@nudomarinero - can you try:

```
conda install -c astrofrog glueviz
```

and let me know if this works?

**Comment by nudomarinero** [comment]
@astrofrog - I have installed it using the command. The installation process did not raise any error. Later I executed the command `glue` and I got the following error:
```
jsm@leda:~/programs/temp$ glue
Traceback (most recent call last):
  File "/home/jsm/programs/soft/anaconda/bin/glue", line 6, in <module>
    sys.exit(main())
  File "/home/jsm/programs/soft/anaconda/lib/python2.7/site-packages/glueviz-0.4.0-py2.7.egg/glue/main.py", line 229, in main
    start_glue(config=opt.config)
  File "/home/jsm/programs/soft/anaconda/lib/python2.7/site-packages/glueviz-0.4.0-py2.7.egg/glue/main.py", line 174, in start_glue
    ga = GlueApplication(session=session)
  File "/home/jsm/programs/soft/anaconda/lib/python2.7/site-packages/glueviz-0.4.0-py2.7.egg/glue/qt/glue_application.py", line 188, in __init__
    self._setup_ui()
  File "/home/jsm/programs/soft/anaconda/lib/python2.7/site-packages/glueviz-0.4.0-py2.7.egg/glue/qt/glue_application.py", line 207, in _setup_ui
    self._ui = load_ui('glue_application', None)
  File "/home/jsm/programs/soft/anaconda/lib/python2.7/site-packages/glueviz-0.4.0-py2.7.egg/glue/qt/qtutil.py", line 747, in load_ui
    return _load_ui_pyqt4(path, parent)
  File "/home/jsm/programs/soft/anaconda/lib/python2.7/site-packages/glueviz-0.4.0-py2.7.egg/glue/qt/qtutil.py", line 724, in _load_ui_pyqt4
    return loadUi(path, parent)
  File "/usr/lib/python2.7/dist-packages/PyQt4/uic/__init__.py", line 238, in loadUi
    return DynamicUILoader(package).loadUi(uifile, baseinstance, resource_suffix)
  File "/usr/lib/python2.7/dist-packages/PyQt4/uic/Loader/loader.py", line 50, in __init__
    UIParser.__init__(self, QtCore, QtGui, LoaderCreatorPolicy(package))
  File "/usr/lib/python2.7/dist-packages/PyQt4/uic/uiparser.py", line 170, in __init__
    self.factory = QObjectCreator(creatorPolicy)
  File "/usr/lib/python2.7/dist-packages/PyQt4/uic/objcreator.py", line 97, in __init__
    self._cwFilters.append(plugin_locals["getFilter"]())
  File "<string>", line 22, in getFilter
ImportError: /usr/lib/libkdecore.so.5: undefined symbol: _ZNK7QSslKey9algorithmEv
```

**Comment by astrofrog** [comment]
@nudomarinero - this is very strange, for some reason it is picking up the system installation of PyQt. Can you show me the output of the conda install command you ran so I can check what dependencies it installed?

**Comment by nudomarinero** [comment]
@astrofrog - Of course:
```
jsm@leda:~/programs/temp$ conda install -c astrofrog glueviz
Fetching package metadata: ...
Solving package specifications: .
Package plan for installation in environment /home/jsm/programs/soft/anaconda:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    zlib-1.2.8                 |                0         100 KB
    openssl-1.0.1k             |                0         2.6 MB
    cairo-1.12.18              |                0         593 KB
    py2cairo-1.10.0            |           py27_2          36 KB
    conda-env-2.0.1            |           py27_0          15 KB
    six-1.9.0                  |           py27_0          17 KB
    pytz-2014.9                |           py27_0         175 KB
    setuptools-12.0.5          |           py27_0         436 KB
    scipy-0.15.1               |       np19py27_0        37.0 MB
    astropy-1.0rc1             |       np19py27_0         7.3 MB
    conda-3.8.3                |           py27_0         162 KB
    pandas-0.15.2              |       np19py27_0         9.9 MB
    matplotlib-1.4.2           |       np19py27_0        44.8 MB
    scikit-image-0.10.1        |       np19py27_0        21.6 MB
    glueviz-0.4.0              |       np19py27_0         974 KB
    ------------------------------------------------------------
                                           Total:       125.7 MB

The following NEW packages will be INSTALLED:

    conda-env:    2.0.1-py27_0     
    glueviz:      0.4.0-np19py27_0 

The following packages will be UPDATED:

    astropy:      0.4.1-np19py27_0  --> 1.0rc1-np19py27_0
    cairo:        1.12.2-2          --> 1.12.18-0        
    conda:        3.7.4-py27_0      --> 3.8.3-py27_0     
    matplotlib:   1.3.1-np18py27_1  --> 1.4.2-np19py27_0 
    numpy:        1.8.2-py27_0      --> 1.9.1-py27_0                                                                          
    openssl:      1.0.1j-4          --> 1.0.1k-0                                                                              
    pandas:       0.14.0-np18py27_0 --> 0.15.2-np19py27_0                                                                     
    py2cairo:     1.10.0-py27_1     --> 1.10.0-py27_2    
    pytz:         2014.3-py27_0     --> 2014.9-py27_0    
    scikit-image: 0.10.0-np18py27_0 --> 0.10.1-np19py27_0
    scipy:        0.14.0-np19py27_0 --> 0.15.1-np19py27_0
    setuptools:   5.8-py27_0        --> 12.0.5-py27_0    
    six:          1.6.1-py27_0      --> 1.9.0-py27_0     
    zlib:         1.2.7-0           --> 1.2.8-0          

Proceed ([y]/n)? 

Fetching packages ...
zlib-1.2.8-0.t 100% |##############################################################################| Time: 0:00:00 411.89 kB/s
openssl-1.0.1k 100% |##############################################################################| Time: 0:00:03 734.27 kB/s
cairo-1.12.18- 100% |##############################################################################| Time: 0:00:00 725.95 kB/s
py2cairo-1.10. 100% |##############################################################################| Time: 0:00:00 311.98 kB/s
conda-env-2.0. 100% |##############################################################################| Time: 0:00:00 152.59 kB/s
six-1.9.0-py27 100% |##############################################################################| Time: 0:00:00  81.40 kB/s
pytz-2014.9-py 100% |##############################################################################| Time: 0:00:01 156.16 kB/s
setuptools-12. 100% |##############################################################################| Time: 0:00:00 726.45 kB/s
scipy-0.15.1-n 100% |##############################################################################| Time: 0:00:25   1.54 MB/s
astropy-1.0rc1 100% |##############################################################################| Time: 0:00:20 380.62 kB/s
conda-3.8.3-py 100% |##############################################################################| Time: 0:00:00 396.18 kB/s
pandas-0.15.2- 100% |##############################################################################| Time: 0:00:07   1.36 MB/s
matplotlib-1.4 100% |##############################################################################| Time: 0:00:29   1.61 MB/s
scikit-image-0 100% |##############################################################################| Time: 0:00:14   1.57 MB/s
glueviz-0.4.0- 100% |##############################################################################| Time: 0:00:01 996.15 kB/s
Extracting packages ...
[      COMPLETE      ] |################################################################################################| 100%
Unlinking packages ...
[      COMPLETE      ] |################################################################################################| 100%
Linking packages ...
[      COMPLETE      ] |################################################################################################| 100%
```

**Comment by astrofrog** [comment]
Ah, I think I see the issue - more soon.

**Comment by astrofrog** [comment]
@nudomarinero - can you do (in python):

```
import PyQt4
print PyQt4.__path__
```

as well as:

```
import sys
print sys.path
```

and let me know the output? Also, can you do (on the command-line):

```
echo $PYTHONPATH
```

and let me know the output?

**Comment by nudomarinero** [comment]
@astrofrog - Yes, the first output is:
```
>>> import PyQt4
>>> print PyQt4.__path__
['/usr/lib/python2.7/dist-packages/PyQt4']
```
The second output:
```
>>> import sys
>>> print sys.path
['', '/home/jsm/.local/lib/python2.7/site-packages/opus-0.0.1-py2.7.egg', '/home/jsm/.local/lib/python2.7/site-packages/lsmtool-1.0.0-py2.7.egg', '/usr/lib/python2.7/dist-packages', '/home/jsm/programs/soft/anaconda/lib/python2.7/site-packages/opus-0.0.1-py2.7.egg', '/home/jsm/programs/soft/LofIm/lib/python2.7/site-packages', '/home/jsm/programs/soft/anaconda/lib/python27.zip', '/home/jsm/programs/soft/anaconda/lib/python2.7', '/home/jsm/programs/soft/anaconda/lib/python2.7/plat-linux2', '/home/jsm/programs/soft/anaconda/lib/python2.7/lib-tk', '/home/jsm/programs/soft/anaconda/lib/python2.7/lib-old', '/home/jsm/programs/soft/anaconda/lib/python2.7/lib-dynload', '/home/jsm/.local/lib/python2.7/site-packages', '/home/jsm/programs/soft/anaconda/lib/python2.7/site-packages', '/home/jsm/programs/soft/anaconda/lib/python2.7/site-packages/PIL', '/home/jsm/programs/soft/anaconda/lib/python2.7/site-packages/astropy-1.0rc1-py2.7-linux-x86_64.egg', '/home/jsm/programs/soft/anaconda/lib/python2.7/site-packages/glueviz-0.4.0-py2.7.egg', '/home/jsm/programs/soft/anaconda/lib/python2.7/site-packages/runipy-0.1.0-py2.7.egg', '/home/jsm/programs/soft/anaconda/lib/python2.7/site-packages/setuptools-12.0.5-py2.7.egg']
>>> 
```
And the last:
```
jsm@leda:~/programs/temp$ echo $PYTHONPATH
/home/jsm/programs/soft/LofIm/lib/python2.7/site-packages
```

**Comment by astrofrog** [comment]
@nudomarinero - thanks, and just one more thing to try before I investigate further - can you do:

```
conda update pyqt4
```

and let me know the output?

**Comment by nudomarinero** [comment]
@astrofrog - Apparently pyqt4 is not found.
```
jsm@leda:~/programs/temp$ conda update pyqt4
Error: package 'pyqt4' is not installed in /home/jsm/programs/soft/anaconda
jsm@leda:~/programs/temp$ conda install pyqt4
Fetching package metadata: ..
Error: No packages found in current linux-64 channels matching: pyqt4

Did you mean one of these?

    pyqt

You can search for this package on Binstar with

    binstar search -t conda pyqt4
```
Did you mean pyqt?
```
jsm@leda:~/programs/temp$ conda update pyqt
Fetching package metadata: ..
# All requested packages already installed.
# packages in environment at /home/jsm/programs/soft/anaconda:
#
pyqt                      4.10.4                   py27_0 
```

**Comment by astrofrog** [comment]
@nudomarinero - ah yes sorry, they call it ``pyqt``. Ok, so the issue seems to be that somehow ``PyQt4`` is getting picked up from the system installation rather than from Anaconda. I'm not 100% sure what is causing this, but could you try and do:

```
export $PYTHONPATH=""
```

in a terminal then try and launch ``glue`` again?

**Comment by nudomarinero** [comment]
@astrofrog - Yes, it looks like it is importing the system version of PyQt4. The ```export PYTHONPATH=""``` does not seem to work. I will try to look for a solution for that.

**Comment by astrofrog** [comment]
@nudomarinero - ok, thanks for your patience, I will look into it too. One more thing to try:

```
conda install pyside
export QT_API=pyside
glue
```

This might work because it tells glue to not use PyQt4 at all, but PySide instead (a different Qt wrapper).

**Comment by nudomarinero** [comment]
@astrofrog - No problem, I am happy to help with this. And yes, it works with pyside!

**Comment by astrofrog** [comment]
Ok, great to know, thanks for testing this!

@ChrisBeaumont - just to check, have you seen the PyQt error @nudomarinero was seeing before? Any idea about why it would use the system-installed version?

**Comment by ChrisBeaumont** [comment]
Hi @nudomarinero , @astrofrog 

This might be the same issue as #366 (which was on Kubuntu, but also using KDE, which is backed by Qt). Qt uses some weird logic I don't understand to load libraries, and it seems to sometimes override common environment variables. The punchline is that sometimes Anaconda loads system libraries instead of anaconda ones, and things break.

The relevant anaconda issue is https://github.com/ContinuumIO/anaconda-issues/issues/63. There are some workaround solutions posted on both tickets, but none of them are super satisfying. It's good to know that using PySide might sidestep the issue though.

**Comment by astrofrog** [comment]
@nudomarinero @ChrisBeaumont - I have opened a pull request to add a known issue to the docs:

https://github.com/glue-viz/glue/pull/570

Let me know if you have any comments before I merge it!

**Comment by nudomarinero** [comment]
For the record. Apparently the path "/usr/lib/python2.7/dist-packages" was added to my Python path somewhere very deep into my configuration files. Finally, I was able to remove that.
After this was removed, the possible mismatch of Qt libraries was solved with an ```export QT_PLUGIN_PATH=""```

**Comment by astrofrog** [comment]
@nudomarinero - good to know, thanks!
