### ISSUE TITLE
Dragging catalog dataset and asking for image widget results in silent error

### ISSUE THREAD

**Issue by astrofrog** [glue-viz/glue#580]
If I drag a catalog dataset into the main window, I just get the following error in the terminal:

```
WARNING: W42: None:2:0: W42: No XML namespace specified [astropy.io.votable.tree]
Traceback (most recent call last):
  File "/Users/tom/miniconda3/envs/gluedev27/lib/python3.4/site-packages/glueviz-0.5.0.dev0-py3.4.egg/glue/qt/widgets/glue_mdi_area.py", line 62, in dropEvent
    new_layer(layer)
  File "/Users/tom/miniconda3/envs/gluedev27/lib/python3.4/site-packages/glueviz-0.5.0.dev0-py3.4.egg/glue/qt/widgets/glue_mdi_area.py", line 52, in new_layer
    self._application.choose_new_data_viewer(layer)
  File "/Users/tom/miniconda3/envs/gluedev27/lib/python3.4/site-packages/glueviz-0.5.0.dev0-py3.4.egg/glue/qt/glue_application.py", line 573, in choose_new_data_viewer
    return self.do(cmd)
  File "/Users/tom/miniconda3/envs/gluedev27/lib/python3.4/site-packages/glueviz-0.5.0.dev0-py3.4.egg/glue/core/application_base.py", line 147, in do
    self._cmds.do(command)
  File "/Users/tom/miniconda3/envs/gluedev27/lib/python3.4/site-packages/glueviz-0.5.0.dev0-py3.4.egg/glue/core/command.py", line 125, in do
    result = cmd.do(self._session)
  File "/Users/tom/miniconda3/envs/gluedev27/lib/python3.4/site-packages/glueviz-0.5.0.dev0-py3.4.egg/glue/core/command.py", line 215, in do
    v = session.application.new_data_viewer(self.viewer, self.data)
  File "/Users/tom/miniconda3/envs/gluedev27/lib/python3.4/site-packages/glueviz-0.5.0.dev0-py3.4.egg/glue/qt/widgets/mpl_widget.py", line 38, in wrapper
    result = func(*args, **kwargs)
  File "/Users/tom/miniconda3/envs/gluedev27/lib/python3.4/site-packages/glueviz-0.5.0.dev0-py3.4.egg/glue/core/application_base.py", line 75, in new_data_viewer
    if data and not c.add_data(data):
  File "/Users/tom/miniconda3/envs/gluedev27/lib/python3.4/site-packages/glueviz-0.5.0.dev0-py3.4.egg/glue/qt/widgets/mpl_widget.py", line 38, in wrapper
    result = func(*args, **kwargs)
  File "/Users/tom/miniconda3/envs/gluedev27/lib/python3.4/site-packages/glueviz-0.5.0.dev0-py3.4.egg/glue/qt/widgets/image_widget.py", line 124, in add_data
    self.set_attribute_combo(self.client.display_data)
  File "/Users/tom/miniconda3/envs/gluedev27/lib/python3.4/site-packages/glueviz-0.5.0.dev0-py3.4.egg/glue/qt/widgets/image_widget.py", line 188, in set_attribute_combo
    labeldata = ((f.label, f) for f in data.visible_components)
AttributeError: 'NoneType' object has no attribute 'visible_components'
```

But no error in the app.

**Comment by astrofrog** [comment]
Possible fix in https://github.com/glue-viz/glue/pull/582
