### ISSUE TITLE
Improve traceback when errors are present in ``config.py``

### ISSUE THREAD

**Issue by astrofrog** [glue-viz/glue#647]
At the moment, the error traceback from problems in ``config.py`` is pretty unclear:

```
Traceback (most recent call last):
  File "/Users/tom/miniconda3/envs/production/lib/python3.4/site-packages/glueviz-0.5.0.dev0-py3.4.egg/glue/config.py", line 471, in load_configuration
    config = imp.load_source('config', config_file)
  File "/Users/tom/miniconda3/envs/production/lib/python3.4/imp.py", line 171, in load_source
    module = methods.load()
  File "<frozen importlib._bootstrap>", line 1220, in load
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/Users/tom/Desktop/spec/config.py", line 1, in <module>
    from glue.config import menubar_plugin
ImportError: cannot import name 'menubar_plugin'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tom/miniconda3/envs/production/bin/glue", line 9, in <module>
    load_entry_point('glueviz==0.5.0.dev0', 'console_scripts', 'glue')()
  File "/Users/tom/miniconda3/envs/production/lib/python3.4/site-packages/setuptools-17.0-py3.4.egg/pkg_resources/__init__.py", line 552, in load_entry_point
  File "/Users/tom/miniconda3/envs/production/lib/python3.4/site-packages/setuptools-17.0-py3.4.egg/pkg_resources/__init__.py", line 2672, in load_entry_point
  File "/Users/tom/miniconda3/envs/production/lib/python3.4/site-packages/setuptools-17.0-py3.4.egg/pkg_resources/__init__.py", line 2345, in load
  File "/Users/tom/miniconda3/envs/production/lib/python3.4/site-packages/setuptools-17.0-py3.4.egg/pkg_resources/__init__.py", line 2351, in resolve
  File "/Users/tom/miniconda3/envs/production/lib/python3.4/site-packages/glueviz-0.5.0.dev0-py3.4.egg/glue/__init__.py", line 127, in <module>
    env = load_configuration()
  File "/Users/tom/miniconda3/envs/production/lib/python3.4/site-packages/glueviz-0.5.0.dev0-py3.4.egg/glue/config.py", line 476, in load_configuration
    raise type(e)("Error loading config file %s:\n%s" % (config_file, e), sys.exc_info()[2])
ImportError: ("Error loading config file /Users/tom/Desktop/spec/config.py:\ncannot import name 'menubar_plugin'", <traceback object at 0x101308488>)
```

We should output something much more user-friendly.

**Comment by ChrisBeaumont** [comment]
What did you have in mind re: a clearer traceback/message?

**Comment by astrofrog** [comment]
To have the traceback that's currently on top be last would already be more helpful.
