### ISSUE TITLE
Spectrum tool and PV Slice tool do not appear in 0.5.1 

### ISSUE THREAD

**Issue by keflavich** [glue-viz/glue#697]
In 0.5.1, when I load a cube, the spectrum extraction and PV extraction tools are missing.  They are present for the same data in 0.4.

**Comment by astrofrog** [comment]
Did you install glue with conda or some other way? Also, do you see the 'Export' sub-menu in the 'File' menu, and does it contain 'Export D3PO' and 'Export Plotly'? Finally, can you let me know what the output is in the terminal when you start up glue with ``glue --verbose``?

**Comment by keflavich** [comment]
Installed from git clone with python setup.py develop.  More details later

**Comment by astrofrog** [comment]
Basically the spectrum tool and PV slice thing are now treated as plugins and registered via entry_points. It's possible that entry points don't work properly with 'develop'. Will try it out.

**Comment by astrofrog** [comment]
Hmm no it seems to work. So later, when you get a chance, send the output of ``glue --verbose``

**Comment by keflavich** [comment]
OK, so there's clearly something wrong with entry points that is specific to my setup

```
INFO:glue:Input arguments: ['/Users/adam/anaconda/envs/astropy27/bin/glue', '--verbose', 'ALMA_Outflow_b6_12M_12CO.fits']
INFO:glue.core.hub:Subscribing DataCollection (0 data sets)
	 to DataAddComponentMessage
INFO:glue.core.hub:Broadcasting DataCollectionAddMessage:
	 Sent from: DataCollection (1 data set)
	  0: ALMA_Outflow_b6_12M_12CO
INFO:glue:Loading external plugins
INFO:glue.core.hub:Subscribing <glue.qt.data_collection_model.DataCollectionModel object at 0x113f3b770> to DataCollectionDeleteMessage
INFO:glue.core.hub:Subscribing <glue.qt.data_collection_model.DataCollectionModel object at 0x113f3b770> to SubsetDeleteMessage
INFO:glue.core.hub:Subscribing <glue.qt.data_collection_model.DataCollectionModel object at 0x113f3b770> to DataCollectionAddMessage
INFO:glue.core.hub:Subscribing <glue.qt.data_collection_model.DataCollectionModel object at 0x113f3b770> to SubsetCreateMessage
2015-07-10 01:31:08.429 python[44817:507] modalSession has been exited prematurely - check for a reentrant call to endModalSession:
WARNING:glue.config:could not get default tools for GlueVTKViewer
INFO:glue.core.hub:Subscribing <glue.clients.image_client.MplImageClient object at 0x14256f3d0> to SubsetCreateMessage
INFO:glue.core.hub:Subscribing <glue.clients.image_client.MplImageClient object at 0x14256f3d0> to SubsetUpdateMessage
INFO:glue.core.hub:Subscribing <glue.clients.image_client.MplImageClient object at 0x14256f3d0> to SubsetDeleteMessage
INFO:glue.core.hub:Subscribing <glue.clients.image_client.MplImageClient object at 0x14256f3d0> to DataUpdateMessage
INFO:glue.core.hub:Subscribing <glue.clients.image_client.MplImageClient object at 0x14256f3d0> to NumericalDataChangedMessage
INFO:glue.core.hub:Subscribing <glue.clients.image_client.MplImageClient object at 0x14256f3d0> to DataCollectionDeleteMessage
INFO:glue.core.hub:Subscribing <glue.clients.image_client.MplImageClient object at 0x14256f3d0> to ComponentReplacedMessage
INFO:glue.core.hub:Subscribing Image Widget to DataCollectionAddMessage
INFO:glue.core.hub:Subscribing Image Widget to DataCollectionDeleteMessage
INFO:glue.core.hub:Subscribing Image Widget to DataUpdateMessage
INFO:glue.core.hub:Subscribing Image Widget to ComponentsChangedMessage
/Users/adam/anaconda/envs/astropy27/lib/python2.7/site-packages/matplotlib/text.py:52: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if rotation in ('horizontal', None):
/Users/adam/anaconda/envs/astropy27/lib/python2.7/site-packages/matplotlib/text.py:54: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  elif rotation == 'vertical':
```


my config file:
```
from glue.config import colormaps
import matplotlib.cm
colormaps.add('Spectral',matplotlib.cm.spectral)
colormaps.add('jet',matplotlib.cm.jet)
colormaps.add('gist_earth',matplotlib.cm.gist_earth)
colormaps.add('gist_stern',matplotlib.cm.gist_stern)

def change_backgrounds(color, application):
    for viewers in application.viewers:
        for v in viewers:
            v.axes.set_axis_bgcolor(color)

def blackbg():
    change_backgrounds('black', globals()['application'])

from glue.qt import get_qapp
app = get_qapp()
#app.setStyleSheet("{ background-color: black }")

from glue.qt.widgets import enable_dendrograms
enable_dendrograms()

from glue.config import qt_client
try:
    qt_client.lazy_add('cube_viewer.glue_plugin')
except AttributeError:
    # lazy_add is in >v0.5
    pass
```

**Comment by keflavich** [comment]
Also I have no `export` menu under the `file` menu

**Comment by astrofrog** [comment]
Thanks - could you paste the output of ``python setup.py develop``?

**Comment by keflavich** [comment]
```
cyg ~/repos/glue remotes/upstream/stable$ git rev-parse HEAD
5cc966203788241adb94dd0fcbc30d9fa1a9bd26
cyg ~/repos/glue remotes/upstream/stable$ python setup.py develop
running develop
running egg_info
writing glueviz.egg-info/PKG-INFO
writing top-level names to glueviz.egg-info/top_level.txt
writing dependency_links to glueviz.egg-info/dependency_links.txt
writing entry points to glueviz.egg-info/entry_points.txt
reading manifest file 'glueviz.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'glueviz.egg-info/SOURCES.txt'
running build_ext
Creating /Users/adam/anaconda/envs/astropy27/lib/python2.7/site-packages/glueviz.egg-link (link to .)
glueviz 0.5.1 is already the active version in easy-install.pth
Installing glue-config script to /Users/adam/anaconda/envs/astropy27/bin
Installing glue script to /Users/adam/anaconda/envs/astropy27/bin
Installing glue-deps script to /Users/adam/anaconda/envs/astropy27/bin

Installed /Users/adam/repos/glue
Processing dependencies for glueviz==0.5.1
Finished processing dependencies for glueviz==0.5.1
```

**Comment by astrofrog** [comment]
Thanks, could you let me know the contents of ``glueviz.egg-info/entry_points.txt`` in the repo?

**Comment by keflavich** [comment]
I should've guessed:
```
cyg ~/repos/glue remotes/upstream/stable$ cat ./glueviz.egg-info/entry_points.txt

[glue.plugins]
ginga_viewer = glue.plugins.ginga_viewer:setup
export_d3po = glue.plugins.export_d3po:setup
export_plotly = glue.plugins.export_plotly:setup
pv_slicer = glue.plugins.tools.pv_slicer:setup
spectrum_tool = glue.plugins.tools.spectrum_tool:setup
coordinate_helpers = glue.plugins.coordinate_helpers:setup

[console_scripts]
glue = glue.main:main
glue-config = glue.config_gen:main
glue-deps = glue._deps:main
```
looks fine?  or is the `:setup` a problem?

**Comment by astrofrog** [comment]
No this all looks fine. Ok, one more thing to try: open the IPython console inside Glue and type:

from glue._plugin_helpers import iter_plugin_entry_points
print(list(iter_plugin_entry_points()))

What does this output? Thanks!

**Comment by keflavich** [comment]
```
from glue._plugin_helpers import iter_plugin_entry_points
print(list(iter_plugin_entry_points()))

[]
```

**Comment by astrofrog** [comment]
Huh.

**Comment by astrofrog** [comment]
Ok, for fun, can you now type that in IPython (for the same Python installation) outside of glue? (that is, the normal IPython)

**Comment by keflavich** [comment]
Whoa:
```
In [1]: %paste
from glue._plugin_helpers import iter_plugin_entry_points
print(list(iter_plugin_entry_points()))

## -- End pasted text --
[EntryPoint.parse('ginga_viewer = glue.plugins.ginga_viewer:setup'), EntryPoint.parse('export_plotly = glue.plugins.export_plotly:setup'), EntryPoint.parse('export_d3po = glue.plugins.export_d3po:setup'), EntryPoint.parse('pv_slicer = glue.plugins.tools.pv_slicer:setup'), EntryPoint.parse('spectrum_tool = glue.plugins.tools.spectrum_tool:setup'), EntryPoint.parse('coordinate_helpers = glue.plugins.coordinate_helpers:setup')]

```

**Comment by astrofrog** [comment]
um, what.

**Comment by keflavich** [comment]
fwiw:
```
cyg ~$ which ipython
/Users/adam/anaconda/envs/astropy27/bin/ipython
cyg ~$ which glue
/Users/adam/anaconda/envs/astropy27/bin/glue
```
same env

**Comment by astrofrog** [comment]
In IPython in glue, can you check:

```
import glue
glue.__path__
```

?

**Comment by keflavich** [comment]
```
import glue
glue.__path__

Out[2]: ['/Users/adam/repos/glue/glue']
```

(same in cmd line)

**Comment by astrofrog** [comment]
What setuptools version do you have installed?

**Comment by keflavich** [comment]
```
cyg ~$ python -c "import setuptools; print setuptools.__version__"
0.6
```
that... seems like an incomplete version #....

**Comment by keflavich** [comment]
updating setuptools with conda `    setuptools: 17.1.1-py27_0 --> 18.0.1-py27_0` had no effect

**Comment by astrofrog** [comment]
Huh wait, how did it say 0.6 but then updated from 17? Does `` python -c "import setuptools; print setuptools.__version__"`` give 18.0.1 now? or still 0.6?

**Comment by keflavich** [comment]
still 0.6

**Comment by keflavich** [comment]
```
cyg ~$ python -c "import setuptools; print setuptools.__version__; print setuptools.__path__"
0.6
['/Users/adam/anaconda/envs/astropy27/lib/python2.7/site-packages/setuptools']
```
??

**Comment by astrofrog** [comment]
Ah, I found out that the entry points only start working at some point between setuptools 5 and 11 (need to refine further). In the mean time, I wonder if you have a pip installed version overriding the conda one. Try conda removing setuptools and also remove the directory manually, then re-install.

**Comment by astrofrog** [comment]
Just tested, and Glue only works correctly for setuptools >= 11.3. Need to find a workaround for earlier versions, but 0.6 is definitely very old.

**Comment by keflavich** [comment]
OK, this is now a conda issue, but after conda uninstalling and removing all setuptools directories, I had to `conda install -f setuptools` and then I get:
```
cyg ~/repos/glue remotes/upstream/stable$ python setup.py develop
Traceback (most recent call last):
  File "setup.py", line 4, in <module>
    from setuptools import setup, Command, find_packages
  File "/Users/adam/anaconda/envs/astropy27/lib/python2.7/site-packages/setuptools-18.0.1-py2.7.egg/setuptools/__init__.py", line 11, in <module>

  File "/Users/adam/anaconda/envs/astropy27/lib/python2.7/site-packages/setuptools-18.0.1-py2.7.egg/setuptools/extension.py", line 8, in <module>
  File "/Users/adam/anaconda/envs/astropy27/lib/python2.7/site-packages/setuptools-18.0.1-py2.7.egg/setuptools/dist.py", line 21, in <module>
AttributeError: 'module' object has no attribute 'packaging'
```
I'll revisit this tomorrow... have to sleep.

**Comment by keflavich** [comment]
I had to re-install setuptools from source; conda installing led to the above error, which also broke pip.  This issue is resolved for me now, though.

**Comment by astrofrog** [comment]
This is now fixed in glueviz 0.5.2 (i.e. it will work with old versions of setuptools)

**Comment by keflavich** [comment]
This issue is recurring for me:
```
cyg ~$ python -c "import setuptools; print(setuptools.__version__)"
27.2.0
cyg ~$ python -c "import glue.plugins.tools.spectrum_tool"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'glue.plugins.tools.spectrum_tool'
cyg ~/repos/glue master$ python setup.py develop
running develop
running egg_info
writing glue_core.egg-info/PKG-INFO
writing dependency_links to glue_core.egg-info/dependency_links.txt
writing entry points to glue_core.egg-info/entry_points.txt
writing requirements to glue_core.egg-info/requires.txt
writing top-level names to glue_core.egg-info/top_level.txt
reading manifest file 'glue_core.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'README.md'
writing manifest file 'glue_core.egg-info/SOURCES.txt'
running build_ext
Creating /Users/adam/anaconda/envs/astropy36mpl2/lib/python3.6/site-packages/glue-core.egg-link (link to .)
glue-core 0.13.0.dev4576 is already the active version in easy-install.pth
Installing glue-config script to /Users/adam/anaconda/envs/astropy36mpl2/bin
Installing glue-deps script to /Users/adam/anaconda/envs/astropy36mpl2/bin
Installing glue script to /Users/adam/anaconda/envs/astropy36mpl2/bin

Installed /Users/adam/repos/glue
Processing dependencies for glue-core==0.13.0.dev4576
Searching for mpl-scatter-density==0.3
Best match: mpl-scatter-density 0.3
Adding mpl-scatter-density 0.3 to easy-install.pth file

Using /Users/adam/anaconda/envs/astropy36mpl2/lib/python3.6/site-packages
Searching for Bottleneck==1.2.1
Best match: Bottleneck 1.2.1
Adding Bottleneck 1.2.1 to easy-install.pth file

Using /Users/adam/anaconda/envs/astropy36mpl2/lib/python3.6/site-packages
Searching for h5py==2.8.0rc1
Best match: h5py 2.8.0rc1
Processing h5py-2.8.0rc1-py3.6-macosx-10.7-x86_64.egg
h5py 2.8.0rc1 is already the active version in easy-install.pth

Using /Users/adam/anaconda/envs/astropy36mpl2/lib/python3.6/site-packages/h5py-2.8.0rc1-py3.6-macosx-10.7-x86_64.egg
Searching for xlrd==1.1.0
Best match: xlrd 1.1.0
Processing xlrd-1.1.0-py3.6.egg
xlrd 1.1.0 is already the active version in easy-install.pth
Installing runxlrd.py script to /Users/adam/anaconda/envs/astropy36mpl2/bin

Using /Users/adam/anaconda/envs/astropy36mpl2/lib/python3.6/site-packages/xlrd-1.1.0-py3.6.egg
Searching for dill==0.2.7.1
Best match: dill 0.2.7.1
Processing dill-0.2.7.1-py3.6.egg
dill 0.2.7.1 is already the active version in easy-install.pth
Installing dill_unpickle.py script to /Users/adam/anaconda/envs/astropy36mpl2/bin
Installing get_objgraph.py script to /Users/adam/anaconda/envs/astropy36mpl2/bin

Using /Users/adam/anaconda/envs/astropy36mpl2/lib/python3.6/site-packages/dill-0.2.7.1-py3.6.egg
Searching for qtconsole==4.3.1
Best match: qtconsole 4.3.1
Processing qtconsole-4.3.1-py3.6.egg
qtconsole 4.3.1 is already the active version in easy-install.pth
Installing jupyter-qtconsole script to /Users/adam/anaconda/envs/astropy36mpl2/bin

Using /Users/adam/anaconda/envs/astropy36mpl2/lib/python3.6/site-packages/qtconsole-4.3.1-py3.6.egg
Searching for ipykernel==4.8.2
Best match: ipykernel 4.8.2
Adding ipykernel 4.8.2 to easy-install.pth file

Using /Users/adam/anaconda/envs/astropy36mpl2/lib/python3.6/site-packages
Searching for ipython==6.1.0
Best match: ipython 6.1.0
Adding ipython 6.1.0 to easy-install.pth file

Using /Users/adam/anaconda/envs/astropy36mpl2/lib/python3.6/site-packages
Searching for setuptools==27.2.0
Best match: setuptools 27.2.0
Processing setuptools-27.2.0-py3.6.egg
setuptools 27.2.0 is already the active version in easy-install.pth
Installing easy_install script to /Users/adam/anaconda/envs/astropy36mpl2/bin
Installing easy_install-3.6 script to /Users/adam/anaconda/envs/astropy36mpl2/bin

Using /Users/adam/anaconda/envs/astropy36mpl2/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg
Searching for QtPy==1.4.0
Best match: QtPy 1.4.0
Processing QtPy-1.4.0-py3.6.egg
QtPy 1.4.0 is already the active version in easy-install.pth

Using /Users/adam/anaconda/envs/astropy36mpl2/lib/python3.6/site-packages/QtPy-1.4.0-py3.6.egg
Searching for matplotlib==2.2.2
Best match: matplotlib 2.2.2
Adding matplotlib 2.2.2 to easy-install.pth file

Using /Users/adam/anaconda/envs/astropy36mpl2/lib/python3.6/site-packages
Searching for astropy==3.1.dev21531
Best match: astropy 3.1.dev21531
astropy 3.1.dev21531 is already the active version in easy-install.pth
Installing fits2bitmap script to /Users/adam/anaconda/envs/astropy36mpl2/bin
Installing fitscheck script to /Users/adam/anaconda/envs/astropy36mpl2/bin
Installing fitsdiff script to /Users/adam/anaconda/envs/astropy36mpl2/bin
Installing fitsheader script to /Users/adam/anaconda/envs/astropy36mpl2/bin
Installing fitsinfo script to /Users/adam/anaconda/envs/astropy36mpl2/bin
Installing samp_hub script to /Users/adam/anaconda/envs/astropy36mpl2/bin
Installing showtable script to /Users/adam/anaconda/envs/astropy36mpl2/bin
Installing volint script to /Users/adam/anaconda/envs/astropy36mpl2/bin
Installing wcslint script to /Users/adam/anaconda/envs/astropy36mpl2/bin

Using /Users/adam/repos/astropy
Searching for pandas==0.22.0
Best match: pandas 0.22.0
Adding pandas 0.22.0 to easy-install.pth file

Using /Users/adam/anaconda/envs/astropy36mpl2/lib/python3.6/site-packages
Searching for numpy==1.13.3
Best match: numpy 1.13.3
Adding numpy 1.13.3 to easy-install.pth file

Using /Users/adam/anaconda/envs/astropy36mpl2/lib/python3.6/site-packages
Searching for fast-histogram==0.4
Best match: fast-histogram 0.4
Adding fast-histogram 0.4 to easy-install.pth file

Using /Users/adam/anaconda/envs/astropy36mpl2/lib/python3.6/site-packages
Searching for six==1.10.0
Best match: six 1.10.0
Adding six 1.10.0 to easy-install.pth file

Using /Users/adam/anaconda/envs/astropy36mpl2/lib/python3.6/site-packages
Searching for Pygments==2.2.0
Best match: Pygments 2.2.0
Adding Pygments 2.2.0 to easy-install.pth file

Using /Users/adam/anaconda/envs/astropy36mpl2/lib/python3.6/site-packages
Searching for jupyter-client==5.2.3
Best match: jupyter-client 5.2.3
Adding jupyter-client 5.2.3 to easy-install.pth file
Installing jupyter-kernel script to /Users/adam/anaconda/envs/astropy36mpl2/bin
Installing jupyter-kernelspec script to /Users/adam/anaconda/envs/astropy36mpl2/bin
Installing jupyter-run script to /Users/adam/anaconda/envs/astropy36mpl2/bin

Using /Users/adam/anaconda/envs/astropy36mpl2/lib/python3.6/site-packages
Searching for jupyter-core==4.4.0
Best match: jupyter-core 4.4.0
Adding jupyter-core 4.4.0 to easy-install.pth file
Installing jupyter script to /Users/adam/anaconda/envs/astropy36mpl2/bin
Installing jupyter-migrate script to /Users/adam/anaconda/envs/astropy36mpl2/bin
Installing jupyter-troubleshoot script to /Users/adam/anaconda/envs/astropy36mpl2/bin

Using /Users/adam/anaconda/envs/astropy36mpl2/lib/python3.6/site-packages
Searching for ipython-genutils==0.2.0
Best match: ipython-genutils 0.2.0
Adding ipython-genutils 0.2.0 to easy-install.pth file

Using /Users/adam/anaconda/envs/astropy36mpl2/lib/python3.6/site-packages
Searching for traitlets==4.3.2
Best match: traitlets 4.3.2
Adding traitlets 4.3.2 to easy-install.pth file

Using /Users/adam/anaconda/envs/astropy36mpl2/lib/python3.6/site-packages
Searching for tornado==5.0
Best match: tornado 5.0
Adding tornado 5.0 to easy-install.pth file

Using /Users/adam/anaconda/envs/astropy36mpl2/lib/python3.6/site-packages
Searching for kiwisolver==1.0.1
Best match: kiwisolver 1.0.1
Adding kiwisolver 1.0.1 to easy-install.pth file

Using /Users/adam/anaconda/envs/astropy36mpl2/lib/python3.6/site-packages
Searching for pytz==2017.2
Best match: pytz 2017.2
Adding pytz 2017.2 to easy-install.pth file

Using /Users/adam/anaconda/envs/astropy36mpl2/lib/python3.6/site-packages
Searching for python-dateutil==2.6.0
Best match: python-dateutil 2.6.0
Adding python-dateutil 2.6.0 to easy-install.pth file

Using /Users/adam/anaconda/envs/astropy36mpl2/lib/python3.6/site-packages
Searching for pyparsing==2.1.4
Best match: pyparsing 2.1.4
Adding pyparsing 2.1.4 to easy-install.pth file

Using /Users/adam/anaconda/envs/astropy36mpl2/lib/python3.6/site-packages
Searching for cycler==0.10.0
Best match: cycler 0.10.0
Adding cycler 0.10.0 to easy-install.pth file

Using /Users/adam/anaconda/envs/astropy36mpl2/lib/python3.6/site-packages
Searching for pyzmq==17.0.0
Best match: pyzmq 17.0.0
Adding pyzmq 17.0.0 to easy-install.pth file

Using /Users/adam/anaconda/envs/astropy36mpl2/lib/python3.6/site-packages
Finished processing dependencies for glue-core==0.13.0.dev4576
cyg ~/repos/glue master$ python -c "from glue._plugin_helpers import iter_plugin_entry_points; print('\n'.join(map(str,(iter_plugin_entry_points()))))"
export_d3po = glue.plugins.export_d3po:setup
export_plotly = glue.plugins.exporters.plotly:setup
pv_slicer = glue.plugins.tools.pv_slicer:setup
coordinate_helpers = glue.plugins.coordinate_helpers:setup
spectral_cube = glue.plugins.data_factories.spectral_cube:setup
dendro_viewer = glue.plugins.dendro_viewer:setup
image_viewer = glue.viewers.image:setup
scatter_viewer = glue.viewers.scatter:setup
histogram_viewer = glue.viewers.histogram:setup
profile_viewer = glue.viewers.profile:setup
table_viewer = glue.viewers.table:setup
data_exporters = glue.core.data_exporters:setup
fits_format = glue.io.formats.fits:setup
export_python = glue.plugins.tools:setup
export_d3po = glue.plugins.export_d3po:setup
export_plotly = glue.plugins.exporters.plotly:setup
pv_slicer = glue.plugins.tools.pv_slicer:setup
spectrum_tool = glue.plugins.tools.spectrum_tool:setup
coordinate_helpers = glue.plugins.coordinate_helpers:setup
spectral_cube = glue.plugins.data_factories.spectral_cube:setup
dendro_viewer = glue.plugins.dendro_viewer:setup
image_viewer = glue.viewers.image:setup
scatter_viewer = glue.viewers.scatter:setup
histogram_viewer = glue.viewers.histogram:setup
table_viewer = glue.viewers.table:setup
data_exporters = glue.core.data_exporters:setup
ginga = glue_ginga:setup
vispy_volume = glue_vispy_viewers.volume:setup
vispy_scatter = glue_vispy_viewers.scatter:setup
specviz_plugin = specviz.app:glue_setup
cubeviz = cubeviz.cubeviz:setup
```

**Comment by keflavich** [comment]
Solved; needed to remove a line in `main.py`.
