### ISSUE TITLE
Bug in categorical ROI

### ISSUE THREAD

**Issue by astrofrog** [glue-viz/glue#718]
Following #601, if I generate the following dataset and open it in glue:

```python
import numpy as np
from astropy.table import Table

t = Table()
t['a'] = ['a','b','c'] * 10
t['b'] = np.random.random(30)
t.write('test.fits', overwrite=True)
```

then try and make a scatter plot and select something, I get:

```python
Traceback (most recent call last):
  File "/Volumes/Raptor/miniconda3/envs/production/lib/python3.4/site-packages/matplotlib/backends/backend_qt5.py", line 291, in mouseReleaseEvent
    FigureCanvasBase.button_release_event(self, x, y, button)
  File "/Volumes/Raptor/miniconda3/envs/production/lib/python3.4/site-packages/matplotlib/backend_bases.py", line 1910, in button_release_event
    self.callbacks.process(s, event)
  File "/Volumes/Raptor/miniconda3/envs/production/lib/python3.4/site-packages/matplotlib/cbook.py", line 540, in process
    proxy(*args, **kwargs)
  File "/Volumes/Raptor/miniconda3/envs/production/lib/python3.4/site-packages/matplotlib/cbook.py", line 415, in __call__
    return mtd(*args, **kwargs)
  File "/Volumes/Raptor/miniconda3/envs/production/lib/python3.4/site-packages/glue/qt/mouse_mode.py", line 222, in release
    self._finish_roi(event)
  File "/Volumes/Raptor/miniconda3/envs/production/lib/python3.4/site-packages/glue/qt/mouse_mode.py", line 175, in _finish_roi
    self._roi_callback(self)
  File "/Volumes/Raptor/miniconda3/envs/production/lib/python3.4/site-packages/glue/qt/widgets/scatter_widget.py", line 110, in apply_mode
    return self.apply_roi(mode.roi())
  File "/Volumes/Raptor/miniconda3/envs/production/lib/python3.4/site-packages/glue/qt/decorators.py", line 20, in result
    return func(*args, **kwargs)
  File "/Volumes/Raptor/miniconda3/envs/production/lib/python3.4/site-packages/glue/core/application_base.py", line 299, in apply_roi
    self._session.command_stack.do(cmd)
  File "/Volumes/Raptor/miniconda3/envs/production/lib/python3.4/site-packages/glue/core/command.py", line 125, in do
    result = cmd.do(self._session)
  File "/Volumes/Raptor/miniconda3/envs/production/lib/python3.4/site-packages/glue/core/command.py", line 260, in do
    self.client.apply_roi(self.roi)
  File "/Volumes/Raptor/miniconda3/envs/production/lib/python3.4/site-packages/glue/clients/scatter_client.py", line 293, in apply_roi
    subset_state = self._process_categorical_roi(roi)
  File "/Volumes/Raptor/miniconda3/envs/production/lib/python3.4/site-packages/glue/clients/scatter_client.py", line 273, in _process_categorical_roi
    raise AssertionError
AssertionError
```

cc @JudoWill

**Comment by astrofrog** [comment]
The error happens for a circular ROI. This should raise a better error. For the rectangular ROI, nothing happens (no error and no selection)

**Comment by astrofrog** [comment]
There are other exceptions when doing various rectangular selections (e.g. going too far on the left)

**Comment by astrofrog** [comment]
@JudoWill - just to check, would you have time to look into these issues today or tomorrow? If not, I'll try and look into them since they are critical.

**Comment by astrofrog** [comment]
So just to be clear:

* A better exception should be raised when the ROI is not rectangular. Ideally the circular and lasso selection should not even be present for the scatter widget if there is categorical data I guess?

* If you try and use the horizontal range selector, you also get various errors or the selection looks wrong. Try and select the three different columns of data in turn.

**Comment by JudoWill** [comment]
I'll check out the multiple selection bug today.

The circular and lasso roi are undefined on a categorical axis ...
especially since my last refactoring where I changed the ROI to store the
actual categories. This fixed a lot of bugs related to joining multiple
datasets (with overlapping categories and dealing with link functions
converting between representations (for example, M/F vs Male/Female) but
made it impractical to keep the circular ROI.

A better error message would be easy. I don't have enough knowledge of the
GUI to adjust the selectors that are present on the widget. Any suggestions?

**Comment by astrofrog** [comment]
@JudoWill - thanks! Just before we get rid of it completely, I wonder if we could simply consider interpolating e.g. circular and lasso ROIs at the position of the categories in the plot and transform them on-the-fly into some kind of rectangular ROI but where the range depends on the category? (then it would behave intuitively). What do you think?

Otherwise, for now a better error message would do, and later I can look into disabling those ROIs later.

**Comment by astrofrog** [comment]
Essentially I'm suggesting adding a new kind of ROI which is a category-dependent range for categorical data. Then we can transform any selection on the screen into that.

**Comment by ChrisBeaumont** [comment]
>  I wonder if we could simply consider interpolating e.g. circular and lasso ROIs at the position of the categories in the plot and transform them on-the-fly into some kind of rectangular ROI but where the range depends on the category

This is my preferred approach. I think we should think of a categorical axis as partitioning that axis into slabs for each category, and each category is "in" the ROI if any part of the slab overlaps the shape.

**Comment by astrofrog** [comment]
@JudoWill - I guess there is also some overlap with https://github.com/glue-viz/glue/pull/692, which hasn't been merged. So maybe it makes sense to do the fixes described here as part of #692.

**Comment by astrofrog** [comment]
I have an immediate fix for the selection bug that I will open a PR for very soon, just to make sure that things works properly.

**Comment by astrofrog** [comment]
This has all been fixed in https://github.com/glue-viz/glue/pull/834
