### ISSUE TITLE
Can not import Sprite

### ISSUE THREAD

**Issue by JaredZheng** [glue-viz/glue#740]
The error message appeared when I tried to start glue in the command line:

```
===============================================================
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/glue", line 9, in <module>
    load_entry_point('glue==0.11.1', 'console_scripts', 'glue')()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 552, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2672, in load_entry_point
    return ep.load()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2345, in load
    return self.resolve()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2351, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/glue/bin.py", line 11, in <module>
    from glue import managers
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/glue/managers/__init__.py", line 1, in <module>
    from .project import ProjectManager
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/glue/managers/project.py", line 4, in <module>
    from .base import BaseManager
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/glue/managers/base.py", line 1, in <module>
    from glue.core import Sprite
ImportError: cannot import name Sprite
===============================================================
```

**Comment by astrofrog** [comment]
@JaredZheng - it looks like you have the 'glue' package from PyPI installed, which is different from the package here, which is called 'glueviz' on PyPI. If you are interested in our package, you need to ``pip install glueviz``, and make sure you uninstall the other glue package.

**Comment by JaredZheng** [comment]
@astrofrog Thanks! That works well!
