### ISSUE TITLE
Fix Mac app build

### ISSUE THREAD

**Issue by astrofrog** [glue-viz/glue#873]
The Mac app build is currently not loading the entry points correctly:

```
INFO:glue:Loading plugin scatter_viewer failed (Exception: 'NoneType' object has no attribute 'requires')
INFO:glue:Loading plugin ginga_viewer failed (Exception: 'NoneType' object has no attribute 'requires')
INFO:glue:Loading plugin pv_slicer failed (Exception: 'NoneType' object has no attribute 'requires')
INFO:glue:Loading plugin histogram_viewer failed (Exception: 'NoneType' object has no attribute 'requires')
INFO:glue:Loading plugin image_viewer failed (Exception: 'NoneType' object has no attribute 'requires')
INFO:glue:Loading plugin dendro_viewer failed (Exception: 'NoneType' object has no attribute 'requires')
INFO:glue:Loading plugin coordinate_helpers failed (Exception: 'NoneType' object has no attribute 'requires')
...
```

**Comment by astrofrog** [comment]
The app launches, but upon creating an image widget, the following error occurs:

```
Traceback (most recent call last):
  File "glue/app/qt/mdi_area.pyc", line 61, in dropEvent
  File "glue/app/qt/mdi_area.pyc", line 51, in new_layer
  File "glue/app/qt/application.pyc", line 690, in choose_new_data_viewer
  File "glue/core/application_base.pyc", line 170, in do
  File "glue/core/command.pyc", line 126, in do
  File "glue/core/command.pyc", line 216, in do
  File "glue/viewers/common/qt/mpl_widget.pyc", line 37, in wrapper
  File "glue/core/application_base.pyc", line 72, in new_data_viewer
  File "glue/viewers/image/qt/viewer_widget.pyc", line 60, in __init__
  File "glue/viewers/image/qt/viewer_widget.pyc", line 459, in _connect
  File "glue/viewers/image/qt/viewer_widget.pyc", line 207, in _connect
```

This suggests that the ``RGBEdit`` class is not getting loaded correctly by PySide.

**Comment by astrofrog** [comment]
The app is finally fixed! :)
