### ISSUE TITLE
Missing Qt import

### ISSUE THREAD

**Issue by astrofrog** [glue-viz/glue#892]
```
Traceback (most recent call last):
  File "/Users/tom/miniconda3/envs/stable-glue/lib/python3.5/site-packages/glue/viewers/common/qt/mpl_widget.py", line 113, in paintEvent
    self.roi_callback(self)
  File "/Users/tom/miniconda3/envs/stable-glue/lib/python3.5/site-packages/glue/core/qt/roi.py", line 41, in _paint_check
    self.paint(canvas)
  File "/Users/tom/miniconda3/envs/stable-glue/lib/python3.5/site-packages/glue/core/qt/roi.py", line 45, in paint
    self.draw_polygon(canvas, x, y)
  File "/Users/tom/miniconda3/envs/stable-glue/lib/python3.5/site-packages/glue/core/qt/roi.py", line 97, in draw_polygon
    p = self.get_painter(canvas)
  File "/Users/tom/miniconda3/envs/stable-glue/lib/python3.5/site-packages/glue/core/qt/roi.py", line 86, in get_painter
    p.setBrush(Qt.NoBrush)
NameError: name 'Qt' is not defined
```

**Comment by astrofrog** [comment]
Closed by #901
