### ISSUE TITLE
API QString has already been set to version 1

### ISSUE THREAD

**Issue by philastrophist** [glue-viz/glue#995]
So when I import qglue I get this traceback when running it from pycharm using an anaconda installation:
```
from glue import qglue
```
gives
  ```
File "/home/user/local/Dropbox/TheFIRC3/scripts/gluetest.py", line 10, in <module>
    from glue import qglue
  File "/local/home/user/Apps/anaconda/lib/python2.7/site-packages/glue/__init__.py", line 12, in <module>
    setapi('QString', 2)
ValueError: API 'QString' has already been set to version 1
```

But it runs fine in a terminal using ipython from the same anaconda installation

**Comment by astrofrog** [comment]
Is PyCharm based on Qt? If not, did you run any other Qt application before running Glue?

Basically version 2 of the string API means that Qt strings are the same as Python strings, and makes a lot of development easier.

**Comment by philastrophist** [comment]
I don't think so and I didn't open anything before Glue :/

Also, when attempting to open fits files directly from the GUI in linux, there is a `data load error`

```
Error message: 'QString' object has no attribute 'rfind'

Traceback (most recent call last):
  File "/local/home/sread/Apps/anaconda/lib/python2.7/site-packages/glue/dialogs/data_wizard/qt/data_wizard_dialog.py", line 36, in data_wizard
    result = gdd.load_data()
  File "/local/home/sread/Apps/anaconda/lib/python2.7/site-packages/glue/utils/qt/decorators.py", line 23, in result
    return func(*args, **kwargs)
  File "/local/home/sread/Apps/anaconda/lib/python2.7/site-packages/glue/dialogs/data_wizard/qt/data_wizard_dialog.py", line 105, in load_data
    d = load_data(path, factory=fac.function)
  File "/local/home/sread/Apps/anaconda/lib/python2.7/site-packages/glue/core/data_factories/helpers.py", line 235, in load_data
    lbl = data_label(path)
  File "/local/home/sread/Apps/anaconda/lib/python2.7/site-packages/glue/core/data_factories/helpers.py", line 257, in data_label
    _, fname = os.path.split(path)
  File "/home/sread/local/Apps/anaconda/lib/python2.7/posixpath.py", line 85, in split
    i = p.rfind('/') + 1
AttributeError: 'QString' object has no attribute 'rfind'
```

**Comment by astrofrog** [comment]
@philastrophist - what does ``gluetest.py`` contain?

**Comment by philastrophist** [comment]
@astrofrog where is gluetest.py ?

**Comment by astrofrog** [comment]
Ah sorry I just meant the file you appeared to be running:

```
/home/user/local/Dropbox/TheFIRC3/scripts/gluetest.py
```

**Comment by philastrophist** [comment]
Ah right. Here it is:

```
import numpy as np

def gaussian(x, mu, sig):
    return np.exp(-np.power(x - mu, 2.) / (2 * np.power(sig, 2.)))

n, m = 10, 100
x = np.arange(n)
y = np.arange(n)


pdfs = np.zeros([n, n, m])
values = np.zeros([n, n])
z = np.linspace(0, 1, m)
for i in x:
    for j in y:
        mu, sig = np.random.rand(2)
        pdfs[i, j] = gaussian(z, mu, sig)
        values[i, j] = mu

from glue import qglue

```

**Comment by philastrophist** [comment]
however, if I just run  
```
import numpy as np
from glue import qglue
qglue(data=np.zeros(100))
```
it works

**Comment by philastrophist** [comment]
After some tedious (and, in hindsight unnecessary) research, I have found that you need to import glue before you import matplotlib.pyplot.  
I assume this is expected behaviour, but if I do this, will this api change break certain matplotlib functionalities?

**Comment by astrofrog** [comment]
@philastrophist - thanks for figuring this out! I don't think it will cause issues with Matplotlib, since we use Matplotlib inside glue itself, so it is compatible with version 2 of the API.
